// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include <array>
#include <cmath>
#include <complex>
#include <random>
#include <functional>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <initializer_list>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

#define _Static_assert static_assert
namespace std { using ::sinf; using ::cosf; using ::tanf; using ::asinf; using ::acosf; using ::atanf; using ::atan2f; using ::sqrtf; using ::expf; using ::logf; using ::log10f; using ::powf; }

// DSO-local thread-local variables definition




namespace Card_CraftedVolts {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: crafted_volts.cpp
// ──────────────────────────────────────────────────────────────────────────────

/* stripped system include */
/* stripped system include */
/* stripped system include */
/* stripped system include */

class CraftedVoltsCard : public ComputerCard {
public:
    CraftedVoltsCard() {}

    virtual void ProcessSample() override {
        update_inputs();

        // 1. Audio loop (mixes Audio In 1 and Audio In 2, then attenuverts using Main Knob)
        int32_t main_knob_signed = KnobVal(Knob::Main) - 2048; // -2048 to 2047
        int32_t mix = 0;
        if (Connected(Input::Audio1) && Connected(Input::Audio2)) {
            mix = (AudioIn1() + AudioIn2()) / 2;
        } else if (Connected(Input::Audio1)) {
            mix = AudioIn1();
        } else if (Connected(Input::Audio2)) {
            mix = AudioIn2();
        } else {
            mix = 2048; // Default unpatched behavior
        }
        
        int32_t output_value = (mix * main_knob_signed) / 2048;
        
        // Write to Audio Outputs (Audio 1 inverted, Audio 2 non-inverted)
        AudioOut1(-output_value);
        AudioOut2(output_value);
        
        // LEDs 1 & 2 reflect outputs
        float led1_val = (float)(output_value + 2048) / 4095.f;
        float led2_val = (float)(2047 - output_value) / 4095.f;
        LedBrightness(0, led1_val * led1_val * 4095.f);
        LedBrightness(1, led2_val * led2_val * 4095.f);

        // CV1 output (Knob X attenuverts CV 1 Input)
        int32_t x_knob_signed = KnobVal(Knob::X) - 2048;
        int32_t cv1_val = 2048;
        if (Connected(Input::CV1)) {
            cv1_val = CVIn1();
        }
        int32_t cv1_out_val = (cv1_val * x_knob_signed) / 2048;
        CVOut1(cv1_out_val); // Non-inverted output

        // CV2 output (Knob Y attenuverts CV 2 Input)
        int32_t y_knob_signed = KnobVal(Knob::Y) - 2048;
        int32_t cv2_val = 2048;
        if (Connected(Input::CV2)) {
            cv2_val = CVIn2();
        }
        int32_t cv2_out_val = (cv2_val * y_knob_signed) / 2048;
        CVOut2(cv2_out_val); // Non-inverted output

        // LEDs 3 & 4 reflect CV outputs
        float led3_val = (float)(cv1_out_val + 2048) / 4095.f;
        float led4_val = (float)(cv2_out_val + 2048) / 4095.f;
        LedBrightness(2, led3_val * led3_val * 4095.f);
        LedBrightness(3, led4_val * led4_val * 4095.f);

        // 3. Pulse loop
        Switch sw = SwitchVal();
        if (sw == Switch::Up || sw == Switch::Down) {
            PulseOut1(true);
            PulseOut2(false);
            LedOn(4, true);
            LedOn(5, false);
        } else {
            PulseOut1(false);
            PulseOut2(true);
            LedOn(4, false);
            LedOn(5, true);
        }
    }
};

int main() {
    #ifdef __EMSCRIPTEN__
    auto& cvc = *(new CraftedVoltsCard);
#else
    CraftedVoltsCard cvc;
#endif
    cvc.Run();
    return 0;
}


} // namespace Card_CraftedVolts

extern "C" {
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_CraftedVolts::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
