// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include <array>
#include <cmath>
#include <complex>
#include <random>
#include <functional>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <initializer_list>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

#define _Static_assert static_assert
namespace std { using ::sinf; using ::cosf; using ::tanf; using ::asinf; using ::acosf; using ::atanf; using ::atan2f; using ::sqrtf; using ::expf; using ::logf; using ::log10f; using ::powf; }

// DSO-local thread-local variables definition




namespace Card_DrumDrum {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: main.cpp
// ──────────────────────────────────────────────────────────────────────────────

/*
 * drumdrum — DFAM-Style Step Sequencer
 * =====================================
 * A program card for the Music Thing Modular Workshop Computer that emulates
 * the core sequencer and sound-generation behaviour of the Moog DFAM.
 *
 * The sequencer drives two VCOs (via CV Out 1 and Audio Out 2), outputs a
 * velocity CV for envelope/decay control, generates continuous white noise,
 * and provides step triggers and end-of-cycle triggers for external patching.
 *
 *
 * I/O Assignment:
 * ───────────────
 *   CV Out 1    — VCO 1 pitch (1V/oct, calibrated, quantised to semitones)
 *   CV Out 2    — Velocity CV (for EG decay when patched to Slope)
 *   Audio Out 1 — White noise (continuous, audio-rate xorshift32 PRNG)
 *   Audio Out 2 — VCO 2 pitch (same sequence, offset by Y knob in play mode)
 *   Pulse Out 1 — Step trigger (fires each step; also preview when paused)
 *   Pulse Out 2 — End-of-cycle trigger (fires when sequence wraps to step 1)
 *   Pulse In 1  — External clock (overrides internal tempo when patched)
 *   Pulse In 2  — Reset (returns sequence to step 1 on rising edge)
 *   CV In 1     — Decay CV mod (summed with stored velocity for current step)
 *   CV In 2     — Global pitch transpose (±24 semitones across both VCOs)
 *
 *
 * Modes (Z switch):
 * ─────────────────
 *   UP (play)   — Main=tempo, X=length(2-8), Y=VCO2 offset
 *   MIDDLE (edit)— Main=tempo, X=step pitch(pickup), Y=step velocity(pickup)
 *   DOWN (momentary) — short press: advance edit cursor
 *                       long press (≥500ms): toggle play/pause
 *
 *
 * LED Encoding (steps 1–8 shown on the 6-LED 2×3 grid):
 * ──────────────────────────────────────────────────────
 *   Step 1: top-left only
 *   Step 2: top-left + top-right
 *   Step 3: top row + middle-left
 *   Step 4: top + middle rows
 *   Step 5: top + middle + bottom-left
 *   Step 6: all 6 LEDs
 *   Step 7: all except top-left
 *   Step 8: middle + bottom rows (4 LEDs)
 */

/* stripped ComputerCard include */
#include "shared_state.h"
#include "usb_core1.h"
/* stripped hardware include */
/* stripped pico include */
/* stripped pico include */

/* stripped tusb include */
/* stripped bsp include */


// Cross-core sequencer state. Defined once here, declared extern in
// shared_state.h so Core 1 (USB host / device task) can read & write it.
volatile SharedState gState = {};


class DFAMSequencer : public ComputerCard
{

    // ──────────────────────────────────────────────
    // Internal clock timing
    // At 48kHz, ticksPerStep sets the step duration.
    // Quadratic mapping from Main knob gives a musical
    // tempo feel: CW = fast (~30 steps/s), CCW = slow (~2s/step).
    // ──────────────────────────────────────────────
    uint32_t tickCounter  = 0;
    uint32_t ticksPerStep = 48000;

    // ──────────────────────────────────────────────
    // Trigger pulse timing
    // Each trigger stays high for TRIGGER_LEN samples (~2ms),
    // long enough for any envelope generator to detect reliably.
    // ──────────────────────────────────────────────
    static constexpr int TRIGGER_LEN = 96; // ~2ms at 48kHz
    int trigCounter = 0;          // armed by the boot-mute code below
    int eocCounter  = 0;

    // Boot mute — silence audio and trigger outputs for the first
    // ~150 ms after power-on so settling DACs and immediate startup
    // state can't make a click on whatever's downstream. When the
    // mute lifts we fire the step 1 trigger so the sequencer still
    // starts audibly from boot.
    static constexpr uint32_t BOOT_MUTE_SAMPLES = 7200; // 150 ms at 48 kHz
    uint32_t bootMute = BOOT_MUTE_SAMPLES;

    // ──────────────────────────────────────────────
    // Edit mode pickup state (knob catch-up flags)
    // editStep itself lives in gState so Core 1 can read it for Grid /
    // browser display and write it when the user selects a step there.
    // ──────────────────────────────────────────────
    bool xPickedUp   = false;
    bool yPickedUp   = false;

    // Track the pitch/velocity values we last "owned" — anything in
    // gState that doesn't match these came from the Grid or browser
    // editor and means we must drop pickup so the knob no longer
    // overwrites the externally-set value. lastEditStep does the same
    // job for editStep changes from the Grid.
    uint8_t lastSeenPitch[8]    = {0,0,0,0,0,0,0,0};
    uint8_t lastSeenVelocity[8] = {0,0,0,0,0,0,0,0};
    int8_t  lastEditStep        = -1;

    // After a pickup reset (mode change, edit-step change, external
    // edit), we remember the knob's raw ADC position and require the
    // knob to move at least KNOB_MOVE_THRESH from it before pickup is
    // allowed to recapture. Without this, parking the knob anywhere
    // close to the value the Grid just set causes pickup to catch on
    // the next sample and overwrite the Grid's value with whatever
    // the knob happens to be reading.
    int32_t xKnobAtReset = -1;
    int32_t yKnobAtReset = -1;
    static constexpr int32_t KNOB_MOVE_THRESH = 60; // out of 4096 — well above ADC noise

    // Pickup threshold: the knob must come within this many units of the
    // stored value before it "catches" and begins tracking. This prevents
    // value jumps when switching modes or between steps (MicroFreak-style).
    static constexpr int PICKUP_THRESH = 3;
    static constexpr int PICKUP_THRESH_LENGTH = 1; // tighter for the 2–8 range

    // ──────────────────────────────────────────────
    // Play mode pickup state
    // Same pickup/catchup behaviour applies when switching back to play mode,
    // so the X (length) and Y (VCO2 offset) knobs don't jump to a new value
    // if they were left in a different position during edit mode.
    // ──────────────────────────────────────────────
    bool lengthPickedUp = false;
    bool offsetPickedUp = false;

    // Same external-edit guard as the edit-mode pickup (see lastSeen*
    // below): when seqLength changes from a Grid tap or browser edit
    // we drop lengthPickedUp and require the knob to move before
    // recapturing, so the play-mode length knob can't silently
    // overwrite a Grid-set length when it happens to be parked nearby.
    uint8_t lastSeenSeqLength = 8;
    int32_t lengthKnobAtReset = -1;

    // ──────────────────────────────────────────────
    // VCO 2 pitch offset (semitones, set by Y knob in play mode)
    // Stored as a member so it persists when switching to edit mode.
    // ──────────────────────────────────────────────
    int32_t vco2Offset = 0;

    // ──────────────────────────────────────────────
    // Switch DOWN (momentary) press detection
    // The physical switch is (ON)-OFF-ON: UP latches, MIDDLE is centre,
    // DOWN is momentary and springs back to MIDDLE.
    // We time how long DOWN is held to distinguish short/long presses.
    // ──────────────────────────────────────────────
    static constexpr uint32_t LONG_PRESS_SAMPLES = 24000; // 500ms at 48kHz
    bool     switchDownActive = false;
    uint32_t switchDownCount  = 0;
    bool     longPressHandled = false;

    // ──────────────────────────────────────────────
    // Previous switch position (for detecting mode transitions)
    // ──────────────────────────────────────────────
    Switch prevMode = Switch::Up;

    // ──────────────────────────────────────────────
    // White noise PRNG state (xorshift32)
    // ──────────────────────────────────────────────
    uint32_t rngState = 0xDEADBEEF;

    // ──────────────────────────────────────────────
    // LED encoding table
    // Each entry is a 6-bit mask: bit N = LED N on.
    // Index 0 = step 1, index 7 = step 8.
    //
    // LED layout:
    //   | 0  1 |  (top)
    //   | 2  3 |  (middle)
    //   | 4  5 |  (bottom)
    // ──────────────────────────────────────────────
    static constexpr uint8_t ledPattern[8] = {
        0b000001, // step 1: top-left
        0b000011, // step 2: top-left + top-right
        0b000111, // step 3: + middle-left
        0b001111, // step 4: + middle-right
        0b011111, // step 5: + bottom-left
        0b111111, // step 6: all ON
        0b111110, // step 7: all except top-left
        0b111100, // step 8: middle + bottom rows
    };

public:
    // Advance the PRNG by one step and return the new state.
    uint32_t __not_in_flash_func(xorshift)()
    {
        rngState ^= rngState << 13;
        rngState ^= rngState >> 17;
        rngState ^= rngState << 5;
        return rngState;
    }

    // Expose the protected USBPowerState() to main() so we can pick a
    // USB role (host vs device) before launching Core 1.
    USBPowerState_t ReadUSBPowerState() { return USBPowerState(); }

    DFAMSequencer()
    {
        // Settling delay before any USB / I/O activity — matches MLRws,
        // which we know works on the same hardware. Without this the
        // USB controller doesn't always come up cleanly after reset.
        sleep_ms(150);

        // Seed the PRNG from the hardware microsecond timer so that each
        // reset produces a different sequence. The exact timer value at
        // this point depends on boot timing and is effectively random.
        rngState = time_us_32();
        if (rngState == 0) rngState = 0xDEADBEEF; // xorshift must never be zero

        // Randomise step values: pitch within a musically useful 3-octave
        // range (C2–B4, MIDI 36–71), velocity biased toward the upper half
        // so steps are audible by default.
        for (int i = 0; i < 8; i++) {
            gState.pitch[i]    = 36 + (xorshift() % 36);  // C2–B4
            gState.velocity[i] = 100 + (xorshift() % 156); // 100–255
            lastSeenPitch[i]    = gState.pitch[i];
            lastSeenVelocity[i] = gState.velocity[i];
        }
        gState.seqLength   = 8;
        gState.editStep    = 0;
        gState.currentStep = 0;
        gState.playing     = 1;
        gState.tickEpoch   = 0;
        lastSeenSeqLength  = gState.seqLength;
    }

    // ProcessSample runs once per audio sample at 48kHz in interrupt context.
    // It must complete within ~20μs. All arithmetic is integer to stay fast.
    virtual void ProcessSample() override
    {
        // ════════════════════════════════════════════
        // BOOT MUTE — hold audio and pulse outputs at zero for the
        // first 150 ms so DAC settling and any startup state changes
        // can't make a click. When the mute lifts we arm the step 1
        // trigger so the sequencer still kicks off audibly at boot.
        // ════════════════════════════════════════════
        if (bootMute > 0) {
            bootMute--;
            AudioOut1(0);
            AudioOut2(0);
            PulseOut1(false);
            PulseOut2(false);
            if (bootMute == 0) {
                // Step 1 fires audibly when the mute lifts. End-of-cycle
                // is a sequence-wrap event so we deliberately don't arm
                // it here — patches on Pulse Out 2 shouldn't see a pulse
                // at every power-up.
                trigCounter = TRIGGER_LEN;
            }
            return;
        }

        // ════════════════════════════════════════════
        // WHITE NOISE — always running on Audio Out 1,
        // regardless of mode or play/pause state.
        // xorshift32 produces a full-spectrum noise signal.
        // ════════════════════════════════════════════
        // Extract 12 bits and centre around zero for the signed audio range
        AudioOut1(static_cast<int16_t>((xorshift() >> 20) & 0xFFF) - 2048);


        // ════════════════════════════════════════════
        // READ SWITCH — determines current mode
        // ════════════════════════════════════════════
        Switch sw = SwitchVal();

        // When entering edit mode, reset edit-knob pickup so X/Y don't
        // immediately overwrite the step's stored values.
        if (sw == Switch::Middle && prevMode != Switch::Middle) {
            xPickedUp = false;
            yPickedUp = false;
        }

        // When entering play mode, reset play-knob pickup so X (length)
        // and Y (VCO2 offset) don't jump from their edit-mode positions.
        // Also seed the knob-at-reset position so the first samples
        // after entering UP can't catch without an actual movement.
        if (sw == Switch::Up && prevMode != Switch::Up) {
            lengthPickedUp = false;
            offsetPickedUp = false;
            lengthKnobAtReset = KnobVal(Knob::X);
        }


        // ════════════════════════════════════════════
        // SWITCH DOWN — momentary press handling
        // Short press (<500ms): advance edit cursor to next step.
        // Long press (≥500ms): toggle play/pause.
        // ════════════════════════════════════════════
        if (sw == Switch::Down) {
            if (!switchDownActive) {
                switchDownActive = true;
                switchDownCount  = 0;
                longPressHandled = false;
            }
            switchDownCount++;

            if (switchDownCount >= LONG_PRESS_SAMPLES && !longPressHandled) {
                // Long press detected: toggle play/pause
                longPressHandled = true;
                if (gState.playing) {
                    // Pause the sequencer — step position is preserved
                    gState.playing = 0;
                } else {
                    // Resume playback from the step after the last one played.
                    // This avoids re-triggering a step the user already heard.
                    gState.playing = 1;
                    gState.currentStep = (gState.currentStep + 1) % gState.seqLength;
                    gState.tickEpoch++;
                    tickCounter = 0;
                    trigCounter = TRIGGER_LEN;
                    if (gState.currentStep == 0) {
                        eocCounter = TRIGGER_LEN;
                    }
                }
            }
        } else if (switchDownActive) {
            // Switch just released back to MIDDLE
            switchDownActive = false;

            if (!longPressHandled) {
                // Short press: advance edit cursor, wrapping at sequence length
                gState.editStep = (gState.editStep + 1) % gState.seqLength;
                xPickedUp = false;
                yPickedUp = false;

                // When paused, fire a preview trigger so the user can hear
                // the step they just navigated to. This does NOT fire during
                // normal playback to avoid double-triggering.
                if (!gState.playing) {
                    trigCounter = TRIGGER_LEN;
                }
            }
        }


        // ════════════════════════════════════════════
        // MODE-DEPENDENT KNOB HANDLING
        // ════════════════════════════════════════════
        if (sw == Switch::Up) {
            // --- Play mode ---
            // Both knobs use pickup behaviour so switching from edit mode
            // doesn't cause the length or VCO2 offset to jump.
            int32_t xRaw = KnobVal(Knob::X);

            // If seqLength changed externally (Grid tap, browser edit),
            // drop pickup and require the knob to actually move before
            // recapturing. Otherwise tapping a length on the Grid that's
            // close to the knob's parked position gets immediately
            // overwritten by the knob's value.
            if (gState.seqLength != lastSeenSeqLength) {
                lengthPickedUp = false;
                lengthKnobAtReset = xRaw;
            }
            lastSeenSeqLength = gState.seqLength;

            // X knob → sequence length (1–8 steps). Length 1 = a single
            // hammered step (useful for one-shot voices); EOC fires on
            // every tick in that case.
            int32_t knobLength = 1 + ((xRaw * 8) >> 12);
            if (knobLength > 8) knobLength = 8;
            if (!lengthPickedUp) {
                int32_t moved = xRaw - lengthKnobAtReset;
                if (moved < 0) moved = -moved;
                if (moved >= KNOB_MOVE_THRESH) {
                    int32_t d = knobLength - static_cast<int32_t>(gState.seqLength);
                    if (d < 0) d = -d;
                    if (d <= PICKUP_THRESH_LENGTH) lengthPickedUp = true;
                }
            }
            if (lengthPickedUp) {
                gState.seqLength = static_cast<uint8_t>(knobLength);
            }

            // Y knob → VCO 2 pitch offset relative to VCO 1 (±24 semitones)
            // Knob at noon ≈ unison; CW = higher, CCW = lower
            int32_t knobOffset = ((KnobVal(Knob::Y) * 49) >> 12) - 24;
            if (!offsetPickedUp) {
                int32_t d = knobOffset - vco2Offset;
                if (d < 0) d = -d;
                if (d <= PICKUP_THRESH) offsetPickedUp = true;
            }
            if (offsetPickedUp) {
                vco2Offset = knobOffset;
            }

        } else if (sw == Switch::Middle) {
            // --- Edit mode ---
            // Knobs use "pickup" behaviour: the knob must pass through the
            // stored value before it begins tracking. This prevents jarring
            // value jumps when the knob position doesn't match the step's
            // stored value.

            uint8_t es = gState.editStep;
            int32_t xRaw = KnobVal(Knob::X);
            int32_t yRaw = KnobVal(Knob::Y);

            // If the edit step changed (user tapped a new step on the
            // Grid, or pressed switch DOWN), drop pickup so the knob
            // doesn't immediately splat the new step's value. Same
            // story if pitch/velocity at this step changed externally
            // (Grid tap, browser edit) — give the user a fresh catch
            // before we start tracking again. Stash the knob position
            // so we can require an actual user movement before pickup
            // is allowed to recapture.
            if (es != lastEditStep ||
                gState.pitch[es]    != lastSeenPitch[es] ||
                gState.velocity[es] != lastSeenVelocity[es]) {
                xPickedUp = false;
                yPickedUp = false;
                xKnobAtReset = xRaw;
                yKnobAtReset = yRaw;
            }
            lastEditStep = (int8_t)es;

            // X knob → pitch for the current edit step. Spans the full
            // 0..127 MIDI range; the Grid quantizes to PITCH_GRID_STEP
            // semitones for its picker but we still want fine pot
            // control over the entire range.
            int32_t knobPitch = (xRaw * 127) >> 12;
            if (!xPickedUp) {
                int32_t moved = xRaw - xKnobAtReset;
                if (moved < 0) moved = -moved;
                if (moved >= KNOB_MOVE_THRESH) {
                    int32_t d = knobPitch - static_cast<int32_t>(gState.pitch[es]);
                    if (d < 0) d = -d;
                    if (d <= PICKUP_THRESH) xPickedUp = true;
                }
            }
            if (xPickedUp) {
                gState.pitch[es] = static_cast<uint8_t>(knobPitch);
            }

            // Y knob → velocity for the current edit step (0–255)
            int32_t knobVel = (yRaw * 255) >> 12;
            if (!yPickedUp) {
                int32_t moved = yRaw - yKnobAtReset;
                if (moved < 0) moved = -moved;
                if (moved >= KNOB_MOVE_THRESH) {
                    int32_t d = knobVel - static_cast<int32_t>(gState.velocity[es]);
                    if (d < 0) d = -d;
                    if (d <= PICKUP_THRESH) yPickedUp = true;
                }
            }
            if (yPickedUp) {
                gState.velocity[es] = static_cast<uint8_t>(knobVel);
            }

            // Refresh the "last seen" snapshot so we don't false-trigger
            // a pickup reset next sample. Catches both panel writes and
            // any external write we just observed.
            lastSeenPitch[es]    = gState.pitch[es];
            lastSeenVelocity[es] = gState.velocity[es];
        }


        // ════════════════════════════════════════════
        // RESET INPUT
        // Rising edge on Pulse In 2 returns the sequence to step 1.
        // ════════════════════════════════════════════
        if (PulseIn2RisingEdge()) {
            gState.currentStep = 0;
            gState.tickEpoch++;
            tickCounter = 0;
            trigCounter = TRIGGER_LEN;
        }


        // ════════════════════════════════════════════
        // SEQUENCER ADVANCE
        // External clock (Pulse In 1) overrides the internal tempo when
        // patched. The internal clock keeps running in the background so
        // that removing the patch cable resumes at the current tempo.
        // ════════════════════════════════════════════
        bool useExtClock = Connected(Input::Pulse1);

        if (gState.playing) {
            bool advance = false;

            if (useExtClock) {
                // External clock: each rising edge advances one step
                if (PulseIn1RisingEdge()) {
                    advance = true;
                }
            } else {
                // Internal clock: Main knob sets tempo with a quadratic curve
                // for a musical feel. CW = fast (~30 steps/s), CCW = slow (~2s).
                int32_t knob = KnobVal(Knob::Main);
                int32_t inv  = 4095 - knob;
                ticksPerStep = 1600 + ((inv * inv * 6) >> 10);

                tickCounter++;
                if (tickCounter >= ticksPerStep) {
                    tickCounter = 0;
                    advance = true;
                }
            }

            if (advance) {
                gState.currentStep = (gState.currentStep + 1) % gState.seqLength;
                gState.tickEpoch++;
                trigCounter = TRIGGER_LEN;
                // Fire end-of-cycle when wrapping from last step back to first
                if (gState.currentStep == 0) {
                    eocCounter = TRIGGER_LEN;
                }
            }
        } else {
            // While paused, keep updating the tempo calculation so that
            // unplugging an external clock cable resumes smoothly.
            if (!useExtClock) {
                int32_t knob = KnobVal(Knob::Main);
                int32_t inv  = 4095 - knob;
                ticksPerStep = 1600 + ((inv * inv * 6) >> 10);
            }
        }

        // Clamp positions if sequence length was shortened. Bump
        // tickEpoch on a currentStep clamp so Core 1 (browser editor)
        // sees the position change immediately — otherwise it would
        // keep highlighting a stale step until the next natural tick,
        // and indefinitely if playback is paused.
        if (gState.currentStep >= gState.seqLength) {
            gState.currentStep = 0;
            gState.tickEpoch++;
        }
        if (gState.editStep    >= gState.seqLength) gState.editStep    = 0;


        // ════════════════════════════════════════════
        // CV AND AUDIO OUTPUTS
        // ════════════════════════════════════════════

        // When paused in edit mode, output the edit step's values so the
        // user can hear what they are editing via the preview trigger.
        // Otherwise, output the current playback step.
        uint8_t outputStep = gState.currentStep;
        if (!gState.playing && sw == Switch::Middle) {
            outputStep = gState.editStep;
        }
        uint8_t outPitch    = gState.pitch[outputStep];
        uint8_t outVelocity = gState.velocity[outputStep];

        // CV In 2 → global pitch transpose (±24 semitones)
        // CVIn2 returns -2048..+2047; scale to ±24 with integer math
        int32_t transpose = (CVIn2() * 3) >> 8;

        // --- CV Out 1: VCO 1 pitch (calibrated 1V/oct) ---
        // Uses the EEPROM-calibrated CVOutMIDINote for accurate tracking
        int32_t pitch1 = static_cast<int32_t>(outPitch) + transpose;
        if (pitch1 < 0)   pitch1 = 0;
        if (pitch1 > 127) pitch1 = 127;
        CVOut1MIDINote(static_cast<uint8_t>(pitch1));

        // --- CV Out 2: Velocity + Decay CV mod ---
        // Velocity (0–255) is scaled to fill the positive CV range.
        // CV In 1 is summed in to allow external modulation of the
        // decay/envelope amount.
        int32_t velCV = static_cast<int32_t>(outVelocity) * 8 + CVIn1();
        if (velCV > 2047)  velCV = 2047;
        if (velCV < -2048) velCV = -2048;
        CVOut2(static_cast<int16_t>(velCV));

        // --- Audio Out 2: VCO 2 pitch CV ---
        // Approximates 1V/oct on the 12-bit audio DAC.
        // Audio DAC range -2048..+2047 ≈ ±6V, so 1 semitone ≈ 28.4 units.
        // Formula: (midiNote - 60) * 1820 >> 6 gives ~28.44 units/semitone.
        // This output is uncalibrated — tune VCO 2 by ear or with a tuner.
        int32_t pitch2 = static_cast<int32_t>(outPitch) + transpose + vco2Offset;
        int32_t audioPitch = ((pitch2 - 60) * 1820) >> 6;
        if (audioPitch > 2047)  audioPitch = 2047;
        if (audioPitch < -2048) audioPitch = -2048;
        AudioOut2(static_cast<int16_t>(audioPitch));


        // ════════════════════════════════════════════
        // TRIGGER OUTPUTS
        // Each trigger pulse counts down from TRIGGER_LEN (~2ms).
        // ════════════════════════════════════════════
        PulseOut1(trigCounter > 0);
        if (trigCounter > 0) trigCounter--;

        PulseOut2(eocCounter > 0);
        if (eocCounter > 0) eocCounter--;


        // ════════════════════════════════════════════
        // LED DISPLAY
        // In edit mode: shows the edit cursor position.
        // In play mode: shows the current playback step.
        // Both use the same step-encoding scheme (see table above).
        // ════════════════════════════════════════════
        uint8_t displayStep = (sw == Switch::Middle) ? gState.editStep : gState.currentStep;
        uint8_t pattern = ledPattern[displayStep];
        for (int i = 0; i < 6; i++) {
            LedOn(i, (pattern >> i) & 1);
        }

        prevMode = sw;
    }
};


int main()
{
    // 144MHz reduces ADC tonal artifacts (recommended by Workshop Computer
    // AI Directive). Must be set before the ComputerCard constructor, which
    // configures peripheral clocks based on the current system frequency.
    set_sys_clock_khz(144000, true);

    #ifdef __EMSCRIPTEN__
    auto& seq = *(new DFAMSequencer);
#else
    DFAMSequencer seq;
#endif
    seq.EnableNormalisationProbe();

    // Decide USB role from the USB-C CC pins (Rev 1.1+). UFP = we're
    // plugged into a computer (browser editor). Anything else (DFP or
    // unsupported) we treat as host so a Grid plugged into the front
    // jack works on older hardware too. This matches MLRws's check.
    gUsbHostMode = (seq.ReadUSBPowerState() != ComputerCard::UFP) ? 1 : 0;

    // For device mode we initialise TinyUSB synchronously here on Core 0
    // so the host's enumeration request is answered as quickly as
    // possible. Core 1 just calls tud_task() in its loop. (Host mode
    // does its own board_init/tusb_init from Core 1 — see usb_core1.cpp.)
    if (!gUsbHostMode) {
        board_init();
        tud_init(0);
    }

    // Core 1 owns the USB task pump (host or device, decided above).
    multicore_launch_core1(core1_entry);

    seq.Run();

    return 0;
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: usb_core1.cpp
// ──────────────────────────────────────────────────────────────────────────────

// Core 1 entry — USB host or device task loop.
//
// The role is decided synchronously in main() by reading USBPowerState()
// on the USB-C CC pins, and stashed in gUsbHostMode before Core 1 is
// launched. Initialisation is split to match MLRws (a known-working
// reference on this hardware):
//
//   Device mode: main() calls board_init() + tud_init() on Core 0 *before*
//                launching Core 1, so the host sees the device immediately.
//                Core 1 here just runs the task pump.
//
//   Host mode:   Core 1 calls board_init() + tusb_init() itself. tusb_init
//                (not tuh_init) is required because our tusb_config has
//                CFG_TUSB_RHPORT0_MODE = HOST | DEVICE — going through
//                tusb_init configures the USB hardware for the chosen role.

#include "usb_core1.h"
#include "shared_state.h"
#include "midi_sysex.h"
#include "monome_mext.h"
#include "grid_ui.h"
#include "midi_host.h"

/* stripped tusb include */
/* stripped bsp include */
/* stripped pico include */

volatile uint8_t gUsbHostMode = 0;

static void run_host_loop(void)
{
    board_init();
    // Both host paths coexist: a Grid plugged in fires CDC mount cbs
    // into mext, an 8mu (or any class-compliant USB MIDI device) fires
    // our app-registered MIDI driver. Whichever shows up wins; the
    // other path stays idle. mext_task() drives tuh_task(), which is
    // what dispatches the MIDI driver's xfer callbacks.
    mext_init(MEXT_TRANSPORT_HOST, 0);
    midi_host_init();
    tusb_init();
    grid_ui_init();
    #ifdef __EMSCRIPTEN__
    g_wasm_core1_tick = []() {
        
        mext_task();
        grid_ui_process_input();
        grid_ui_render();
    
    };
#else
    while (true) {
        
        mext_task();
        grid_ui_process_input();
        grid_ui_render();
    
    }
#endif
}

static void run_device_loop(void)
{
    // board_init + tud_init were called from Core 0 in main(), so Core 1
    // just pumps the task here.
    #ifdef __EMSCRIPTEN__
    g_wasm_core1_tick = []() {
        
        tud_task();
        midi_device_task();
    
    };
#else
    while (true) {
        
        tud_task();
        midi_device_task();
    
    }
#endif
}

void tuh_cdc_mount_cb(uint8_t idx);
void tuh_cdc_umount_cb(uint8_t idx);

static void drumdrum_on_grid_connected(bool connected) {
    if (connected) {
        tuh_cdc_mount_cb(0);
    } else {
        tuh_cdc_umount_cb(0);
    }
}

extern "C" void core1_entry(void)
{
    if (t_instance) {
        t_instance->on_grid_connected_fn = drumdrum_on_grid_connected;
        if (t_instance->grid_connected_flag) {
            tuh_cdc_mount_cb(0);
        }
    }
    board_init();
    mext_init(MEXT_TRANSPORT_HOST, 0);
    midi_host_init();
    tusb_init();
    grid_ui_init();
    #ifdef __EMSCRIPTEN__
    g_wasm_core1_tick = []() {
        
        tud_task();
        midi_device_task();
        mext_task();
        grid_ui_process_input();
        grid_ui_render();
    
    };
#else
    while (true) {
        
        tud_task();
        midi_device_task();
        mext_task();
        grid_ui_process_input();
        grid_ui_render();
    
    }
#endif
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: midi_sysex.cpp
// ──────────────────────────────────────────────────────────────────────────────

// SysEx parser/encoder for the WebMIDI editor.
// Runs entirely on Core 1; reads/writes gState directly (single-byte
// fields are atomic on the M0+).

#include "midi_sysex.h"
#include "shared_state.h"

/* stripped tusb include */
/* stripped system include */

// ── Inbound SysEx accumulator ─────────────────────────────────
// SysEx bodies for this card are tiny (max ~5 bytes payload), so a
// 32-byte buffer is plenty. If we ever exceed it the parser drops the
// message and resyncs at the next 0xF0.
static uint8_t  rx_buf[32];
static uint16_t rx_len     = 0;
static bool     rx_in_msg  = false;

// ── Outbound state mirror ─────────────────────────────────────
// We send param updates whenever Core 1's snapshot diverges from gState.
// This catches changes from any source (panel knobs, future Grid mode,
// our own SysEx writes) with a single polling loop.
struct Mirror {
    uint8_t  pitch[8];
    uint8_t  velocity[8];
    uint8_t  seqLength;
    uint8_t  playing;
    uint8_t  currentStep;
    uint32_t tickEpoch;
    bool     dumped;            // initial dump sent for current connection
    bool     was_mounted;
};
static Mirror mirror = {};

// ── Helpers ────────────────────────────────────────────────────
static void send_sysex(const uint8_t *payload, uint16_t len)
{
    if (!tud_midi_mounted()) return;

    uint8_t buf[40];
    if ((size_t)(len + 3) > sizeof(buf)) return;  // belt-and-braces

    buf[0] = 0xF0;
    buf[1] = DRUMDRUM_SYSEX_MFR;
    memcpy(&buf[2], payload, len);
    buf[2 + len] = 0xF7;

    tud_midi_stream_write(0, buf, len + 3);
}

static void send_full_dump(void)
{
    // Layout: cmd, seqLength, playing, currentStep, pitch[0..7],
    //         v_hi[0], v_lo[0], v_hi[1], v_lo[1], ... v_hi[7], v_lo[7]
    // Total payload bytes (after F0 7D): 1 + 3 + 8 + 16 = 28.
    uint8_t p[28];
    p[0] = DRUMDRUM_SYSEX_FULL_DUMP;
    p[1] = gState.seqLength;
    p[2] = gState.playing;
    p[3] = gState.currentStep;
    for (int i = 0; i < 8; i++) p[4 + i] = gState.pitch[i] & 0x7F;
    for (int i = 0; i < 8; i++) {
        uint8_t v = gState.velocity[i];
        p[12 + 2*i + 0] = (v >> 4) & 0x0F;
        p[12 + 2*i + 1] = v & 0x0F;
    }
    send_sysex(p, sizeof(p));
}

static void send_param_pitch(uint8_t step)
{
    uint8_t p[4] = { DRUMDRUM_SYSEX_PARAM_UPDATE,
                     DRUMDRUM_SYSEX_SET_PITCH,
                     step,
                     (uint8_t)(gState.pitch[step] & 0x7F) };
    send_sysex(p, sizeof(p));
}

static void send_param_velocity(uint8_t step)
{
    uint8_t v = gState.velocity[step];
    uint8_t p[5] = { DRUMDRUM_SYSEX_PARAM_UPDATE,
                     DRUMDRUM_SYSEX_SET_VELOCITY,
                     step,
                     (uint8_t)((v >> 4) & 0x0F),
                     (uint8_t)(v & 0x0F) };
    send_sysex(p, sizeof(p));
}

static void send_param_length(void)
{
    uint8_t p[3] = { DRUMDRUM_SYSEX_PARAM_UPDATE,
                     DRUMDRUM_SYSEX_SET_LENGTH,
                     gState.seqLength };
    send_sysex(p, sizeof(p));
}

static void send_param_playing(void)
{
    uint8_t p[3] = { DRUMDRUM_SYSEX_PARAM_UPDATE,
                     DRUMDRUM_SYSEX_SET_PLAYING,
                     (uint8_t)(gState.playing ? 1 : 0) };
    send_sysex(p, sizeof(p));
}

static void send_tick(uint8_t step)
{
    uint8_t p[2] = { DRUMDRUM_SYSEX_TICK, step };
    send_sysex(p, sizeof(p));
}

// ── Inbound dispatch ──────────────────────────────────────────
static void apply_sysex(const uint8_t *body, uint16_t len)
{
    // body[] is everything between F0 and F7, exclusive.
    // body[0] = manufacturer, body[1] = command, then payload.
    if (len < 2) return;
    if (body[0] != DRUMDRUM_SYSEX_MFR) return;

    uint8_t cmd = body[1];
    switch (cmd) {
    case DRUMDRUM_SYSEX_SET_PITCH:
        if (len >= 4) {
            uint8_t step  = body[2] & 0x07;
            uint8_t pitch = body[3] & 0x7F;
            gState.pitch[step] = pitch;
        }
        break;

    case DRUMDRUM_SYSEX_SET_VELOCITY:
        if (len >= 5) {
            uint8_t step = body[2] & 0x07;
            uint8_t hi   = body[3] & 0x0F;
            uint8_t lo   = body[4] & 0x0F;
            gState.velocity[step] = (uint8_t)((hi << 4) | lo);
        }
        break;

    case DRUMDRUM_SYSEX_SET_LENGTH:
        if (len >= 3) {
            uint8_t v = body[2];
            if (v < 1) v = 1;
            if (v > 8) v = 8;
            gState.seqLength = v;
        }
        break;

    case DRUMDRUM_SYSEX_SET_PLAYING:
        if (len >= 3) {
            gState.playing = body[2] ? 1 : 0;
        }
        break;

    case DRUMDRUM_SYSEX_REQUEST_DUMP:
        send_full_dump();
        // Bring our mirror back in sync so we don't immediately re-send
        // every parameter as a "change".
        memcpy(mirror.pitch,    (const void*)gState.pitch,    8);
        memcpy(mirror.velocity, (const void*)gState.velocity, 8);
        mirror.seqLength   = gState.seqLength;
        mirror.playing     = gState.playing;
        mirror.currentStep = gState.currentStep;
        mirror.tickEpoch   = gState.tickEpoch;
        break;

    default:
        break;
    }
}

static void feed_byte(uint8_t b)
{
    if (b == 0xF0) {
        rx_in_msg = true;
        rx_len    = 0;
    } else if (b == 0xF7) {
        if (rx_in_msg) apply_sysex(rx_buf, rx_len);
        rx_in_msg = false;
        rx_len    = 0;
    } else if (rx_in_msg) {
        if (rx_len < sizeof(rx_buf)) {
            rx_buf[rx_len++] = b;
        } else {
            // Overflow — drop the rest of this message
            rx_in_msg = false;
            rx_len    = 0;
        }
    }
}

// ── Public entry ──────────────────────────────────────────────
void midi_device_task(void)
{
    // 1. Detect host (re)connection — re-send the full dump so the
    //    browser can populate its UI from a known starting point.
    bool mounted_now = tud_midi_mounted();
    if (mounted_now && !mirror.was_mounted) {
        mirror.dumped = false;
    }
    mirror.was_mounted = mounted_now;

    if (mounted_now && !mirror.dumped) {
        send_full_dump();
        memcpy(mirror.pitch,    (const void*)gState.pitch,    8);
        memcpy(mirror.velocity, (const void*)gState.velocity, 8);
        mirror.seqLength   = gState.seqLength;
        mirror.playing     = gState.playing;
        mirror.currentStep = gState.currentStep;
        mirror.tickEpoch   = gState.tickEpoch;
        mirror.dumped      = true;
    }

    // 2. Drain inbound MIDI bytes, byte-stream API.
    uint8_t in_buf[64];
    while (tud_midi_available()) {
        uint32_t n = tud_midi_stream_read(in_buf, sizeof(in_buf));
        for (uint32_t i = 0; i < n; i++) feed_byte(in_buf[i]);
    }

    if (!mounted_now) return;

    // 3. Tick notification — fires whenever core 0 advances a step.
    if (gState.tickEpoch != mirror.tickEpoch) {
        mirror.tickEpoch   = gState.tickEpoch;
        mirror.currentStep = gState.currentStep;
        send_tick(mirror.currentStep);
    }

    // 4. Param diff — pushes panel-knob and switch changes to the browser.
    for (int i = 0; i < 8; i++) {
        uint8_t v = gState.pitch[i];
        if (v != mirror.pitch[i]) {
            mirror.pitch[i] = v;
            send_param_pitch((uint8_t)i);
        }
    }
    for (int i = 0; i < 8; i++) {
        uint8_t v = gState.velocity[i];
        if (v != mirror.velocity[i]) {
            mirror.velocity[i] = v;
            send_param_velocity((uint8_t)i);
        }
    }
    if (gState.seqLength != mirror.seqLength) {
        mirror.seqLength = gState.seqLength;
        send_param_length();
    }
    if (gState.playing != mirror.playing) {
        mirror.playing = gState.playing;
        send_param_playing();
    }
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: monome_mext.c
// ──────────────────────────────────────────────────────────────────────────────

/**
 * monome_mext.c — Lightweight mext protocol for monome grid/arc on RP2040.
 *
 * Vendored verbatim from dessertplanet/Workshop_Computer (MLRws release).
 * Direct byte-level mext TX/RX, modelled on dessertplanet/viii and
 * monome/ansible.  All writes are padded to 64 bytes with 0xFF for
 * USB bulk packet alignment — essential for FTDI compatibility.
 *
 * Transport: TinyUSB CDC host (tuh_cdc_write / tuh_cdc_read).
 */

#include "monome_mext.h"

/* stripped system include */
/* stripped tusb include */
/* stripped pico include */
/* stripped pico include */

/* ------------------------------------------------------------------ */
/* Global state                                                       */
/* ------------------------------------------------------------------ */
mext_state_t g_mext;

/* ------------------------------------------------------------------ */
/* Internal helpers                                                   */
/* ------------------------------------------------------------------ */

/* drumdrum customisation: we never use CDC as a USB device (browser
 * mode is MIDI-only), so the device-CDC branches are compiled out
 * unless the descriptor table actually exposes a CDC interface. */
#if CFG_TUD_CDC > 0
#  define MEXT_HAVE_DEVICE_CDC 1
#else
#  define MEXT_HAVE_DEVICE_CDC 0
#endif

/** Send raw bytes padded to 64 with 0xFF — for LED commands. */
static void mext_send_raw(const uint8_t *data, uint32_t len)
{
	if (!g_mext.connected || g_mext.cdc_idx < 0)
		return;

	uint8_t padded[64];
	if (len < 64) {
		memcpy(padded, data, len);
		memset(padded + len, 0xFF, 64 - len);
		if (g_mext.transport == MEXT_TRANSPORT_DEVICE) {
#if MEXT_HAVE_DEVICE_CDC
			if (tud_cdc_n_write_available(g_mext.device_cdc_itf) < 64)
				return;
			tud_cdc_n_write(g_mext.device_cdc_itf, padded, 64);
			tud_cdc_n_write_flush(g_mext.device_cdc_itf);
#endif
		} else {
			tuh_cdc_write((uint8_t)g_mext.cdc_idx, padded, 64);
			tuh_cdc_write_flush((uint8_t)g_mext.cdc_idx);
		}
	} else {
		if (g_mext.transport == MEXT_TRANSPORT_DEVICE) {
#if MEXT_HAVE_DEVICE_CDC
			if (tud_cdc_n_write_available(g_mext.device_cdc_itf) < len)
				return;
			tud_cdc_n_write(g_mext.device_cdc_itf, data, len);
			tud_cdc_n_write_flush(g_mext.device_cdc_itf);
#endif
		} else {
			tuh_cdc_write((uint8_t)g_mext.cdc_idx, data, len);
			tuh_cdc_write_flush((uint8_t)g_mext.cdc_idx);
		}
	}
}

/** Send bytes without padding — for discovery/system queries. */
static void mext_send(const uint8_t *data, uint32_t len)
{
	if (!g_mext.connected || g_mext.cdc_idx < 0)
		return;

	if (g_mext.transport == MEXT_TRANSPORT_DEVICE) {
#if MEXT_HAVE_DEVICE_CDC
		if (tud_cdc_n_write_available(g_mext.device_cdc_itf) < len)
			return;
		tud_cdc_n_write(g_mext.device_cdc_itf, data, len);
		tud_cdc_n_write_flush(g_mext.device_cdc_itf);
#endif
	} else {
		tuh_cdc_write((uint8_t)g_mext.cdc_idx, data, len);
		tuh_cdc_write_flush((uint8_t)g_mext.cdc_idx);
	}
}

static void event_push(const mext_event_t *e)
{
	uint8_t next = (g_mext.events.w + 1) % MEXT_EVENT_QUEUE_SIZE;
	if (next == g_mext.events.r)
		return; /* queue full, drop event */
	g_mext.events.buf[g_mext.events.w] = *e;
	g_mext.events.w = next;
}

static inline uint8_t quad_idx(uint8_t x, uint8_t y)
{
	return ((y >= 8) << 1) | (x >= 8);
}

/* ------------------------------------------------------------------ */
/* mext RX parser                                                     */
/* ------------------------------------------------------------------ */

static uint8_t mext_response_len(uint8_t header)
{
	uint8_t addr = header >> 4;
	uint8_t cmd  = header & 0x0F;

	switch (addr) {
	case 0x0: /* system */
		switch (cmd) {
		case 0x0: return 3;
		case 0x1: return 33;
		case 0x2: return 4;
		case 0x3: return 3;
		case 0x4: return 3;
		case 0xF: return 9;
		default:  return 1;
		}

	case 0x2: /* key grid */
		return (cmd <= 0x1) ? 3 : 1;

	case 0x5: /* encoder */
		if (cmd == 0x0) return 3;
		if (cmd == 0x1 || cmd == 0x2) return 2;
		return 1;

	case 0x8: /* tilt */
		if (cmd == 0x0) return 2;
		if (cmd == 0x1) return 8;
		return 1;

	default:
		return 1;
	}
}

static void mext_dispatch_message(void)
{
	uint8_t header = g_mext.rx_buf[0];
	uint8_t addr   = header >> 4;
	uint8_t cmd    = header & 0x0F;

	switch (addr) {
	case 0x0:
		if (cmd == 0x3 && g_mext.rx_expected == 3) {
			uint8_t cols = g_mext.rx_buf[1];
			uint8_t rows = g_mext.rx_buf[2];
			if (cols > 0 && cols <= MEXT_MAX_GRID_X) g_mext.grid_x = cols;
			if (rows > 0 && rows <= MEXT_MAX_GRID_Y) g_mext.grid_y = rows;
		} else if (cmd == 0x0 && g_mext.rx_expected == 3) {
			uint8_t subsystem = g_mext.rx_buf[1];
			uint8_t count     = g_mext.rx_buf[2];
			if (subsystem == 0x5) {
				g_mext.arc_enc_count = (count > MEXT_MAX_ENCODERS)
					? MEXT_MAX_ENCODERS : count;
				if (g_mext.arc_enc_count > 0)
					g_mext.is_arc = true;
			}
		}
		break;

	case 0x2:
		{
			mext_event_t e;
			if (g_mext.is_arc) {
				e.type      = MEXT_EVENT_ENC_KEY;
				e.enc_key.n = g_mext.rx_buf[1];
				e.enc_key.z = (cmd == 0x1) ? 1 : 0;
			} else {
				e.type   = MEXT_EVENT_GRID_KEY;
				e.grid.x = g_mext.rx_buf[1];
				e.grid.y = g_mext.rx_buf[2];
				e.grid.z = (cmd == 0x1) ? 1 : 0;
			}
			event_push(&e);
		}
		break;

	case 0x5:
		{
			mext_event_t e;
			if (cmd == 0x0) {
				e.type      = MEXT_EVENT_ENC_DELTA;
				e.enc.n     = g_mext.rx_buf[1];
				e.enc.delta = (int8_t)g_mext.rx_buf[2];
			} else if (cmd == 0x1) {
				e.type      = MEXT_EVENT_ENC_KEY;
				e.enc_key.n = g_mext.rx_buf[1];
				e.enc_key.z = 0;
			} else if (cmd == 0x2) {
				e.type      = MEXT_EVENT_ENC_KEY;
				e.enc_key.n = g_mext.rx_buf[1];
				e.enc_key.z = 1;
			} else {
				break;
			}
			event_push(&e);
		}
		break;

	default:
		break;
	}
}

static void mext_rx_consume_byte(uint8_t byte)
{
	if (g_mext.rx_expected == 0) {
		if (byte == 0xFF) return;

		g_mext.rx_buf[0]  = byte;
		g_mext.rx_len      = 1;
		g_mext.rx_expected = mext_response_len(byte);

		if (g_mext.rx_expected <= 1) {
			if (g_mext.rx_expected == 1)
				mext_dispatch_message();
			g_mext.rx_expected = 0;
			g_mext.rx_len      = 0;
		}
		return;
	}

	if (g_mext.rx_len < sizeof(g_mext.rx_buf)) {
		g_mext.rx_buf[g_mext.rx_len++] = byte;
	}

	if (g_mext.rx_len >= g_mext.rx_expected) {
		mext_dispatch_message();
		g_mext.rx_expected = 0;
		g_mext.rx_len      = 0;
	}
}

/* ------------------------------------------------------------------ */
/* Public API                                                         */
/* ------------------------------------------------------------------ */

void mext_init(mext_transport_t transport, uint8_t device_cdc_itf)
{
	memset(&g_mext, 0, sizeof(g_mext));
	g_mext.cdc_idx        = -1;
	g_mext.transport      = (uint8_t)transport;
	g_mext.device_cdc_itf = device_cdc_itf;
	g_mext.grid_intensity = 15;
}

void mext_connect(int cdc_idx)
{
	g_mext.cdc_idx   = cdc_idx;
	g_mext.connected = true;

	g_mext.grid_x       = 0;
	g_mext.grid_y       = 0;
	g_mext.arc_enc_count = 0;
	g_mext.is_arc        = false;
	g_mext.rx_len        = 0;
	g_mext.rx_expected   = 0;

	memset(g_mext.grid_led, 0, sizeof(g_mext.grid_led));
	memset(g_mext.grid_next, 0, sizeof(g_mext.grid_next));
	memset(g_mext.arc_ring, 0, sizeof(g_mext.arc_ring));
	for (int q = 0; q < 4; q++) g_mext.grid_dirty[q] = false;
	g_mext.grid_frame_pending = false;

	g_mext.discovery_tick = 0;
	g_mext.connect_time_us = time_us_64();
}

void mext_disconnect(void)
{
	g_mext.connected = false;
	g_mext.cdc_idx   = -1;
}

void mext_grid_led_set(uint8_t x, uint8_t y, uint8_t level)
{
	if (x >= MEXT_MAX_GRID_X || y >= MEXT_MAX_GRID_Y) return;
	if (level > 15) level = 15;

	g_mext.grid_led[y * MEXT_MAX_GRID_X + x] = level;
	g_mext.grid_dirty[quad_idx(x, y)] = true;
}

void mext_grid_led_all(uint8_t level)
{
	if (level > 15) level = 15;
	memset(g_mext.grid_led, level, sizeof(g_mext.grid_led));
	for (int q = 0; q < 4; q++) g_mext.grid_dirty[q] = true;
}

void mext_grid_led_intensity(uint8_t level)
{
	g_mext.grid_intensity = level & 0x0F;
	g_mext.intensity_pending = true;
}

void mext_grid_all_off(void)
{
	const uint8_t buf[] = {0x12};
	mext_send_raw(buf, sizeof(buf));
}

bool __not_in_flash_func(mext_grid_frame_submit)(const uint8_t *levels)
{
	if (levels == NULL)
		return false;
	if (g_mext.grid_frame_pending)
		return false;

	memcpy(g_mext.grid_next, levels, sizeof(g_mext.grid_next));
	__dmb();
	g_mext.grid_frame_pending = true;
	return true;
}

void mext_send_discovery(void)
{
	const uint8_t query_caps[] = {0x00};
	const uint8_t query_id[]   = {0x01};
	const uint8_t query_size[] = {0x05};

	mext_send(query_caps, sizeof(query_caps));
	mext_send(query_id,   sizeof(query_id));
	mext_send(query_size, sizeof(query_size));
}

void mext_grid_refresh(void)
{
	if (!g_mext.connected) return;
	if (g_mext.grid_x == 0 || g_mext.grid_y == 0) return;

	if (g_mext.grid_frame_pending) {
		memcpy(g_mext.grid_led, g_mext.grid_next, sizeof(g_mext.grid_led));
		for (int q = 0; q < 4; q++) g_mext.grid_dirty[q] = true;
		__dmb();
		g_mext.grid_frame_pending = false;
	}

	if (g_mext.intensity_pending) {
		uint8_t ibuf[2] = {0x17, g_mext.grid_intensity};
		mext_send_raw(ibuf, 2);
		g_mext.intensity_pending = false;
	}

	for (uint8_t yo = 0; yo < g_mext.grid_y; yo += 8) {
		for (uint8_t xo = 0; xo < g_mext.grid_x; xo += 8) {
			uint8_t q = quad_idx(xo, yo);
			if (!g_mext.grid_dirty[q]) continue;

			uint8_t levels[64];
			for (uint8_t r = 0; r < 8; r++) {
				for (uint8_t c = 0; c < 8; c++) {
					uint8_t gx = xo + c;
					uint8_t gy = yo + r;
					if (gx < g_mext.grid_x && gy < g_mext.grid_y)
						levels[r * 8 + c] = g_mext.grid_led[gy * MEXT_MAX_GRID_X + gx];
					else
						levels[r * 8 + c] = 0;
				}
			}

			uint8_t buf[35];
			buf[0] = 0x1A;
			buf[1] = xo;
			buf[2] = yo;
			uint8_t *p = buf + 3;
			for (int i = 0; i < 64; i += 2) {
				*p++ = (levels[i] << 4) | (levels[i + 1] & 0x0F);
			}

			mext_send_raw(buf, 35);
			g_mext.grid_dirty[q] = false;
		}
	}
}

void mext_rx_feed(const uint8_t *data, uint32_t len)
{
	for (uint32_t i = 0; i < len; i++) {
		mext_rx_consume_byte(data[i]);
	}
}

bool __not_in_flash_func(mext_event_pop)(mext_event_t *out)
{
	if (g_mext.events.r == g_mext.events.w)
		return false;

	*out = g_mext.events.buf[g_mext.events.r];
	g_mext.events.r = (g_mext.events.r + 1) % MEXT_EVENT_QUEUE_SIZE;
	return true;
}

bool __not_in_flash_func(mext_grid_ready)(void)
{
	return g_mext.connected && g_mext.grid_x > 0 && g_mext.grid_y > 0;
}

/* ------------------------------------------------------------------ */
/* Polling task                                                       */
/* ------------------------------------------------------------------ */

#define MEXT_REFRESH_US  16667  /* ~60 fps */

static uint64_t s_last_refresh_us = 0;

void mext_task(void)
{
	if (g_mext.transport == MEXT_TRANSPORT_HOST) {
		tuh_task();
	}

	if (!g_mext.connected)
		return;

	if (g_mext.transport == MEXT_TRANSPORT_HOST) {
		uint8_t buf[64];
		uint32_t n = tuh_cdc_read((uint8_t)g_mext.cdc_idx, buf, sizeof(buf));
		if (n > 0) {
			mext_rx_feed(buf, n);
		}
	} else {
#ifndef VCV_PORT
#if MEXT_HAVE_DEVICE_CDC
		if (tud_mounted()) {
			uint8_t buf[64];
			uint32_t n = tud_cdc_n_read(g_mext.device_cdc_itf, buf, sizeof(buf));
			if (n > 0) {
				mext_rx_feed(buf, n);
			}
		}
#endif
#endif
	}

	if (g_mext.grid_x == 0 || g_mext.grid_y == 0) {
		uint64_t now_us = time_us_64();
		uint64_t elapsed_ms = (now_us - g_mext.connect_time_us) / 1000;
		if ((elapsed_ms > 200 && g_mext.discovery_tick == 0) ||
		    (elapsed_ms > 1000 && (elapsed_ms / 1000) > g_mext.discovery_tick)) {
			g_mext.discovery_tick = (uint32_t)(elapsed_ms / 1000);
			mext_send_discovery();
		}
	}

	uint64_t now_us = time_us_64();
	if (now_us - s_last_refresh_us >= MEXT_REFRESH_US) {
		s_last_refresh_us = now_us;
		mext_grid_refresh();
	}
}

/* ------------------------------------------------------------------ */
/* TinyUSB CDC host callbacks                                         */
/* ------------------------------------------------------------------ */

void tuh_cdc_mount_cb(uint8_t idx)
{
	if (g_mext.transport != MEXT_TRANSPORT_HOST)
		return;

	if (!g_mext.connected) {
		mext_connect((int)idx);
	}
}

void tuh_cdc_umount_cb(uint8_t idx)
{
	if (g_mext.transport != MEXT_TRANSPORT_HOST)
		return;

	if (g_mext.cdc_idx == (int)idx) {
		mext_disconnect();
	}
}

void tuh_cdc_rx_cb(uint8_t idx)
{
	(void)idx;
}

void tuh_cdc_tx_complete_cb(uint8_t idx)
{
	(void)idx;
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: grid_ui.cpp
// ──────────────────────────────────────────────────────────────────────────────

// drumdrum-specific Monome Grid layout for a 16x8 device.
//
//   LEFT half (cols 0–7) — sequence overview
//     Row 0           length selector  (cols 0..7 = "set length to N+1")
//     Rows 1–7        per-step bar — height = pitch, brightness = velocity
//                       (current/edit step override the brightness so they
//                        stand out; out-of-length columns are off)
//
//   RIGHT half (cols 8–15) — selected-step editor
//     (col 15, row 0) play/pause toggle
//     Rows 1–5        chromatic pitch grid (40 notes from MIDI 36)
//                     bottom-left = lowest pitch, top-right = highest
//     Rows 6–7        16-step velocity bar
//                     bottom-left = lowest, top-right = highest

#include "grid_ui.h"
#include "monome_mext.h"
#include "shared_state.h"

/* stripped pico include */

/* stripped system include */
/* stripped system include */

// Local snapshot of last-rendered state — lets us skip redundant LED
// writes without touching gState mid-frame.
struct RenderSnap {
    uint8_t  pitch[8];
    uint8_t  velocity[8];
    uint8_t  seqLength;
    uint8_t  editStep;
    uint8_t  currentStep;
    uint8_t  playing;
    uint32_t tickEpoch;
    bool     valid;
};
static RenderSnap snap = {};

// ── Layout helpers ────────────────────────────────────────────

// Pitch → bar height (1..7 cells), scaled across the full 0..127
// MIDI range so the bar tops out only at the highest possible pitches.
static inline uint8_t pitch_to_bar_height(uint8_t pitch)
{
    int32_t h = ((int32_t)pitch * 7) / 127;     // 0..7
    if (h > 6) h = 6;
    return (uint8_t)(h + 1);                    // 1..7
}

// Brightness for a step's column on the left-half overview.
// "other" steps show velocity-as-brightness so the bar carries both
// pieces of info at once. Current playback overrides to full bright.
// The edit step gets a brightness floor so it's always clearly visible.
static inline uint8_t left_brightness(uint8_t step, const RenderSnap &s)
{
    if (step >= s.seqLength) return 0;
    if (step == s.currentStep && s.playing) return 15;

    uint8_t vb = (uint8_t)(s.velocity[step] >> 4);  // 0..15
    if (vb < 1) vb = 1;                             // never invisible

    if (step == s.editStep) {
        if (vb < 6) vb = 6;                         // edit floor
    }
    return vb;
}

// Right-half pitch grid: full-range MIDI note → (col, row). Each cell
// is a 3-or-4-pitch bin so every MIDI pitch lands somewhere on the
// grid. Row 5 (bottom) holds the lowest pitch, row 1 (top) the highest.
static inline uint8_t pitch_to_cell(uint8_t note)
{
    int32_t off = ((int32_t)note * PITCH_GRID_CELLS) / 128;
    if (off >= PITCH_GRID_CELLS) off = PITCH_GRID_CELLS - 1;
    if (off < 0) off = 0;
    return (uint8_t)off;
}

static void note_to_right_cell(uint8_t note, uint8_t *col_out, uint8_t *row_out)
{
    uint8_t off = pitch_to_cell(note);
    *row_out = (uint8_t)(5 - (off >> 3));
    *col_out = (uint8_t)(8 + (off & 7));
}

// Cell N → representative pitch (centre of the cell's bin).
static inline uint8_t cell_to_pitch(uint8_t off)
{
    int32_t p = ((int32_t)off * 128 + 64) / PITCH_GRID_CELLS;
    if (p > 127) p = 127;
    if (p < 0)   p = 0;
    return (uint8_t)p;
}

// Right-half velocity bar: idx 0..15 → (col, row). idx 0 is at the
// bottom-left (least velocity), idx 15 at the top-right (most).
static inline void vel_idx_to_cell(uint8_t idx, uint8_t *col_out, uint8_t *row_out)
{
    *row_out = (uint8_t)(7 - (idx >> 3));     // row 7 (bottom) for idx 0..7, row 6 for 8..15
    *col_out = (uint8_t)(8 + (idx & 7));
}

// ── public API ────────────────────────────────────────────────
void grid_ui_init(void)
{
    snap.valid = false;
    mext_grid_led_intensity(15);
    mext_grid_led_all(0);
}

void grid_ui_process_input(void)
{
    mext_event_t ev;
    while (mext_event_pop(&ev)) {
        if (ev.type != MEXT_EVENT_GRID_KEY) continue;
        if (ev.grid.z == 0) continue;          // act on key-down only

        uint8_t x = ev.grid.x, y = ev.grid.y;

        if (x < 8) {
            // ── LEFT half ─────────────────────────────────
            if (y == 0) {
                // length selector: tap col N → length N+1 (1–8 inclusive)
                uint8_t newLen = (uint8_t)(x + 1);
                gState.seqLength = newLen;
                if (gState.editStep    >= newLen) gState.editStep    = 0;
                if (gState.currentStep >= newLen) gState.currentStep = 0;
            } else {
                // any other left cell selects the edit step for that column
                if (x < gState.seqLength) {
                    gState.editStep = x;
                }
            }
        } else {
            // ── RIGHT half ────────────────────────────────
            if (y == 0) {
                // only col 15 row 0 is a button; cols 8..14 are reserved
                if (x == 15) {
                    gState.playing = gState.playing ? 0 : 1;
                }
            } else if (y >= 1 && y <= 5) {
                // pitch picker — 40 cells covering all 128 MIDI pitches
                // in 3-or-4-pitch bins. Tapping a cell snaps the pitch
                // to the bin centre; the panel knob can dial anything
                // in between for fine-grained editing.
                uint8_t off = (uint8_t)(((5 - y) << 3) + (x - 8));
                if (off < PITCH_GRID_CELLS) {
                    gState.pitch[gState.editStep] = cell_to_pitch(off);
                }
            } else {
                // y == 6 or 7 — velocity bar (16 cells, bottom-left = low)
                uint8_t idx = (uint8_t)(((7 - y) << 3) + (x - 8));   // 0..15
                uint16_t v = (uint16_t)((idx + 1) << 4);             // 16..256
                if (v > 255) v = 255;
                gState.velocity[gState.editStep] = (uint8_t)v;
            }
        }
    }
}

static bool snap_matches(const RenderSnap &a)
{
    if (!a.valid) return false;
    if (a.seqLength   != gState.seqLength)   return false;
    if (a.editStep    != gState.editStep)    return false;
    if (a.currentStep != gState.currentStep) return false;
    if (a.playing     != gState.playing)     return false;
    if (a.tickEpoch   != gState.tickEpoch)   return false;
    if (memcmp((const void*)a.pitch,    (const void*)gState.pitch,    8) != 0) return false;
    if (memcmp((const void*)a.velocity, (const void*)gState.velocity, 8) != 0) return false;
    return true;
}

static void take_snapshot(RenderSnap &out)
{
    memcpy(out.pitch,    (const void*)gState.pitch,    8);
    memcpy(out.velocity, (const void*)gState.velocity, 8);
    out.seqLength   = gState.seqLength;
    out.editStep    = gState.editStep;
    out.currentStep = gState.currentStep;
    out.playing     = gState.playing;
    out.tickEpoch   = gState.tickEpoch;
    out.valid       = true;
}

void grid_ui_render(void)
{
    if (!mext_grid_ready()) return;
    if (snap_matches(snap)) return;

    take_snapshot(snap);
    const RenderSnap &s = snap;

    uint8_t buf[256];
    memset(buf, 0, sizeof(buf));

    // ── LEFT half — sequence overview ───────────────────
    // Row 0: length indicator
    for (uint8_t c = 0; c < 8; c++) {
        buf[0 * 16 + c] = (c < s.seqLength) ? 8 : 0;
    }
    // Rows 1–7: per-step bar (height = pitch, brightness = velocity)
    for (uint8_t step = 0; step < 8; step++) {
        uint8_t b = left_brightness(step, s);
        if (b == 0) continue;
        uint8_t h = pitch_to_bar_height(s.pitch[step]);   // 1..7
        for (uint8_t k = 0; k < h; k++) {
            uint8_t r = (uint8_t)(7 - k);                 // fill from bottom up
            buf[r * 16 + step] = b;
        }
    }

    // ── RIGHT half — selected-step editor ───────────────
    // (col 15, row 0): play/pause
    buf[0 * 16 + 15] = s.playing ? 15 : 3;

    // Rows 1–5: pitch picker (40 cells, every MIDI pitch reachable).
    // Only the current pitch is lit — keeps the picker uncluttered.
    {
        uint8_t c, r;
        note_to_right_cell(s.pitch[s.editStep], &c, &r);
        buf[r * 16 + c] = 15;
    }

    // Rows 6–7: velocity bar (16 cells, bottom-left = low)
    {
        uint8_t v = s.velocity[s.editStep];
        // Number of cells lit, 0..16. ceil(v/16) so any non-zero
        // velocity lights at least one cell, and v=255 lights all 16.
        uint8_t lit = (uint8_t)((v + 15) >> 4);
        if (lit > 16) lit = 16;
        for (uint8_t idx = 0; idx < lit; idx++) {
            uint8_t c, r;
            vel_idx_to_cell(idx, &c, &r);
            buf[r * 16 + c] = 10;
        }
    }

    // Push the frame. mext clones into its own buffer, so `buf` can go
    // out of scope immediately. Falls back to per-cell writes if a frame
    // is already in flight (rare with 60 fps refresh).
    if (!mext_grid_frame_submit(buf)) {
        for (uint8_t y = 0; y < 8; y++) {
            for (uint8_t x = 0; x < 16; x++) {
                mext_grid_led_set(x, y, buf[y * 16 + x]);
            }
        }
    }
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: midi_host.cpp
// ──────────────────────────────────────────────────────────────────────────────

// Minimal class-compliant USB MIDI host driver for Music Thing 8mu.
// See midi_host.h for the CC dispatch table.

#include "midi_host.h"
#include "shared_state.h"

/* stripped tusb include */
#include "host/usbh_pvt.h"
#include "class/midi/midi.h"
/* stripped pico include */

/* stripped system include */
/* stripped system include */

// ── Driver-private state ─────────────────────────────────────────────
// Only one MIDI device tracked at a time. The Workshop Computer's front
// jack is a single port; a hub could in principle bring more, but v1
// only listens to the first MIDI device that mounts.
static volatile bool s_connected     = false;
static uint8_t       s_dev_addr      = 0;
static uint8_t       s_ep_in         = 0;       // bulk-IN endpoint address (with direction bit)
static uint16_t      s_ep_in_size    = 64;      // bulk-IN max packet size
static uint8_t       s_last_itf      = TUSB_INDEX_INVALID_8; // highest interface we claimed

// Per-button rising-edge state (CC value <64 → ≥64 = press).
static uint8_t       s_btn22_prev    = 0;
static uint8_t       s_btn23_prev    = 0;
static uint8_t       s_btn24_prev    = 0;

// USB-MIDI Event Packets are 4 bytes each. 64 bytes = up to 16 events
// per IN transfer, which is plenty: an 8mu sweeps a fader at maybe
// 100 Hz max.
static uint8_t       s_rx_buf[64];

// ── Helpers ──────────────────────────────────────────────────────────
static inline bool button_press_edge(uint8_t* prev, uint8_t value) {
    bool press = (value >= 64) && (*prev < 64);
    *prev = value;
    return press;
}

// Core-1-local xorshift32 PRNG used for the randomize button. Distinct
// from the audio ISR's PRNG on Core 0 — they don't need to share state,
// and a separate generator means a randomize press doesn't perturb the
// white-noise stream. Seeded lazily on first use from the hardware us
// counter, which has effectively unbounded entropy by the time someone
// presses a button.
static uint32_t s_rng = 0;
static uint32_t midi_xorshift(void) {
    if (s_rng == 0) {
        s_rng = time_us_32();
        if (s_rng == 0) s_rng = 0xDEADBEEF;
    }
    s_rng ^= s_rng << 13;
    s_rng ^= s_rng >> 17;
    s_rng ^= s_rng << 5;
    return s_rng;
}

// Re-roll all 8 step pitches and velocities. Matches the constructor's
// boot randomisation in main.cpp: pitches in C2..B4 (the musical sweet
// spot of the MIDI range) and velocities biased toward the upper half
// so every step stays audible. Bumps tickEpoch once at the end so a
// future browser/Grid replug sees the new pattern in one go.
//
// Single-byte writes are atomic on M0+, so the audio ISR reading a
// pitch/velocity mid-randomize may see one new value and one old —
// that's fine. At 48 kHz the whole loop is over in under a hundred
// samples; sonically it's an instant scramble, which is what we want.
static void randomize_pattern(void) {
    for (int i = 0; i < 8; i++) {
        gState.pitch[i]    = (uint8_t)(36 + (midi_xorshift() % 36));
        gState.velocity[i] = (uint8_t)(100 + (midi_xorshift() % 156));
    }
}

static void handle_cc(uint8_t cc, uint8_t v) {
    bool changed = false;
    if (cc >= 34 && cc <= 41) {
        const uint8_t i = (uint8_t)(cc - 34);
        if (gState.midiHostVelocityMode) {
            gState.velocity[i] = (uint8_t)(v << 1);
        } else {
            gState.pitch[i] = v;
        }
        changed = true;
    } else if (cc >= 50 && cc <= 57) {
        gState.velocity[cc - 50] = (uint8_t)(v << 1);
        changed = true;
    } else if (cc == 28) {
        uint8_t step = (uint8_t)((v * 8u) >> 7);
        if (step > 7) step = 7;
        gState.editStep = step;
        changed = true;
    } else if (cc == 22) {
        if (button_press_edge(&s_btn22_prev, v)) {
            gState.midiHostVelocityMode ^= 1;
            changed = true;
        }
    } else if (cc == 23) {
        if (button_press_edge(&s_btn23_prev, v)) {
            gState.playing ^= 1;
            changed = true;
        }
    } else if (cc == 24) {
        if (button_press_edge(&s_btn24_prev, v)) {
            // Mirrors the Pulse In 2 reset: jump to step 1. currentStep
            // is normally written only by Core 0, but a single-byte
            // store from Core 1 is atomic on the M0+ — and the audio
            // ISR's only "reaction" is to display/play step 0, which
            // is exactly what we want.
            gState.currentStep = 0;
            changed = true;
        }
    }
    if (changed) gState.tickEpoch++;
}

// 8mu factory button mappings. The 8mu firmware sends note-on with a
// velocity byte for press and either a note-off OR a note-on with
// velocity 0 (running-status convention) for release. We act on press
// only — drop anything with velocity 0.
static void handle_note_on(uint8_t note, uint8_t vel) {
    if (vel == 0) return;
    bool changed = true;
    switch (note) {
        case 36:  // button 1 — C2
            gState.midiHostVelocityMode ^= 1;
            break;
        case 48:  // button 2 — C3
            gState.playing ^= 1;
            break;
        case 60:  // button 3 — C4 (middle C)
            // Mirrors Pulse In 2 reset (and the CC 24 alt mapping).
            gState.currentStep = 0;
            break;
        case 72:  // button 4 — C5
            randomize_pattern();
            break;
        default:
            changed = false;
            break;
    }
    if (changed) gState.tickEpoch++;
}

static void rearm_rx(void) {
    if (!s_connected || s_ep_in == 0) return;
    if (!usbh_edpt_claim(s_dev_addr, s_ep_in)) return;
    uint16_t const len = (s_ep_in_size > sizeof(s_rx_buf))
        ? (uint16_t)sizeof(s_rx_buf) : s_ep_in_size;
    if (!usbh_edpt_xfer(s_dev_addr, s_ep_in, s_rx_buf, len)) {
        // The internal usbh_edpt_xfer (class-driver-level) does NOT
        // roll back the claim on failure — only the app-level
        // tuh_edpt_xfer does. Without an explicit release here, a
        // transient submit failure would leave the IN endpoint
        // permanently claimed and every subsequent rearm_rx() would
        // bail at the claim step above, silently stopping all MIDI
        // input until the 8mu is unplugged. Caught by Codex review
        // on PR #8.
        usbh_edpt_release(s_dev_addr, s_ep_in);
    }
}

static void clear_state(void) {
    s_connected   = false;
    s_dev_addr    = 0;
    s_ep_in       = 0;
    s_ep_in_size  = 64;
    s_last_itf    = TUSB_INDEX_INVALID_8;
    s_btn22_prev  = 0;
    s_btn23_prev  = 0;
    s_btn24_prev  = 0;
}

// ── Public API ───────────────────────────────────────────────────────
extern "C" void midi_host_init(void) {
    clear_state();
}

// ── TinyUSB class-driver callbacks ───────────────────────────────────
//
// Driver lifecycle:
//   driver_init       — once at host stack init.
//   driver_open       — when a matching interface descriptor arrives
//                       during enumeration. We claim two interfaces
//                       (Audio-Control + MIDIStreaming) by parsing
//                       through to the bulk endpoints and opening them.
//   driver_set_config — once the device is in CONFIGURED state. We
//                       kick off the first IN read here, then signal
//                       the host stack we're done with this interface.
//   driver_xfer_cb    — every time a bulk-IN packet completes.
//   driver_close      — on disconnect.

static bool driver_init(void) {
    clear_state();
    return true;
}

static bool driver_deinit(void) {
    clear_state();
    return true;
}

static bool driver_open(uint8_t rhport, uint8_t dev_addr,
                        tusb_desc_interface_t const* itf_desc, uint16_t max_len) {
    (void)rhport;

    // We only claim Audio-class interfaces. The descriptor parser at
    // usbh.c:1681 groups Audio-Control (subclass 1) + MIDIStreaming
    // (subclass 3) together via assoc_itf_count=2 when CFG_TUH_MIDI=1.
    // Some devices skip Audio-Control entirely, so accept either entry.
    if (itf_desc->bInterfaceClass != TUSB_CLASS_AUDIO) return false;
    if (itf_desc->bInterfaceSubClass != 1 /* AUDIO_SUBCLASS_CONTROL */ &&
        itf_desc->bInterfaceSubClass != 3 /* AUDIO_SUBCLASS_MIDI_STREAMING */) {
        return false;
    }

    // Only one MIDI device at a time.
    if (s_connected) return false;

    uint8_t const* p_desc = (uint8_t const*)itf_desc;
    uint8_t const* p_end  = p_desc + max_len;

    // Walk forward to the MIDIStreaming interface. If we entered on
    // MIDIStreaming directly, the very first iteration matches.
    // Stash its interface number so set_config can tell the host stack
    // to resume past our claimed group — see driver_set_config below.
    uint8_t ms_itf_num = TUSB_INDEX_INVALID_8;
    while (p_desc < p_end) {
        if (tu_desc_type(p_desc) == TUSB_DESC_INTERFACE) {
            tusb_desc_interface_t const* itf = (tusb_desc_interface_t const*)p_desc;
            if (itf->bInterfaceClass    == TUSB_CLASS_AUDIO &&
                itf->bInterfaceSubClass == 3 /* MIDIStreaming */) {
                ms_itf_num = itf->bInterfaceNumber;
                p_desc = tu_desc_next(p_desc);
                break;
            }
        }
        p_desc = tu_desc_next(p_desc);
    }
    if (ms_itf_num == TUSB_INDEX_INVALID_8) return false;

    // Now scan for the bulk endpoints. Stop at the next interface.
    uint8_t  ep_in = 0, ep_out = 0;
    uint16_t ep_in_size = 64;
    while (p_desc < p_end) {
        uint8_t const dt = tu_desc_type(p_desc);
        if (dt == TUSB_DESC_INTERFACE) {
            break;
        } else if (dt == TUSB_DESC_ENDPOINT) {
            tusb_desc_endpoint_t const* ep = (tusb_desc_endpoint_t const*)p_desc;
            if (ep->bmAttributes.xfer == TUSB_XFER_BULK) {
                if (tu_edpt_dir(ep->bEndpointAddress) == TUSB_DIR_IN) {
                    if (!tuh_edpt_open(dev_addr, ep)) return false;
                    ep_in      = ep->bEndpointAddress;
                    ep_in_size = tu_edpt_packet_size(ep);
                } else {
                    if (!tuh_edpt_open(dev_addr, ep)) return false;
                    ep_out = ep->bEndpointAddress;
                }
            }
        }
        p_desc = tu_desc_next(p_desc);
    }
    if (ep_in == 0) return false;  // need at least an IN endpoint
    (void)ep_out; // OUT not used in v1 (no SysEx writes back to 8mu)

    s_dev_addr   = dev_addr;
    s_ep_in      = ep_in;
    s_ep_in_size = ep_in_size;
    s_last_itf   = ms_itf_num;
    return true;
}

static bool driver_set_config(uint8_t dev_addr, uint8_t itf_num) {
    (void)itf_num;
    s_connected = true;
    rearm_rx();
    // Tell the host stack this driver has finished configuring. The
    // stack's loop advances `itf_num++` and resumes searching for the
    // next driver from there (usbh.c:1740). When our driver claimed
    // both AudioControl + MIDIStreaming, both interface numbers map
    // back to us in dev->itf2drv[], so we MUST return the highest
    // claimed interface number — passing TUSB_INDEX_INVALID_8 (0xFF)
    // would wrap to 0, find our driver again, and recurse until the
    // stack overflows. The TinyUSB header note for IAD-binding drivers
    // says exactly this: "should return itf_num + 1 when complete".
    usbh_driver_set_config_complete(dev_addr, s_last_itf);
    return true;
}

static bool driver_xfer_cb(uint8_t dev_addr, uint8_t ep_addr,
                           xfer_result_t result, uint32_t xferred_bytes) {
    (void)dev_addr;
    if (ep_addr != s_ep_in) {
        // OUT-completion or stray callback — ignore.
        return true;
    }
    if (result == XFER_RESULT_SUCCESS) {
        // Parse 32-bit USB-MIDI Event Packets. Each packet:
        //   byte 0: (cable_num << 4) | code_index_number
        //   bytes 1..3: MIDI message bytes
        // 8mu has only one cable, but we accept any cable index.
        for (uint32_t i = 0; i + 4 <= xferred_bytes; i += 4) {
            uint8_t const cin = (uint8_t)(s_rx_buf[i] & 0x0F);
            if (cin == MIDI_CIN_CONTROL_CHANGE) {
                handle_cc((uint8_t)(s_rx_buf[i + 2] & 0x7F),
                          (uint8_t)(s_rx_buf[i + 3] & 0x7F));
            } else if (cin == MIDI_CIN_NOTE_ON) {
                // 8mu's factory button defaults send these.
                handle_note_on((uint8_t)(s_rx_buf[i + 2] & 0x7F),
                               (uint8_t)(s_rx_buf[i + 3] & 0x7F));
            }
            // CIN 8 (NOTE_OFF), sysex, pitch bend, etc. are dropped.
        }
    }
    // Always re-arm: a stalled or aborted xfer should still try again.
    rearm_rx();
    return true;
}

static void driver_close(uint8_t dev_addr) {
    if (s_dev_addr == dev_addr) {
        clear_state();
    }
}

// Aggregate-initialised in field order to avoid the C++ designated-init
// extension. Match the order of usbh_class_driver_t in usbh_pvt.h:
//   name, init, deinit, open, set_config, xfer_cb, close.
static usbh_class_driver_t const s_drivers[] = {
    {
        "MIDI",
        driver_init,
        driver_deinit,
        driver_open,
        driver_set_config,
        driver_xfer_cb,
        driver_close,
    },
};

extern "C" usbh_class_driver_t const* usbh_app_driver_get_cb(uint8_t* driver_count) {
    *driver_count = (uint8_t)(sizeof(s_drivers) / sizeof(s_drivers[0]));
    return s_drivers;
}


} // namespace Card_DrumDrum

extern "C" {
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_DrumDrum::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
