// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include <array>
#include <cmath>
#include <complex>
#include <random>
#include <functional>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <initializer_list>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

#define _Static_assert static_assert
namespace std { using ::sinf; using ::cosf; using ::tanf; using ::asinf; using ::acosf; using ::atanf; using ::atan2f; using ::sqrtf; using ::expf; using ::logf; using ::log10f; using ::powf; }

// DSO-local thread-local variables definition




namespace Card_Knots {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: main.cpp
// ──────────────────────────────────────────────────────────────────────────────

/* stripped ComputerCard include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped pico include */
#include "pico.h"
/* stripped pico include */

#include "knots/src/core/control_router.h"
#include "knots/src/core/midi_worker.h"
#include "knots/src/core/shared_state.h"
#include "knots/src/dsp/sine_lut.h"
#include "knots/src/engines/engine_registry.h"

namespace mtws {

namespace {
constexpr int32_t kUnityQ12 = 4096;
constexpr int kVCAGainSmoothShift = 6;

// Maps MIDI CC74 from 0..127 into the ComputerCard bipolar CV code range.
// The endpoints intentionally use the full raw code span so the output is
// approximately -6 V at startup and +6 V at the top of the CC range.
inline int16_t __not_in_flash_func(MapCC74ToCV2Code)(uint8_t cc74_value) {
  return int16_t(((uint32_t(cc74_value) * 4095U) + 63U) / 127U) - 2048;
}

// Slews one Q12 gain toward its latest target with a tiny integer one-pole
// step. `shift = 6` means each sample moves by roughly 1/64 of the remaining
// error, which lengthens the fixed CV2 fade enough to better suppress
// gate-driven clicks while keeping the path lightweight and responsive.
inline int32_t __not_in_flash_func(SmoothToward)(int32_t current, int32_t target, int shift) {
  if (shift <= 0) return target;
  int32_t delta = target - current;
  int32_t step = delta >> shift;
  if (step == 0 && delta != 0) {
    step = (delta > 0) ? 1 : -1;
  }
  return current + step;
}

// Available clock divisions for MIDI clock mode. Each entry is the number of
// input ticks (at 24 PPQN) per output pulse. Spread as 8 equal steps across
// the X knob. All values divide evenly into 24 for clean timing.
constexpr uint8_t kClockDivisions[] = {24, 12, 8, 6, 4, 3, 2, 1};
constexpr uint8_t kNumClockDivisions = 8;

// Maps X knob (0..4095) to an index in kClockDivisions (0..7).
inline uint8_t ClockDivisionIndexFromKnobX(uint16_t knob_x) {
  uint32_t idx = (uint32_t(knob_x) * kNumClockDivisions) >> 12;
  if (idx >= kNumClockDivisions) idx = kNumClockDivisions - 1U;
  return uint8_t(idx);
}

// Maps X knob (0..4095) to an internal clock period in control ticks.
// 20 BPM = 3000 ticks, 999 BPM = 60 ticks (linear across the knob).
inline uint32_t InternalClockPeriodFromKnobX(uint16_t knob_x) {
  uint32_t bpm = 20U + ((uint32_t(knob_x) * 979U + 2048U) >> 12);
  if (bpm < 20U) bpm = 20U;
  if (bpm > 999U) bpm = 999U;
  return 60000U / bpm;
}

// Clamps one raw knob reading into the documented 12-bit panel range so the
// rest of the control path can work in a consistent 0..4095 domain.
inline uint16_t ClampKnobU12(int32_t knob_value) {
  if (knob_value < 0) return 0;
  if (knob_value > 4095) return 4095;
  return uint16_t(knob_value);
}

}  // namespace

class MTWSApp : public ComputerCard {
 public:
  static constexpr uint32_t kControlDivisor = 48;
  static constexpr uint32_t kControlPeriodUs = (kControlDivisor * 1000000U) / 48000U;
  static constexpr uint8_t kSwitchDebounceTicks = 3;
  static constexpr uint32_t kNoteFlashOffSamples = 960;  // ~20ms
  // Control ticks without a new MIDI clock tick before switching to internal.
  static constexpr uint32_t kClockTimeoutTicks = 500;
  // ~5ms pulse width = 5 control ticks at ~1kHz control rate.
  static constexpr uint32_t kPulseWidthTicks = 5;
  // Requiring 16 raw knob counts cancels only deliberate X movement while
  // still ignoring the small idle jitter the smoothed knob can report.
  static constexpr uint16_t kZSwitchClockConfigDeadband = 16;

  MTWSApp()
      : lut_(),
        registry_(&lut_),
        midi_worker_(),
        published_ui_snapshot_index_(0),
        published_frame_index_(0),
        control_counter_(int(kControlDivisor)),
        switch_candidate_(Middle),
        switch_stable_(Middle),
        switch_stable_count_(0),
        switch_inputs_primed_(false),
        pulse2_high_prev_(false),
        panel_alt_latched_(false),
        selected_slot_(0),
        z_switch_hold_active_(false),
        z_switch_slot_armed_(false),
        z_switch_clock_edit_active_(false),
        z_switch_down_knob_x_(0),
        seen_note_on_counter_(0),
        note_flash_samples_remaining_(0),
        last_cv_note_sent_(255),
        last_cc74_sent_(0),
        last_pulse1_gate_sent_(2),
        smoothed_vca_gain_q12_(kUnityQ12),
        core1_started_(false),
        last_clock_tick_seen_(0),
        clock_inactive_counter_(kClockTimeoutTicks),
        clock_division_ticks_(6),
        midi_clock_div_counter_(0),
        internal_clock_period_(500),
        internal_clock_counter_(500),
        pulse2_width_counter_(0) {
    instance_ = this;

    EnableNormalisationProbe();
    CVOut2(MapCC74ToCV2Code(0));
    registry_.Init();
    registry_.Get(selected_slot_)->OnSelected();

    UISnapshot init_ui{};
    init_ui.knob_main = 2048;
    init_ui.knob_x = 0;
    init_ui.knob_y = 0;
    init_ui.cv1 = 0;
    init_ui.cv2 = 0;
    init_ui.audio1 = 0;
    init_ui.audio2 = 0;
    init_ui.audio1_connected = false;
    init_ui.audio2_connected = false;
    init_ui.cv2_connected = false;
    init_ui.pulse1_connected = false;
    init_ui.pulse1_high = false;
    init_ui.selected_slot = selected_slot_;
    init_ui.panel_alt_latched = panel_alt_latched_;
    ui_snapshots_[0] = init_ui;
    ui_snapshots_[1] = init_ui;

    MidiState init_midi{};
    init_midi.note_active = false;
    init_midi.current_note = 60;
    init_midi.last_note = 60;
    init_midi.cc74_value = 0;
    init_midi.note_on_counter = 0;
    init_midi.clock_tick_count = 0;

    GlobalControlFrame init_global = ControlRouter::BuildGlobalFrame(init_ui, init_midi);
    for (int i = 0; i < 2; ++i) {
      control_frames_[i].global = init_global;
      registry_.Get(init_global.selected_slot)->ControlTick(init_global, control_frames_[i].engine);
    }
    smoothed_vca_gain_q12_ = int32_t(init_global.vca_gain_q12);
  }

  static void Core1Entry() {
    if (instance_ != nullptr) {
      instance_->ControlAndMIDIWorkerCore();
    }
  }

  void ControlAndMIDIWorkerCore() {
    midi_worker_.Init();

    #ifdef __EMSCRIPTEN__
    g_wasm_core1_tick = [this]() {
        
      midi_worker_.Poll();

      __dmb();
      uint32_t ui_read_index = published_ui_snapshot_index_;
      UISnapshot ui = ui_snapshots_[ui_read_index];
      MidiState midi = midi_worker_.Snapshot();

      GlobalControlFrame global = ControlRouter::BuildGlobalFrame(ui, midi);

      uint32_t read_index = published_frame_index_;
      uint32_t write_index = read_index ^ 1U;
      ControlFrame& frame = control_frames_[write_index];
      frame.global = global;
      registry_.Get(global.selected_slot)->ControlTick(global, frame.engine);

      __dmb();
      published_frame_index_ = write_index;

      busy_wait_us_32(kControlPeriodUs);
    
    };
#else
    while (1) {
        
      midi_worker_.Poll();

      __dmb();
      uint32_t ui_read_index = published_ui_snapshot_index_;
      UISnapshot ui = ui_snapshots_[ui_read_index];
      MidiState midi = midi_worker_.Snapshot();

      GlobalControlFrame global = ControlRouter::BuildGlobalFrame(ui, midi);

      uint32_t read_index = published_frame_index_;
      uint32_t write_index = read_index ^ 1U;
      ControlFrame& frame = control_frames_[write_index];
      frame.global = global;
      registry_.Get(global.selected_slot)->ControlTick(global, frame.engine);

      __dmb();
      published_frame_index_ = write_index;

      busy_wait_us_32(kControlPeriodUs);
    
    }
#endif
  }

  // Advances to the next engine slot and lets the new engine refresh any
  // per-selection state before the next render call.
  inline void __not_in_flash_func(AdvanceSelectedSlot)() {
    selected_slot_ = uint8_t((selected_slot_ + 1U) % kNumOscillatorSlots);
    registry_.Get(selected_slot_)->OnSelected();
  }

  inline void __not_in_flash_func(CaptureUISnapshotAndHandleSwitching)() {
    const uint16_t knob_x = ClampKnobU12(KnobVal(Knob::X));
    Switch sw = SwitchVal();
    const bool pulse2_high_now = Connected(Input::Pulse2) && PulseIn2();

    // Prime the app-level switch and Pulse2 histories from live hardware on
    // the first control snapshot. This avoids turning startup settling into a
    // fake Z down->middle tap or a synthetic Pulse2 rising edge.
    if (!switch_inputs_primed_) {
      switch_candidate_ = sw;
      switch_stable_ = sw;
      switch_stable_count_ = 0;
      pulse2_high_prev_ = pulse2_high_now;
      if (sw == Up) {
        panel_alt_latched_ = true;
      } else if (sw == Middle) {
        panel_alt_latched_ = false;
      }
      switch_inputs_primed_ = true;
    }

    Switch prev_stable = switch_stable_;
    if (sw != switch_candidate_) {
      switch_candidate_ = sw;
      switch_stable_count_ = 0;
    } else if (switch_candidate_ != switch_stable_) {
      if (switch_stable_count_ < kSwitchDebounceTicks) {
        ++switch_stable_count_;
      }
      if (switch_stable_count_ >= kSwitchDebounceTicks) {
        switch_stable_ = switch_candidate_;
        switch_stable_count_ = 0;
      }
    } else {
      switch_stable_count_ = 0;
    }
    sw = switch_stable_;

    const bool entered_down = (sw == Down) && (prev_stable != Down);
    const bool left_down = z_switch_hold_active_ && (sw != Down);
    if (entered_down) {
      // A fresh Z-down gesture starts with one pending slot advance. Moving X
      // far enough while held converts that gesture into clock setup instead.
      z_switch_hold_active_ = true;
      z_switch_slot_armed_ = true;
      z_switch_clock_edit_active_ = false;
      z_switch_down_knob_x_ = knob_x;
    }
    if (z_switch_hold_active_ && sw == Down) {
      int32_t knob_delta = int32_t(knob_x) - int32_t(z_switch_down_knob_x_);
      if (knob_delta < 0) knob_delta = -knob_delta;
      if (knob_delta >= int32_t(kZSwitchClockConfigDeadband)) {
        z_switch_slot_armed_ = false;
        z_switch_clock_edit_active_ = true;
      }
    }

    const bool pulse2_high = pulse2_high_now;
    const bool pulse2_rising = pulse2_high && !pulse2_high_prev_;
    pulse2_high_prev_ = pulse2_high;
    // Keep Pulse2 slot switching masked for the entire Z-down gesture,
    // including the debounced release tick that resolves the pending slot tap.
    const bool pulse2_slot_switch_masked = z_switch_hold_active_;

    if (sw == Up) {
      panel_alt_latched_ = true;
    } else if (sw == Middle) {
      panel_alt_latched_ = false;
    }

    if (left_down) {
      if ((sw == Middle) && z_switch_slot_armed_) {
        // Slot changes are hard cuts. This removes the extra render of the
        // previous engine from the audio callback so switching costs no more
        // than normal steady-state rendering.
        AdvanceSelectedSlot();
      }
      z_switch_hold_active_ = false;
      z_switch_slot_armed_ = false;
      z_switch_clock_edit_active_ = false;
    } else if (pulse2_rising && !pulse2_slot_switch_masked) {
      // Slot changes are hard cuts. This removes the extra render of the
      // previous engine from the audio callback so switching costs no more than
      // normal steady-state rendering.
      AdvanceSelectedSlot();
    }

    UISnapshot ui{};
    ui.knob_main = ClampKnobU12(KnobVal(Knob::Main));
    ui.knob_x = knob_x;
    ui.knob_y = ClampKnobU12(KnobVal(Knob::Y));

    ui.cv1 = int16_t(CVIn1());
    ui.cv2 = int16_t(CVIn2());
    ui.audio1 = int16_t(AudioIn1());
    ui.audio2 = int16_t(AudioIn2());

    ui.audio1_connected = Connected(Input::Audio1);
    ui.audio2_connected = Connected(Input::Audio2);
    ui.cv2_connected = Connected(Input::CV2);
    ui.pulse1_connected = Connected(Input::Pulse1);
    ui.pulse1_high = PulseIn1();

    ui.selected_slot = selected_slot_;
    ui.panel_alt_latched = panel_alt_latched_;

    __dmb();
    uint32_t ui_read_index = published_ui_snapshot_index_;
    uint32_t ui_write_index = ui_read_index ^ 1U;
    ui_snapshots_[ui_write_index] = ui;
    __dmb();
    published_ui_snapshot_index_ = ui_write_index;
  }

  inline void __not_in_flash_func(UpdateSlotLEDs)(const ControlFrame& frame) {
    if (frame.global.note_on_counter != seen_note_on_counter_) {
      seen_note_on_counter_ = frame.global.note_on_counter;
      note_flash_samples_remaining_ = int(kNoteFlashOffSamples);
    }

    bool flash_off = note_flash_samples_remaining_ > 0;
    for (uint32_t i = 0; i < 6; ++i) {
      bool selected = (i == frame.global.selected_slot);
      LedOn(i, selected && !flash_off);
    }
  }

  // Applies MIDI-driven panel outputs at control rate so the audio callback
  // only renders engine audio and avoids extra per-sample GPIO/CV work.
  inline void __not_in_flash_func(UpdateMIDIOutputs)(const GlobalControlFrame& global) {
    if (global.last_midi_note != last_cv_note_sent_) {
      CVOut1MIDINote(global.last_midi_note);
      last_cv_note_sent_ = global.last_midi_note;
    }

    if (global.midi_cc74_value != last_cc74_sent_) {
      CVOut2(MapCC74ToCV2Code(global.midi_cc74_value));
      last_cc74_sent_ = global.midi_cc74_value;
    }

    const uint8_t pulse1_gate = global.midi_note_active ? 1U : 0U;
    if (pulse1_gate != last_pulse1_gate_sent_) {
      PulseOut1(global.midi_note_active);
      last_pulse1_gate_sent_ = pulse1_gate;
    }
  }

  // Drives PulseOut2 as a clock output. In MIDI clock mode, forwards 0xF8
  // ticks at the configured division. In internal mode, generates pulses at
  // the configured BPM. Configuration is set by holding Z down + X knob.
  inline void __not_in_flash_func(UpdateClockOutput)(const GlobalControlFrame& global) {
    const uint32_t tick_count = global.midi_clock_tick_count;
    const bool new_ticks = (tick_count != last_clock_tick_seen_);
    const bool midi_clock_active = (clock_inactive_counter_ < kClockTimeoutTicks);

    // Configuration mode starts only after X has moved far enough to claim the
    // gesture, so pressing Z alone leaves the previous clock setting intact.
    if ((switch_stable_ == Down) && z_switch_clock_edit_active_) {
      uint16_t knob_x = ClampKnobU12(KnobVal(Knob::X));
      if (midi_clock_active) {
        clock_division_ticks_ = kClockDivisions[ClockDivisionIndexFromKnobX(knob_x)];
      } else {
        internal_clock_period_ = InternalClockPeriodFromKnobX(knob_x);
      }
    }

    bool fire_pulse = false;

    if (new_ticks) {
      uint32_t incoming = tick_count - last_clock_tick_seen_;
      last_clock_tick_seen_ = tick_count;
      clock_inactive_counter_ = 0;

      midi_clock_div_counter_ += incoming;
      if (midi_clock_div_counter_ >= clock_division_ticks_) {
        midi_clock_div_counter_ = 0;
        fire_pulse = true;
      }
    } else {
      if (clock_inactive_counter_ < kClockTimeoutTicks) {
        ++clock_inactive_counter_;
      }
    }

    // Internal clock when MIDI clock is absent.
    if (!midi_clock_active && !new_ticks) {
      if (internal_clock_counter_ == 0) {
        internal_clock_counter_ = internal_clock_period_;
        fire_pulse = true;
      }
      --internal_clock_counter_;
    }

    if (fire_pulse) {
      pulse2_width_counter_ = kPulseWidthTicks;
    }
    if (pulse2_width_counter_ > 0) {
      --pulse2_width_counter_;
    }
    PulseOut2(pulse2_width_counter_ > 0);
  }

  virtual void __not_in_flash_func(ProcessSample)() override {
    if (!core1_started_) {
      core1_started_ = true;
      multicore_launch_core1(Core1Entry);
    }

    if (++control_counter_ >= int(kControlDivisor)) {
      control_counter_ = 0;
      CaptureUISnapshotAndHandleSwitching();

      uint32_t read_index = published_frame_index_;
      __dmb();
      const ControlFrame& frame = control_frames_[read_index];
      UpdateSlotLEDs(frame);
      UpdateMIDIOutputs(frame.global);
      UpdateClockOutput(frame.global);
    }

    if (note_flash_samples_remaining_ > 0) {
      --note_flash_samples_remaining_;
    }

    uint32_t read_index = published_frame_index_;
    __dmb();
    const ControlFrame& frame = control_frames_[read_index];

    int32_t new_out1 = 0;
    int32_t new_out2 = 0;
    registry_.Get(frame.global.selected_slot)->RenderSample(frame.engine, new_out1, new_out2);

    int32_t mixed_out1 = new_out1;
    int32_t mixed_out2 = new_out2;
    int32_t target_vca_gain_q12 = int32_t(frame.global.vca_gain_q12);
    smoothed_vca_gain_q12_ = SmoothToward(smoothed_vca_gain_q12_, target_vca_gain_q12, kVCAGainSmoothShift);

    int32_t out1 = int32_t((int64_t(mixed_out1) * smoothed_vca_gain_q12_) >> 12);
    int32_t out2 = int32_t((int64_t(mixed_out2) * smoothed_vca_gain_q12_) >> 12);

    if (out1 > 2047) out1 = 2047;
    if (out1 < -2048) out1 = -2048;
    if (out2 > 2047) out2 = 2047;
    if (out2 < -2048) out2 = -2048;

    AudioOut1(int16_t(out1));
    AudioOut2(int16_t(out2));
  }

 private:
  static MTWSApp* instance_;

  SineLUT lut_;
  EngineRegistry registry_;
  MIDIWorker midi_worker_;

  volatile uint32_t published_ui_snapshot_index_;
  UISnapshot ui_snapshots_[2];
  volatile uint32_t published_frame_index_;
  ControlFrame control_frames_[2];

  int control_counter_;
  Switch switch_candidate_;
  Switch switch_stable_;
  uint8_t switch_stable_count_;
  bool switch_inputs_primed_;
  bool pulse2_high_prev_;
  bool panel_alt_latched_;
  uint8_t selected_slot_;
  bool z_switch_hold_active_;
  bool z_switch_slot_armed_;
  bool z_switch_clock_edit_active_;
  uint16_t z_switch_down_knob_x_;

  uint32_t seen_note_on_counter_;
  int note_flash_samples_remaining_;
  uint8_t last_cv_note_sent_;
  uint8_t last_cc74_sent_;
  uint8_t last_pulse1_gate_sent_;
  int32_t smoothed_vca_gain_q12_;

  bool core1_started_;

  // Clock output state.
  uint32_t last_clock_tick_seen_;
  uint32_t clock_inactive_counter_;
  uint32_t clock_division_ticks_;
  uint32_t midi_clock_div_counter_;
  uint32_t internal_clock_period_;
  uint32_t internal_clock_counter_;
  uint32_t pulse2_width_counter_;
};

MTWSApp* MTWSApp::instance_ = nullptr;

}  // namespace mtws

int main() {
  
  sleep_ms(10);
  

  // Keep the large double-buffered control frames out of the main stack.
  #ifdef __EMSCRIPTEN__
    auto& app = *(new mtws::MTWSApp);
#else
    static mtws::MTWSApp app;
#endif
  app.Run();

    return 0;
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: core/control_router.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/core/control_router.h"

namespace mtws {

namespace {
constexpr uint32_t core_control_router__kBasePhaseInc10Hz = 894785U;  // 10 * 2^32 / 48k
constexpr uint32_t core_control_router__kMaxPhaseInc10kHz = 894784853U;  // 10000 * 2^32 / 48k
constexpr uint32_t core_control_router__kMaxU12 = 4095U;
constexpr uint32_t core_control_router__kUnityQ12 = 4096U;
constexpr int32_t core_control_router__kPitchCVScaleNumerator = 6;
constexpr int32_t core_control_router__kPitchCVScaleDenominator = 5;
// ComputerCard audio/CV signals span approximately +/-6 V over -2048..2047.
// The modulation and VCA paths should reach full scale by +5 V, so use the
// nearest signed input code for 2047 * 5 / 6 as the practical patch range.
constexpr int32_t core_control_router__kFiveVoltInputCode = 1706;

// 2^(x) for x in [0,1] on 1/128 grid, Q16 format.
constexpr uint32_t core_control_router__kExp2Q16[129] = {
     65536,  65892,  66250,  66609,  66971,  67335,  67700,  68068,  68438,  68809,  69183,  69558,  69936,  70316,  70698,  71082,
     71468,  71856,  72246,  72638,  73032,  73429,  73828,  74229,  74632,  75037,  75444,  75854,  76266,  76680,  77096,  77515,
     77936,  78359,  78785,  79212,  79642,  80075,  80510,  80947,  81386,  81828,  82273,  82719,  83169,  83620,  84074,  84531,
     84990,  85451,  85915,  86382,  86851,  87322,  87796,  88273,  88752,  89234,  89719,  90206,  90696,  91188,  91684,  92181,
     92682,  93185,  93691,  94200,  94711,  95226,  95743,  96263,  96785,  97311,  97839,  98370,  98905,  99442,  99982, 100524,
    101070, 101619, 102171, 102726, 103283, 103844, 104408, 104975, 105545, 106118, 106694, 107274, 107856, 108442, 109031, 109623,
    110218, 110816, 111418, 112023, 112631, 113243, 113858, 114476, 115098, 115723, 116351, 116983, 117618, 118257, 118899, 119544,
    120194, 120846, 121502, 122162, 122825, 123492, 124163, 124837, 125515, 126197, 126882, 127571, 128263, 128960, 129660, 130364,
    131072,
};

// 2^(n/12) for n=0..11 in Q16.
constexpr uint32_t core_control_router__kSemitoneQ16[12] = {
    65536, 69433, 73561, 77936, 82575, 87499, 92729, 98289, 104202, 110496, 117202, 124354,
};

inline uint16_t core_control_router__ClampU12(int32_t v) {
  if (v < 0) return 0;
  if (v > int32_t(core_control_router__kMaxU12)) return core_control_router__kMaxU12;
  return uint16_t(v);
}

// Converts the raw CV1 board code into the pitch-code delta used by Main.
// The card exposes about 12 V over the full CV input span, while the pitch
// control covers 10 octaves over the same 12-bit code range, so we scale the
// raw delta by 6/5. This makes 1 V land on 1 octave instead of the current
// 10-semitone response. A float slope or per-board calibration would be more
// flexible, but this integer ratio is cheaper and keeps the control path simple.
constexpr int32_t core_control_router__MapPitchCVInputToPitchCodeDelta(int32_t input_code) {
  if (input_code >= 0) {
    return (input_code * core_control_router__kPitchCVScaleNumerator + (core_control_router__kPitchCVScaleDenominator / 2)) /
           core_control_router__kPitchCVScaleDenominator;
  }
  return -(((-input_code) * core_control_router__kPitchCVScaleNumerator + (core_control_router__kPitchCVScaleDenominator / 2)) /
           core_control_router__kPitchCVScaleDenominator);
}

static_assert(core_control_router__MapPitchCVInputToPitchCodeDelta(0) == 0, "Pitch CV zero should stay centered.");
static_assert(core_control_router__MapPitchCVInputToPitchCodeDelta(1706) == 2047, "Positive pitch CV scale drifted.");
static_assert(core_control_router__MapPitchCVInputToPitchCodeDelta(-1706) == -2047, "Negative pitch CV scale drifted.");

// Clamps one bipolar board-domain input code into the intended -5 V..+5 V
// modulation range so hotter sources saturate instead of overdriving the macro.
inline int32_t core_control_router__ClampBipolarFiveVoltInput(int32_t input_code) {
  if (input_code < -core_control_router__kFiveVoltInputCode) return -core_control_router__kFiveVoltInputCode;
  if (input_code > core_control_router__kFiveVoltInputCode) return core_control_router__kFiveVoltInputCode;
  return input_code;
}

// Maps a bipolar -5 V..+5 V input code into the unsigned macro domain.
// Endpoints are -5 V -> 0, 0 V -> ~2048, +5 V -> 4095.
inline uint16_t core_control_router__MapBipolarFiveVoltInputToU12(int32_t input_code) {
  const uint32_t shifted_code = uint32_t(core_control_router__ClampBipolarFiveVoltInput(input_code) + core_control_router__kFiveVoltInputCode);
  return uint16_t((shifted_code * core_control_router__kMaxU12 + uint32_t(core_control_router__kFiveVoltInputCode)) / (2U * uint32_t(core_control_router__kFiveVoltInputCode)));
}

// Applies a 0..4095 attenuation amount to a 0..4095 source and rounds to the
// nearest output code so full-scale attenuation preserves full-scale inputs.
inline uint16_t core_control_router__ApplyU12Attenuation(uint16_t source_u12, uint16_t amount_u12) {
  return uint16_t((uint32_t(source_u12) * uint32_t(amount_u12) + (core_control_router__kMaxU12 / 2U)) / core_control_router__kMaxU12);
}

// Maps a unipolar 0..+5 V control input into Q12 gain for the global VCA.
// Inputs at or below 0 V keep the VCA closed; +5 V and above reach unity gain.
inline uint16_t core_control_router__MapPositiveFiveVoltInputToQ12(int32_t input_code) {
  if (input_code < 0) input_code = 0;
  if (input_code > core_control_router__kFiveVoltInputCode) input_code = core_control_router__kFiveVoltInputCode;
  return uint16_t((uint32_t(input_code) * core_control_router__kUnityQ12 + (core_control_router__kFiveVoltInputCode / 2)) / core_control_router__kFiveVoltInputCode);
}

}  // namespace

uint32_t ControlRouter::BasePhaseIncrementFromPitchCode(uint32_t pitch_code) {
  if (pitch_code > 4095U) pitch_code = 4095U;

  uint32_t pos = (pitch_code * 5122U) >> 12;  // 10 octaves, 512 steps/oct
  if (pos > 5120U) pos = 5120U;

  uint32_t octave_int = pos >> 9;
  uint32_t sub = pos & 0x1FFU;

  uint32_t inc = core_control_router__kBasePhaseInc10Hz << octave_int;

  uint32_t idx = sub >> 2;
  uint32_t frac = sub & 0x3U;
  uint32_t m1 = core_control_router__kExp2Q16[idx];
  uint32_t m2 = core_control_router__kExp2Q16[idx + 1U];
  uint32_t mult = m1 + (((m2 - m1) * frac) >> 2);

  return uint32_t((uint64_t(inc) * mult) >> 16);
}

uint32_t ControlRouter::ApplySemitoneToPhaseInc(uint32_t base_inc, int semitone) {
  if (base_inc == 0 || semitone == 0) return base_inc;

  if (semitone > 96) semitone = 96;
  if (semitone < -96) semitone = -96;

  int octave = semitone / 12;
  int rem = semitone % 12;
  if (rem < 0) {
    rem += 12;
    octave -= 1;
  }

  uint64_t scaled = (uint64_t(base_inc) * core_control_router__kSemitoneQ16[rem]) >> 16;

  if (octave > 0) {
    if (octave >= 16) {
      return 0x7FFFFFFFU;
    }
    scaled <<= octave;
  } else if (octave < 0) {
    int down = -octave;
    if (down >= 63) {
      scaled = 0;
    } else {
      scaled >>= down;
    }
  }

  if (scaled > 0x7FFFFFFFULL) return 0x7FFFFFFFU;
  return uint32_t(scaled);
}

GlobalControlFrame ControlRouter::BuildGlobalFrame(const UISnapshot& ui, const MidiState& midi) {
  GlobalControlFrame out{};

  out.selected_slot = (ui.selected_slot < kNumOscillatorSlots) ? ui.selected_slot : 0;

  int32_t pitch_local = int32_t(ui.knob_main) + core_control_router__MapPitchCVInputToPitchCodeDelta(int32_t(ui.cv1));
  uint16_t pitch_code = core_control_router__ClampU12(pitch_local);

  uint32_t base_inc = BasePhaseIncrementFromPitchCode(pitch_code);
  // Hold the most recent MIDI note through note-off so internal pitch matches
  // the CV1 note output during envelope release instead of snapping back to the
  // panel tuning as soon as the gate drops.
  int semitone = int(midi.last_note) - 60;
  out.pitch_inc = ApplySemitoneToPhaseInc(base_inc, semitone);
  if (out.pitch_inc < core_control_router__kBasePhaseInc10Hz) out.pitch_inc = core_control_router__kBasePhaseInc10Hz;
  if (out.pitch_inc > core_control_router__kMaxPhaseInc10kHz) out.pitch_inc = core_control_router__kMaxPhaseInc10kHz;

  uint16_t x_local = ui.knob_x;
  if (ui.audio1_connected) {
    x_local = core_control_router__ApplyU12Attenuation(core_control_router__MapBipolarFiveVoltInputToU12(ui.audio1), ui.knob_x);
  }

  uint16_t y_local = ui.knob_y;
  if (ui.audio2_connected) {
    y_local = core_control_router__ApplyU12Attenuation(core_control_router__MapBipolarFiveVoltInputToU12(ui.audio2), ui.knob_y);
  }

  out.macro_x = x_local;
  out.macro_y = y_local;

  out.mode_alt = ui.pulse1_connected ? ui.pulse1_high : ui.panel_alt_latched;

  if (ui.cv2_connected) {
    out.vca_gain_q12 = core_control_router__MapPositiveFiveVoltInputToQ12(ui.cv2);
  } else {
    out.vca_gain_q12 = core_control_router__kUnityQ12;
  }

  out.midi_note_active = midi.note_active;
  out.current_midi_note = midi.current_note;
  out.last_midi_note = midi.last_note;
  out.midi_cc74_value = midi.cc74_value;
  out.note_on_counter = midi.note_on_counter;
  out.midi_clock_tick_count = midi.clock_tick_count;

  return out;
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: core/midi_worker.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/core/midi_worker.h"

/* stripped tusb include */

namespace mtws {

namespace {

constexpr uint32_t core_midi_worker__kMaxMIDIPollBytes = 64U;

// Returns the byte length of one short MIDI message including the status byte.
// SysEx and unknown system messages fall back to 1 so the caller can skip
// forward until the next status byte without building a full general parser.
inline uint32_t core_midi_worker__MIDIMessageLength(uint8_t status) {
  switch (status & 0xF0U) {
    case 0x80:
    case 0x90:
    case 0xA0:
    case 0xB0:
    case 0xE0:
      return 3U;

    case 0xC0:
    case 0xD0:
      return 2U;

    case 0xF0:
      switch (status) {
        case 0xF1:
        case 0xF3:
          return 2U;

        case 0xF2:
          return 3U;

        default:
          return 1U;
      }

    default:
      return 1U;
  }
}

}  // namespace

MIDIWorker::MIDIWorker() {
  state_.note_active = false;
  state_.current_note = 60;
  state_.last_note = 60;
  state_.cc74_value = 0;
  state_.note_on_counter = 0;
  state_.clock_tick_count = 0;
  pending_bytes_[0] = 0;
  pending_bytes_[1] = 0;
  pending_bytes_[2] = 0;
  pending_count_ = 0;
}

void MIDIWorker::Init() {
  tusb_init();
}

void MIDIWorker::HandleShortMessage(uint8_t status, uint8_t data1, uint8_t data2, MidiState& next_state) const {
  if ((status & 0x80U) == 0U) return;

  // System realtime messages (0xF8-0xFF) carry no channel and must be
  // handled before the channel filter below.
  if (status == 0xF8U) {
    next_state.clock_tick_count++;
    return;
  }

  uint8_t status_nibble = status & 0xF0U;
  uint8_t channel = status & 0x0FU;

  // Channel-1 strict. MIDI channel 1 is zero-based channel 0.
  if (channel != 0U) return;

  switch (status_nibble) {
    case 0x90: {  // note on
      uint8_t note = data1 & 0x7FU;
      uint8_t velocity = data2 & 0x7FU;
      if (velocity == 0U) {
        if (next_state.note_active && note == next_state.current_note) {
          next_state.note_active = false;
        }
      } else {
        next_state.note_active = true;
        next_state.current_note = note;
        next_state.last_note = note;
        next_state.note_on_counter++;
      }
      break;
    }

    case 0x80: {  // note off
      uint8_t note = data1 & 0x7FU;
      if (next_state.note_active && note == next_state.current_note) {
        next_state.note_active = false;
      }
      break;
    }

    case 0xB0: {  // control change
      uint8_t controller = data1 & 0x7FU;
      if (controller == 74U) {
        next_state.cc74_value = data2 & 0x7FU;
      }
      break;
    }

    default:
      break;
  }
}

uint32_t MIDIWorker::ConsumeMIDIBytes(const uint8_t* bytes, uint32_t count, MidiState& next_state) const {
  uint32_t index = 0;
  while (index < count) {
    uint8_t status = bytes[index];
    if ((status & 0x80U) == 0U) {
      ++index;
      continue;
    }

    const uint32_t message_length = core_midi_worker__MIDIMessageLength(status);
    if (index + message_length > count) {
      break;
    }

    const uint8_t data1 = (message_length > 1U) ? bytes[index + 1U] : 0U;
    const uint8_t data2 = (message_length > 2U) ? bytes[index + 2U] : 0U;
    HandleShortMessage(status, data1, data2, next_state);
    index += message_length;
  }
  return index;
}

void MIDIWorker::Poll() {
  tud_task();

  if (tud_midi_available() == 0U) return;

  MidiState next_state = state_;
  uint8_t buffer[core_midi_worker__kMaxMIDIPollBytes + 3U];
  uint32_t byte_count = pending_count_;
  for (uint32_t i = 0; i < pending_count_; ++i) {
    buffer[i] = pending_bytes_[i];
  }

  // Read at most one chunk per control tick so MIDI traffic cannot stretch the
  // control loop indefinitely. This still batches multiple short messages.
  const uint32_t bytes_read = tud_midi_stream_read(buffer + byte_count, core_midi_worker__kMaxMIDIPollBytes);
  byte_count += bytes_read;

  const uint32_t consumed = ConsumeMIDIBytes(buffer, byte_count, next_state);
  pending_count_ = uint8_t(byte_count - consumed);
  for (uint32_t i = 0; i < pending_count_; ++i) {
    pending_bytes_[i] = buffer[consumed + i];
  }
  state_ = next_state;
}

MidiState MIDIWorker::Snapshot() const {
  return state_;
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/bender_engine.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/bender_engine.h"
#include "pico.h"

namespace mtws {

namespace {
// Converts knob/macros in 0..4095 to a Q12 interpolation range in 0..4096.
// The extra top code point allows an exact full-wet fold mix at maximum.
inline uint32_t engines_bender_engine__U12ToQ12(uint16_t v) {
  if (v >= 4095U) return 4096U;
  return uint32_t(v);
}

// Maps macro X into the Utility-Pair gain domain used before the folder.
// `128` represents unity input gain because the folded input is scaled by `>> 7`.
// The upper bound `2048` was chosen because it matches the original Utility-Pair
// maximum multiplier range (~16x), giving a familiar amount of folding.
// Alternative considered: stop at `1024` (~8x) for a gentler maximum drive.
// CPU vs memory tradeoff: this is one multiply/shift at control rate and avoids
// storing a separate drive LUT for a simple linear mapping.
inline uint16_t FoldDriveQ7FromMacroX(uint16_t macro_x) {
  uint32_t x_q12 = engines_bender_engine__U12ToQ12(macro_x);
  return uint16_t(128U + ((x_q12 * 1920U + 2048U) >> 12));
}

// Maps macro Y into the Utility-Pair crush step domain using the same squared
// response as the reference implementation. `0` means "effectively off" and is
// clamped to `1` inside CrushFunction, while `4095` gives the coarsest quantizer.
// Alternative considered: linear `1..4095`, but the squared curve gives more
// usable low-end travel before the crusher becomes extreme.
// CPU vs memory tradeoff: one control-rate multiply/shift keeps the mapping
// cheap and avoids an extra lookup table.
inline int16_t CrushAmountFromMacroY(uint16_t macro_y) {
  return int16_t((uint32_t(macro_y) * uint32_t(macro_y)) >> 12);
}
}  // namespace

BenderEngine::BenderEngine(SineLUT* lut)
    : lut_(lut),
      phase_(0),
      last_fold_integral_pre_(0),
      last_fold_input_pre_(0),
      last_fold_integral_post_(0),
      last_fold_input_post_(0),
      last_alt_(false) {}

// Resets oscillator phase and both antialiased fold histories.
void BenderEngine::Init() {
  phase_ = 0;
  last_fold_integral_pre_ = 0;
  last_fold_input_pre_ = 0;
  last_fold_integral_post_ = 0;
  last_fold_input_post_ = 0;
  last_alt_ = false;
}

void BenderEngine::OnSelected() {
  // Keep phase continuity.
}

// Converts the shared macro frame into the lighter-weight bender control frame.
// `X` controls both the fold drive and the dry/wet fold mix, while `Y` controls
// the Utility-Pair-style crush amount.
void BenderEngine::ControlTick(const GlobalControlFrame& global, EngineControlFrame& frame) {
  BenderControlFrame& out = frame.bender;
  out.phase_increment = global.pitch_inc;
  out.fold_drive_q7 = FoldDriveQ7FromMacroX(global.macro_x);
  out.fold_mix_q12 = uint16_t(engines_bender_engine__U12ToQ12(global.macro_x));
  out.crush_amount = CrushAmountFromMacroY(global.macro_y);
  out.alt = global.mode_alt;
}

int32_t __not_in_flash_func(BenderEngine::Clamp12)(int32_t v) {
  if (v > 2047) return 2047;
  if (v < -2048) return -2048;
  return v;
}

// Wraps a signed value into the range 0..8191 using bitmask instead of modulo.
// Equivalent to ((v % 8192) + 8192) % 8192 but avoids two hardware divider
// calls (~16 cycles each on RP2040) by exploiting the power-of-2 period.
static inline int32_t WrapMod8192(int32_t v) {
  return v & 0x1FFF;
}

// Utility-Pair fold transfer function. Values within +/-2048 pass through,
// while larger magnitudes are reflected every 4096 samples.
int32_t __not_in_flash_func(BenderEngine::FoldFunction)(int32_t x) {
  x = WrapMod8192(x + 2048);

  if (x < 4096) {
    return x - 2048;
  }
  return (8191 - x) - 2048;
}

// Antiderivative of FoldFunction used for the derivative antialiasing step.
// This follows the Utility-Pair implementation directly so the folded sine uses
// the same transfer curve and the same antialiasing strategy.
int32_t __not_in_flash_func(BenderEngine::FoldIntegral)(int32_t x) {
  x = WrapMod8192(x + 2048);
  int32_t x2 = x * 2;
  if (x < 4096) {
    return ((x2 + 1) * (x2 - 8191)) >> 3;
  }
  return -((x2 - 8191) * (x2 - 16383)) >> 3;
}

// Differentiates successive fold integrals to suppress aliasing at fold corners.
// If the input sample did not move, the exact fold function is cheaper and
// produces the same result.
int32_t __not_in_flash_func(BenderEngine::AntiAliasedFold)(int32_t x, int32_t& last_integral, int32_t& last_input) {
  int32_t ret = 0;
  if (x == last_input) {
    ret = FoldFunction(x);
  } else {
    int32_t integral = FoldIntegral(x);
    ret = (integral - last_integral) / (x - last_input);
    last_input = x;
    last_integral = integral;
  }
  return Clamp12(ret);
}

// Utility-Pair bitcrusher transfer. `amount` is the quantizer step size in the
// signed 12-bit sample domain, so larger values produce fewer output levels.
// Uses floored division to avoid the two modulo operations in the original
// Utility-Pair implementation, saving ~32 cycles per call on RP2040.
int32_t __not_in_flash_func(BenderEngine::CrushFunction)(int32_t x, int32_t amount) {
  if (amount < 1) amount = 1;
  x += -2047 + (amount >> 1);
  int32_t q = x / amount;
  if (x < 0 && (q * amount != x)) q -= 1;
  x = q * amount + 2047;
  if (x < -2047) x = -2047;
  if (x > 2047) x = 2047;
  return x;
}

// Linear interpolation where `t_q12 = 0` returns dry and `4096` returns wet.
int32_t __not_in_flash_func(BenderEngine::LerpQ12)(int32_t a, int32_t b, uint32_t t_q12) {
  if (t_q12 > 4096U) t_q12 = 4096U;
  return a + int32_t((int64_t(b - a) * int32_t(t_q12)) >> 12);
}

// Renders one sine sample and routes it through the selected processing order.
// Normal mode keeps the current A/B comparison patch:
// - Out1: dry/wet sine -> fold
// - Out2: sine -> crusher
// Alt mode reorders the nonlinear stages:
// - Out1: fold -> crusher
// - Out2: crusher -> fold
void __not_in_flash_func(BenderEngine::RenderSample)(const EngineControlFrame& frame, int32_t& out1, int32_t& out2) {
  const BenderControlFrame& in = frame.bender;

  if (in.alt != last_alt_) {
    last_fold_integral_pre_ = 0;
    last_fold_input_pre_ = 0;
    last_fold_integral_post_ = 0;
    last_fold_input_post_ = 0;
    last_alt_ = in.alt;
  }

  phase_ += in.phase_increment;

  int32_t sine = lut_->LookupLinear(phase_);
  int32_t folded_input = int32_t((int64_t(sine) * in.fold_drive_q7) >> 7);
  int32_t folded = AntiAliasedFold(folded_input, last_fold_integral_pre_, last_fold_input_pre_);
  int32_t crushed = CrushFunction(sine, in.crush_amount);

  if (!in.alt) {
    out1 = Clamp12(LerpQ12(sine, folded, in.fold_mix_q12));
    out2 = crushed;
    return;
  }

  int32_t fold_then_crush = CrushFunction(folded, in.crush_amount);
  int32_t crush_then_fold_input = int32_t((int64_t(crushed) * in.fold_drive_q7) >> 7);
  int32_t crush_then_fold = AntiAliasedFold(crush_then_fold_input, last_fold_integral_post_, last_fold_input_post_);

  out1 = fold_then_crush;
  out2 = crush_then_fold;
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/cumulus_engine.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/cumulus_engine.h"
#include "pico.h"

namespace mtws {

// Creates the additive engine and initializes the per-partial phase and
// smoothing state used by both control-rate and audio-rate code.
CumulusEngine::CumulusEngine(SineLUT* lut) : lut_(lut) {
  Init();
}

// Resets all partial phases and smoothing memory to the default harmonic stack.
void CumulusEngine::Init() {
  for (int i = 0; i < kNumCumulusVoices; ++i) {
    phases_[i] = 0;
    smoothed_ratio_q16_[i] = HarmonicRatioQ16(i);
    smoothed_gain_q12_[i] = int32_t(kUnityQ12 / uint32_t(i + 1));
  }
}

void CumulusEngine::OnSelected() {
  // Keep phase continuity to avoid clicks when re-entering this engine.
}

// Broad centroid weighting where gain falls as 1 / (1 + distance) across the
// partial index domain.
int32_t CumulusEngine::CentroidBaseGainQ12(int partial_index, uint32_t centroid_q12) {
  uint32_t pos_q12 = uint32_t(partial_index) << 12;
  uint32_t d_q12 = (pos_q12 >= centroid_q12) ? (pos_q12 - centroid_q12) : (centroid_q12 - pos_q12);
  uint32_t denom_q12 = kUnityQ12 + d_q12;
  uint64_t numer = uint64_t(kUnityQ12) * kUnityQ12;
  return int32_t((numer + (denom_q12 >> 1)) / denom_q12);
}

// Narrow centroid weighting where only the nearest neighboring partials remain
// active, giving a pointier spectrum at lower Y positions.
int32_t CumulusEngine::CentroidNarrowGainQ12(int partial_index, uint32_t centroid_q12) {
  uint32_t pos_q12 = uint32_t(partial_index) << 12;
  uint32_t d_q12 = (pos_q12 >= centroid_q12) ? (pos_q12 - centroid_q12) : (centroid_q12 - pos_q12);
  if (d_q12 >= kUnityQ12) return 0;
  return int32_t(kUnityQ12 - d_q12);
}

// Fixed-point linear interpolation helper where `t_q12 = 0` returns `a` and
// `t_q12 = 4096` returns `b`.
int32_t CumulusEngine::LerpQ12(int32_t a, int32_t b, uint32_t t_q12) {
  if (t_q12 > kUnityQ12) t_q12 = kUnityQ12;
  return int32_t((int64_t(a) * int32_t(kUnityQ12 - t_q12) + int64_t(b) * int32_t(t_q12)) >> 12);
}

// Integer one-pole smoother used to keep ratio and gain changes free of zipper
// noise without adding per-partial buffers.
int32_t CumulusEngine::SmoothToward(int32_t current, int32_t target, int shift) {
  if (shift <= 0) return target;
  int32_t delta = target - current;
  int32_t step = delta >> shift;
  if (step == 0 && delta != 0) {
    step = (delta > 0) ? 1 : -1;
  }
  return current + step;
}

// Reflect-folds a warped ratio into the legal Q16 ratio range so the alt-mode
// attract/repel motion stays continuous instead of hard-clipping at the edges.
int32_t CumulusEngine::FoldReflectQ16(int32_t x, int32_t lo, int32_t hi) {
  int64_t span = int64_t(hi) - int64_t(lo);
  if (span <= 0) return lo;
  int64_t period = span << 1;
  int64_t t = (int64_t(x) - int64_t(lo)) % period;
  if (t < 0) t += period;
  if (t > span) t = period - t;
  return int32_t(int64_t(lo) + t);
}

// Blends the narrow centroid shape, broad centroid shape, and a flat spectrum
// as Y moves from fully counter-clockwise to fully clockwise.
int32_t CumulusEngine::ShapedCentroidGainQ12(int partial_index, uint32_t centroid_q12, uint32_t knob_y) {
  if (knob_y > 4095U) knob_y = 4095U;

  int32_t g_base = CentroidBaseGainQ12(partial_index, centroid_q12);
  int32_t g_narrow = CentroidNarrowGainQ12(partial_index, centroid_q12);

  if (knob_y <= 2048U) {
    uint32_t t_q12 = knob_y << 1;
    return LerpQ12(g_narrow, g_base, t_q12);
  }

  uint32_t t_q12 = (knob_y - 2048U) << 1;
  if (knob_y >= 4095U) t_q12 = kUnityQ12;
  return LerpQ12(g_base, int32_t(kUnityQ12), t_q12);
}

// Builds one additive control frame. X moves the spectral centroid, Y controls
// shape in normal mode and ratio attract/repel in alt mode, and the control
// path also computes a conservative bus normalization gain for the next block.
void CumulusEngine::ControlTick(const GlobalControlFrame& global, EngineControlFrame& frame) {
  CumulusControlFrame& out = frame.cumulus;

  uint32_t knob_x = global.macro_x;
  uint32_t knob_y = global.macro_y;
  uint32_t base_inc = global.pitch_inc;
  bool alt_mode = global.mode_alt;

  if (knob_x > 4095U) knob_x = 4095U;
  uint32_t centroid_max_q12 = uint32_t(kNumCumulusVoices - 1) << 12;
  uint32_t centroid_q12 = uint32_t((uint64_t(knob_x) * centroid_max_q12 + 2048U) >> 12);
  int32_t centroid_ratio_q16 = int32_t((1U << 16) + (centroid_q12 << 4));

  int32_t max_ratio_q16 = kMaxRatioQ16;

  uint32_t odd_gain_sum_q12 = 0;
  uint32_t even_gain_sum_q12 = 0;
  for (int i = 0; i < kNumCumulusVoices; ++i) {
    int32_t target_ratio_q16 = HarmonicRatioQ16(i);

    if (alt_mode) {
      if (i == 0 && knob_y > 2048U) {
        target_ratio_q16 = HarmonicRatioQ16(0);
      } else {
        if (knob_y < 2048U) {
          uint32_t warp_q12 = (2048U - knob_y) << 1;
          target_ratio_q16 = LerpQ12(target_ratio_q16, centroid_ratio_q16, warp_q12);
        } else if (knob_y > 2048U) {
          uint32_t warp_q12 = (knob_y - 2048U) << 1;
          if (knob_y >= 4095U) warp_q12 = kUnityQ12;
          int32_t repel_ratio_q16 = (target_ratio_q16 << 1) - centroid_ratio_q16;
          target_ratio_q16 = LerpQ12(target_ratio_q16, repel_ratio_q16, warp_q12);
        }

        target_ratio_q16 = FoldReflectQ16(target_ratio_q16, HarmonicRatioQ16(0), max_ratio_q16);
      }

      if (target_ratio_q16 < kMinRatioQ16) target_ratio_q16 = kMinRatioQ16;
      if (target_ratio_q16 > max_ratio_q16) target_ratio_q16 = max_ratio_q16;
    }

    if (alt_mode) {
      smoothed_ratio_q16_[i] = SmoothToward(smoothed_ratio_q16_[i], target_ratio_q16, kRatioSmoothShift);
      if (smoothed_ratio_q16_[i] < kMinRatioQ16) smoothed_ratio_q16_[i] = kMinRatioQ16;
      if (smoothed_ratio_q16_[i] > max_ratio_q16) smoothed_ratio_q16_[i] = max_ratio_q16;
    } else {
      smoothed_ratio_q16_[i] = target_ratio_q16;
    }

    uint64_t voice_inc_64 = (uint64_t(base_inc) * uint64_t(uint32_t(smoothed_ratio_q16_[i]))) >> 16;
    bool voice_above_guard = (voice_inc_64 > uint64_t(kPartialMaxPhaseInc));
    if (voice_inc_64 > uint64_t(kNyquistPhaseInc)) voice_inc_64 = uint64_t(kNyquistPhaseInc);
    out.voice_phase_increment[i] = uint32_t(voice_inc_64);

    if (voice_above_guard) {
      // Hard mute above cutoff for diagnostic clarity.
      smoothed_gain_q12_[i] = 0;
      out.voice_gain_q12[i] = 0;
    } else {
      int32_t target_gain_q12 = ShapedCentroidGainQ12(i, centroid_q12, knob_y);
      if (target_gain_q12 < 0) target_gain_q12 = 0;
      if (target_gain_q12 > int32_t(kUnityQ12)) target_gain_q12 = int32_t(kUnityQ12);

      smoothed_gain_q12_[i] = SmoothToward(smoothed_gain_q12_[i], target_gain_q12, kGainSmoothShift);
      if (smoothed_gain_q12_[i] < 0) smoothed_gain_q12_[i] = 0;
      if (smoothed_gain_q12_[i] > int32_t(kUnityQ12)) smoothed_gain_q12_[i] = int32_t(kUnityQ12);

      int32_t scaled_gain_q12 =
          int32_t((int64_t(smoothed_gain_q12_[i]) * int32_t(kUniformPartialGainQ12) + 2048) >> 12);
      if (scaled_gain_q12 < 0) scaled_gain_q12 = 0;
      out.voice_gain_q12[i] = scaled_gain_q12;
    }
    uint32_t g_q12 = uint32_t(out.voice_gain_q12[i]);
    if ((i & 1) == 0) {
      odd_gain_sum_q12 += g_q12;
    } else {
      even_gain_sum_q12 += g_q12;
    }
  }

  uint32_t max_bus_gain_sum_q12 = (odd_gain_sum_q12 > even_gain_sum_q12) ? odd_gain_sum_q12 : even_gain_sum_q12;
  if (max_bus_gain_sum_q12 == 0U) {
    out.mix_norm_q12 = int32_t(kCumulusMasterGainQ12);
    return;
  }

  // Conservative peak estimate for one bus:
  // bus_peak ~= (2047 * sum(gains_q12) / 4096) / (1<<kRenderSumShift).
  uint32_t bus_peak_pre_mix = uint32_t((uint64_t(2047U) * max_bus_gain_sum_q12) >> 12);
  bus_peak_pre_mix >>= kRenderSumShift;
  if (bus_peak_pre_mix == 0U) bus_peak_pre_mix = 1U;

  // Max safe Q12 multiplier so post-mix peak stays <= 2047.
  uint32_t safe_mix_norm_q12 =
      uint32_t(((uint64_t(2047U) << 12) + (bus_peak_pre_mix >> 1)) / uint64_t(bus_peak_pre_mix));
  if (safe_mix_norm_q12 > kCumulusMasterGainQ12) safe_mix_norm_q12 = kCumulusMasterGainQ12;
  out.mix_norm_q12 = int32_t(safe_mix_norm_q12);
}

// Renders the 16 sine partials, routes even and odd indices to separate
// stereo buses, then applies the per-frame normalization gain and 12-bit clamp.
void __not_in_flash_func(CumulusEngine::RenderSample)(const EngineControlFrame& frame, int32_t& out1, int32_t& out2) {
  const CumulusControlFrame& in = frame.cumulus;

  int32_t sum_odd = 0;
  int32_t sum_even = 0;
  for (int i = 0; i < kNumCumulusVoices; ++i) {
    phases_[i] += in.voice_phase_increment[i];
    int32_t s = lut_->LookupLinear(phases_[i]);
    int32_t voice = (s * in.voice_gain_q12[i]) >> 12;
    if ((i & 1) == 0) {
      sum_odd += voice;
    } else {
      sum_even += voice;
    }
  }

  int32_t odd_bus = sum_odd >> kRenderSumShift;
  int32_t even_bus = sum_even >> kRenderSumShift;

  int32_t odd_out = int32_t((int64_t(odd_bus) * in.mix_norm_q12) >> 12);
  int32_t even_out = int32_t((int64_t(even_bus) * in.mix_norm_q12) >> 12);

  if (odd_out > 2047) odd_out = 2047;
  if (odd_out < -2048) odd_out = -2048;
  if (even_out > 2047) even_out = 2047;
  if (even_out < -2048) even_out = -2048;

  out1 = odd_out;
  out2 = even_out;
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/din_sum_engine.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/din_sum_engine.h"
#include "pico.h"

namespace mtws {

namespace {
// Converts knob/macros in 0..4095 to the local Q12 range in 0..4096.
// The extra top code point preserves an exact pure-saw endpoint.
inline uint16_t ToQ12(uint16_t v) {
  return (v >= 4095U) ? 4096U : v;
}

// The shared MTWS control thread publishes one new engine frame every 16
// samples, so the random target interpolation spans exactly 16 audio samples.
constexpr uint8_t kRandomInterpolationSteps = 16U;
// Since the interpolation length is 16 samples, `>> 4` maps the interpolated
// delta back into the native random-value domain.
constexpr uint8_t kRandomInterpolationShift = 4U;
// The low-passed random target is updated once per 16-sample control frame. A
// shift of 2 moves 25% toward the latest random value each update, which keeps
// the smooth branch visibly different from the residual high-passed branch.
// Alternative considered: shift 3 for slower drift, but it reduced the
// liveliness of normal mode too far.
// CPU vs memory tradeoff: one add/subtract/shift at control rate is cheaper
// than maintaining a larger smoothing buffer or a lookup-based response curve.
constexpr uint8_t kFilteredRandomShift = 2U;
// Unity in the local Q12 morph convention.
constexpr uint16_t engines_din_sum_engine__kUnityQ12 = 4096U;
// Half scale in the local Q12 morph convention. This is the largest legal
// deviation range because the bounded morph corridor shrinks symmetrically from
// both endpoints toward the midpoint.
constexpr uint16_t kHalfQ12 = 2048U;
// Alt-mode wrap stickiness spans 1..8 cycles. Low Y holds the same waveform
// family for several cycles, while high Y rerolls almost every cycle.
constexpr uint8_t kAltHoldCyclesMin = 1U;
constexpr uint8_t kAltHoldCyclesMax = 8U;
// A 90-degree phase offset in the native 32-bit phase domain. This keeps Out2
// clearly different at the saw end without causing the strong octave-only mono
// sum of a full 180-degree offset.
constexpr uint32_t kOut2SawPhaseOffset = 0x40000000U;
}  // namespace

// Creates the engine and stores the shared sine LUT dependency.
// Input: pointer to the global LUT owned by the MTWS app.
// Output: engine ready to reset and render.
DinSumEngine::DinSumEngine(SineLUT* lut)
    : lut_(lut),
      random_state_(1U),
      alt_random_state_(0x6d2b79f5U),
      phase_(0U),
      control_random_lp_next_(0),
      control_random_hp_next_(0),
      frame_epoch_counter_(0U),
      active_frame_epoch_(0U),
      random_interp_step_(0U),
      active_alt_mode_(false),
      alt_cycle_is_saw_out1_(false),
      alt_cycle_is_saw_out2_(false),
      alt_cycle_hold_out1_(0U),
      alt_cycle_hold_out2_(0U) {
  Init();
}

// Resets phase, random target state, and the audio-rate interpolation cursor to
// deterministic startup values.
void DinSumEngine::Init() {
  random_state_ = 1U;
  alt_random_state_ = 0x6d2b79f5U;
  phase_ = 0U;
  control_random_lp_next_ = 0;
  control_random_hp_next_ = 0;
  frame_epoch_counter_ = 0U;
  active_frame_epoch_ = 0U;
  random_interp_step_ = 0U;
  active_alt_mode_ = false;
  alt_cycle_is_saw_out1_ = false;
  alt_cycle_is_saw_out2_ = false;
  alt_cycle_hold_out1_ = 0U;
  alt_cycle_hold_out2_ = 0U;
}

void DinSumEngine::OnSelected() {
  // Keep phase continuity and the current random state when switching back in.
}

// Clamps any intermediate sample to the signed 12-bit ComputerCard audio range.
// Input: unconstrained signed sample.
// Output: sample limited to -2048..2047.
int32_t __not_in_flash_func(DinSumEngine::Clamp12)(int32_t v) {
  if (v > 2047) return 2047;
  if (v < -2048) return -2048;
  return v;
}

// Interpolates between two signed samples with a Q12 morph amount.
// Inputs: endpoints `a` and `b`, and `t_q12` in the range 0..4096.
// Output: a point guaranteed to stay inside the closed interval [a, b].
int32_t __not_in_flash_func(DinSumEngine::LerpQ12)(int32_t a, int32_t b, uint16_t t_q12) {
  uint32_t t = t_q12;
  if (t > engines_din_sum_engine__kUnityQ12) t = engines_din_sum_engine__kUnityQ12;
  return int32_t(int64_t(a) + ((int64_t(b) - int64_t(a)) * int64_t(t) >> 12));
}

// Generates a PolyBLEP-corrected saw using a precomputed reciprocal to avoid
// 64-bit divisions at audio rate. See SawsomeEngine for the reciprocal scheme.
int32_t __not_in_flash_func(DinSumEngine::PolyBlepSawQ12)(uint32_t phase, uint32_t phase_inc, uint32_t recip_q24) {
  int32_t saw = int32_t((phase >> 20) & 0x0FFFU) - 2048;
  if (phase_inc == 0U) return saw;

  if (phase < phase_inc) {
    uint32_t t_q12 = uint32_t((uint64_t(phase) * recip_q24) >> 24);
    int32_t x = int32_t(t_q12);
    int32_t corr = x + x - int32_t((int64_t(x) * x) >> 12) - 4096;
    saw -= corr >> 1;
  }

  uint32_t tail = 0xFFFFFFFFU - phase;
  if (tail < phase_inc) {
    uint32_t t_q12 = uint32_t((uint64_t(tail) * recip_q24) >> 24);
    int32_t x = int32_t(t_q12);
    int32_t corr = int32_t((int64_t(x) * x) >> 12);
    saw += corr >> 1;
  }

  return Clamp12(saw);
}

// Advances the control-rate xorshift generator and returns a bipolar 12-bit
// random target suitable for bounded morph modulation.
// Input/output: mutable PRNG state.
// Output: signed value approximately in the range -2048..2047.
int16_t DinSumEngine::Rand12Bipolar(uint32_t& state) {
  state ^= state << 13;
  state ^= state >> 17;
  state ^= state << 5;
  return int16_t(((state >> 20) & 0x0FFFU) - 2048);
}

// Advances the xorshift generator and returns a unipolar 12-bit random value.
// Input/output: mutable PRNG state.
// Output: unsigned value in the range 0..4095 for probability comparisons.
uint16_t DinSumEngine::Rand12Unipolar(uint32_t& state) {
  state ^= state << 13;
  state ^= state >> 17;
  state ^= state << 5;
  return uint16_t((state >> 20) & 0x0FFFU);
}

// Builds one shared-engine control frame. This captures the current phase
// increment and macro values, then advances the low-pass and high-pass random
// targets used for the next 16-sample audio interpolation span.
// X controls the sine-to-saw morph position, while Y controls the random-source
// character in normal mode and the cycle-choice stickiness in alt mode.
void DinSumEngine::ControlTick(const GlobalControlFrame& global, EngineControlFrame& frame) {
  DinSumControlFrame& out = frame.din_sum;

  const uint16_t morph_q12 = ToQ12(global.macro_x);
  const uint16_t coherence_q12 = ToQ12(global.macro_y);
  const int16_t random_lp_prev = control_random_lp_next_;
  const int16_t random_hp_prev = control_random_hp_next_;
  const int16_t random_raw = Rand12Bipolar(random_state_);
  const int16_t random_lp_next = int16_t(
      int32_t(random_lp_prev) + ((int32_t(random_raw) - int32_t(random_lp_prev)) >> kFilteredRandomShift));

  // The high-passed branch is the residual between the raw target and the
  // smoothed branch. Clamping keeps it inside the same nominal bipolar range so
  // the later bounded-corridor math behaves consistently.
  int32_t random_hp_next = int32_t(random_raw) - int32_t(random_lp_next);
  if (random_hp_next < -2048) random_hp_next = -2048;
  if (random_hp_next > 2047) random_hp_next = 2047;

  control_random_lp_next_ = random_lp_next;
  control_random_hp_next_ = int16_t(random_hp_next);
  ++frame_epoch_counter_;

  out.phase_increment = global.pitch_inc;
  out.phase_inc_recip_q24 = (global.pitch_inc > 0) ? uint32_t((1ULL << 36) / global.pitch_inc) : 0U;
  out.morph_q12 = morph_q12;
  out.coherence_q12 = coherence_q12;
  out.random_lp_prev = random_lp_prev;
  out.random_lp_next = random_lp_next;
  out.random_hp_prev = random_hp_prev;
  out.random_hp_next = int16_t(random_hp_next);
  out.alt = global.mode_alt;
  out.frame_epoch = frame_epoch_counter_;
}

// Renders one stereo sample. In normal mode, both outputs choose a bounded
// random interpolation point between the shared sine and their saw targets.
// Out1 uses the local saw, while Out2 uses the same saw evaluated 90 degrees
// later in phase. In alt mode, each output chooses sine or saw for whole cycles
// with the same X-controlled probability but independent rerolls.
void __not_in_flash_func(DinSumEngine::RenderSample)(const EngineControlFrame& frame, int32_t& out1, int32_t& out2) {
  const DinSumControlFrame& in = frame.din_sum;

  if (in.frame_epoch != active_frame_epoch_) {
    active_frame_epoch_ = in.frame_epoch;
    random_interp_step_ = 0U;
  }

  const uint32_t previous_phase = phase_;
  phase_ += in.phase_increment;
  const bool wrapped = phase_ < previous_phase;

  const int32_t sine = lut_->LookupLinear(phase_);
  const int32_t saw_up = PolyBlepSawQ12(phase_, in.phase_increment, in.phase_inc_recip_q24);
  const int32_t saw_up_shifted = PolyBlepSawQ12(phase_ + kOut2SawPhaseOffset, in.phase_increment, in.phase_inc_recip_q24);

  if (in.alt) {
    // Low Y increases hold length so waveform-family decisions persist across
    // several wraps. High Y reduces the hold toward one cycle so alt mode
    // flickers more aggressively.
    const uint8_t hold_cycles = uint8_t(
        kAltHoldCyclesMax -
        ((uint32_t(in.coherence_q12) * uint32_t(kAltHoldCyclesMax - kAltHoldCyclesMin) + 2048U) >> 12));

    // Entering alt mode always starts fresh. On later wraps, reroll only when
    // the current choice has been held for the requested number of cycles.
    if (!active_alt_mode_) {
      active_alt_mode_ = true;
      alt_cycle_is_saw_out1_ = Rand12Unipolar(alt_random_state_) < in.morph_q12;
      alt_cycle_is_saw_out2_ = Rand12Unipolar(alt_random_state_) < in.morph_q12;
      alt_cycle_hold_out1_ = 0U;
      alt_cycle_hold_out2_ = 0U;
    } else if (wrapped) {
      if (++alt_cycle_hold_out1_ >= hold_cycles) {
        alt_cycle_is_saw_out1_ = Rand12Unipolar(alt_random_state_) < in.morph_q12;
        alt_cycle_hold_out1_ = 0U;
      }
      if (++alt_cycle_hold_out2_ >= hold_cycles) {
        alt_cycle_is_saw_out2_ = Rand12Unipolar(alt_random_state_) < in.morph_q12;
        alt_cycle_hold_out2_ = 0U;
      }
    }

    out1 = alt_cycle_is_saw_out1_ ? saw_up : sine;
    out2 = alt_cycle_is_saw_out2_ ? saw_up_shifted : sine;
    return;
  }

  active_alt_mode_ = false;
  alt_cycle_hold_out1_ = 0U;
  alt_cycle_hold_out2_ = 0U;

  // The interpolated random value is audio-rate smooth but only refreshed once
  // per 16-sample control block. The `>> 4` shift matches the block length
  // exactly. Alternative considered: stepped sample-and-hold, but the
  // interpolated form preserves pitch better and avoids obvious zippering.
  const int32_t random_lp_interp = int32_t(in.random_lp_prev) +
      (((int32_t(in.random_lp_next) - int32_t(in.random_lp_prev)) * int32_t(random_interp_step_)) >>
       kRandomInterpolationShift);
  const int32_t random_hp_interp = int32_t(in.random_hp_prev) +
      (((int32_t(in.random_hp_next) - int32_t(in.random_hp_prev)) * int32_t(random_interp_step_)) >>
       kRandomInterpolationShift);
  if (random_interp_step_ < (kRandomInterpolationSteps - 1U)) {
    ++random_interp_step_;
  }

  // Y crossfades between smooth and nervous random sources. Out1 follows the
  // knob directly, while Out2 uses the inverse crossfade so the outputs swap
  // character across the sweep and meet toward the midpoint.
  const int32_t random_interp_out1 = LerpQ12(random_lp_interp, random_hp_interp, in.coherence_q12);
  const int32_t random_interp_out2 = LerpQ12(random_hp_interp, random_lp_interp, in.coherence_q12);

  // `room_q12` is the maximum legal deviation from the knob-defined morph
  // position while staying inside the interval [0, 4096]. Using the smaller of
  // the two distances to the endpoints makes the instability collapse naturally
  // at both edges. The Q12 domain was kept because it preserves exact sine and
  // saw endpoints while staying cheap enough for audio-rate fixed-point math.
  // Alternative considered: 0..4095, but 4096 preserves an exact full-saw
  // endpoint in the final `>> 12` lerp.
  // CPU vs memory tradeoff: this is one compare/subtract per sample instead of
  // a lookup-based curve or precomputed modulation table.
  const uint16_t room_q12 =
      (in.morph_q12 < kHalfQ12) ? in.morph_q12 : uint16_t(engines_din_sum_engine__kUnityQ12 - in.morph_q12);

  // `random_interp` is roughly +/-2048, so `>> 11` maps the product back into a
  // legal Q12 offset around the knob-defined morph position. A larger shift was
  // considered, but it made the center region too tame. A smaller shift pushed
  // too aggressively into the clamps and wasted corridor resolution.
  const int32_t offset_q12_out1 = (random_interp_out1 * int32_t(room_q12)) >> 11;
  int32_t schrodinger_p_q12_out1 = int32_t(in.morph_q12) + offset_q12_out1;
  if (schrodinger_p_q12_out1 < 0) schrodinger_p_q12_out1 = 0;
  if (schrodinger_p_q12_out1 > int32_t(engines_din_sum_engine__kUnityQ12)) schrodinger_p_q12_out1 = int32_t(engines_din_sum_engine__kUnityQ12);

  const int32_t offset_q12_out2 = (random_interp_out2 * int32_t(room_q12)) >> 11;
  int32_t schrodinger_p_q12_out2 = int32_t(in.morph_q12) + offset_q12_out2;
  if (schrodinger_p_q12_out2 < 0) schrodinger_p_q12_out2 = 0;
  if (schrodinger_p_q12_out2 > int32_t(engines_din_sum_engine__kUnityQ12)) schrodinger_p_q12_out2 = int32_t(engines_din_sum_engine__kUnityQ12);

  out1 = Clamp12(LerpQ12(sine, saw_up, uint16_t(schrodinger_p_q12_out1)));
  out2 = Clamp12(LerpQ12(sine, saw_up_shifted, uint16_t(schrodinger_p_q12_out2)));
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/engine_registry.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/engine_registry.h"
#include "pico.h"

namespace mtws {

EngineRegistry::EngineRegistry(SineLUT* lut)
    : sawsome_(),
      bender_(lut),
      floatable_(),
      cumulus_(lut),
      losenge_(lut),
      din_sum_(lut),
      slots_{
          &sawsome_,
          &bender_,
          &floatable_,
          &cumulus_,
          &losenge_,
          &din_sum_,
      } {}

void EngineRegistry::Init() {
  for (uint8_t i = 0; i < kNumOscillatorSlots; ++i) {
    slots_[i]->Init();
  }
}

EngineInterface* __not_in_flash_func(EngineRegistry::Get)(uint8_t slot) {
  if (slot >= kNumOscillatorSlots) {
    slot = 0;
  }
  return slots_[slot];
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/floatable_engine.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/floatable_engine.h"
#include "pico.h"

#include "knots/src/wavetables/floatable_bank_1_16x256.h"
#include "knots/src/wavetables/floatable_bank_4_16x256.h"

namespace mtws {

namespace {
// Clamps the audio sample to the signed 12-bit ComputerCard output range.
inline int32_t __not_in_flash_func(ClampAudio12)(int32_t sample) {
  if (sample > 2047) return 2047;
  if (sample < -2048) return -2048;
  return sample;
}
}  // namespace

// Initializes the oscillator with a cleared phase accumulator.
FloatableEngine::FloatableEngine() : phase_(0) {}

void FloatableEngine::OnSelected() {
  // Keep phase continuity for smooth slot changes.
}

// Interpolates between `a` and `b` using a Q12 fraction. `4096` is used instead
// of `4095` so the endpoint can reach the last stored sample exactly.
int32_t __not_in_flash_func(FloatableEngine::LerpQ12)(int32_t a, int32_t b, uint32_t t_q12) {
  if (t_q12 > 4096U) t_q12 = 4096U;
  return a + ((b - a) * int32_t(t_q12) >> 12);
}

// Converts one axis code into a source-wave selection pair.
// Inputs:
// - axis_code: control-domain morph coordinate in 0..4095.
// Outputs:
// - wave_index: base source wave in 0..14.
// - wave_frac_q12: Q12 fraction in 0..4096 toward wave_index + 1.
void FloatableEngine::ComputeWaveSelection(uint32_t axis_code,
                                           uint8_t& wave_index,
                                           uint16_t& wave_frac_q12) {
  if (axis_code > 4095U) axis_code = 4095U;

  uint32_t wave_pos_q12 = axis_code * kInterpolationCells;
  uint32_t index = wave_pos_q12 >> 12;
  if (index > (kNumSourceWaves - 2U)) index = kNumSourceWaves - 2U;

  uint32_t frac_q12 = wave_pos_q12 & 0x0FFFU;
  if (axis_code == 4095U) frac_q12 = 4096U;

  wave_index = static_cast<uint8_t>(index);
  wave_frac_q12 = static_cast<uint16_t>(frac_q12);
}

// Renders one output sample from a source bank using two interpolation stages.
// Inputs:
// - source_waves: selected bank set with shape [16][256].
// - wave_index/wave_frac_q12: morph position between adjacent source waves.
// - sample_index/sample_next/sample_frac_q12: oscillator phase components.
// Output:
// - one signed 12-bit clamped sample.
int32_t __not_in_flash_func(FloatableEngine::RenderMorphedBankSample)(const int16_t (*source_waves)[kSourceTableSize],
                                                 uint32_t wave_index,
                                                 uint32_t wave_frac_q12,
                                                 uint32_t sample_index,
                                                 uint32_t sample_next,
                                                 uint32_t sample_frac_q12) {
  if (wave_index > (kNumSourceWaves - 2U)) wave_index = kNumSourceWaves - 2U;

  const int16_t* wave_a = source_waves[wave_index];
  const int16_t* wave_b = source_waves[wave_index + 1U];

  int32_t sample_a = LerpQ12(wave_a[sample_index], wave_a[sample_next], sample_frac_q12);
  int32_t sample_b = LerpQ12(wave_b[sample_index], wave_b[sample_next], sample_frac_q12);
  int32_t morphed_sample = LerpQ12(sample_a, sample_b, wave_frac_q12);
  return ClampAudio12(morphed_sample >> 4);
}

// Publishes compact floatable state at control rate.
// Inputs:
// - global control frame (pitch, alt flag, and axis controls).
// Output:
// - floatable engine frame with compact morph parameters only.
void FloatableEngine::ControlTick(const GlobalControlFrame& global, EngineControlFrame& frame) {
  frame.floatable.phase_inc = global.pitch_inc;
  frame.floatable.use_alt_banks = global.mode_alt ? 1U : 0U;
  ComputeWaveSelection(global.macro_x, frame.floatable.out1_wave_index, frame.floatable.out1_wave_frac_q12);
  ComputeWaveSelection(global.macro_y, frame.floatable.out2_wave_index, frame.floatable.out2_wave_frac_q12);
}

// Renders floatable audio directly from source waves at audio rate.
// Inputs:
// - compact floatable control data from the active double-buffered frame.
// Outputs:
// - out1/out2 signed 12-bit samples.
void __not_in_flash_func(FloatableEngine::RenderSample)(const EngineControlFrame& frame, int32_t& out1, int32_t& out2) {
  const FloatableControlFrame& w = frame.floatable;

  phase_ += w.phase_inc;

  uint32_t sample_index = phase_ >> kSourceTableIndexShift;
  uint32_t sample_next = (sample_index + 1U) & kSourceTableMask;
  uint32_t sample_frac_q12 = (phase_ >> kSourceTableFracShift) & 0x0FFFU;

  // Single bank for both outputs. Normal = bank 1, alt = bank 4.
  // X and Y select different morph positions within the same timbral space,
  // halving the flash working set and improving XIP cache hit rate.
  const int16_t (*source)[kSourceTableSize] =
      (w.use_alt_banks != 0U) ? floatable_bank_4_16x256 : floatable_bank_1_16x256;

  out1 = RenderMorphedBankSample(source,
                                 w.out1_wave_index,
                                 w.out1_wave_frac_q12,
                                 sample_index,
                                 sample_next,
                                 sample_frac_q12);
  out2 = RenderMorphedBankSample(source,
                                 w.out2_wave_index,
                                 w.out2_wave_frac_q12,
                                 sample_index,
                                 sample_next,
                                 sample_frac_q12);
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/losenge_engine.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/losenge_engine.h"
#include "pico.h"

namespace mtws {

namespace {
constexpr uint8_t kNumOutputs = 2;
constexpr uint8_t kNumFormants = 3;
constexpr uint8_t kNumVowelAnchors = 5;

// Converts knob domain 0..4095 into interpolation-friendly Q12 0..4096.
inline uint16_t ToU12Q12(uint16_t v) { return (v >= 4095U) ? 4096U : v; }

// Holds the first three formants for one vowel plus their relative amplitudes.
// These anchors mirror the solo losenge implementation so standalone and mtws
// share the same vocal geometry.
struct VowelAnchor {
  uint16_t formant_hz[kNumFormants];
  uint16_t formant_gain_q12[kNumFormants];
};

// Male anchor path derived from the supplied vocal-formant reference image.
constexpr VowelAnchor kMaleAnchors[kNumVowelAnchors] = {
    {{609U, 1000U, 2450U}, {4096U, 2052U, 1028U}},  // A
    {{400U, 1700U, 2300U}, {4096U, 1454U, 1630U}},  // E
    {{238U, 1741U, 2450U}, {4096U, 410U, 648U}},    // IY
    {{325U, 700U, 2550U}, {4096U, 1028U, 205U}},    // O
    {{415U, 1400U, 2200U}, {4096U, 1028U, 648U}},   // U
};

// Alt-mode anchor path using the male F2/F3/F4 formants instead of F1/F2/F3.
// Dropping F1 removes the low-frequency chest of the vowel, producing a
// brighter, thinner, more metallic character. F4 values are ~3300-3500 Hz
// (typical adult male range from published phonetics data). The vowel identity
// is preserved because F2/F3 ratios -- the primary cue -- are unchanged.
// F4 gains are reduced since the fourth formant is naturally quieter.
constexpr VowelAnchor kUpperAnchors[kNumVowelAnchors] = {
    {{1000U, 2450U, 3300U}, {4096U, 2052U, 1028U}},  // A
    {{1700U, 2300U, 3500U}, {4096U, 1454U, 1028U}},  // E
    {{1741U, 2450U, 3300U}, {4096U, 410U, 410U}},    // IY
    {{700U, 2550U, 3400U}, {4096U, 1028U, 205U}},    // O
    {{1400U, 2200U, 3300U}, {4096U, 1028U, 410U}},   // U
};

// Interpolates across the vowel path so X moves through named vowels instead of
// arbitrary formant sweeps. Endpoint handling forces 4096 to the last anchor.
VowelAnchor InterpolateVowelPath(const VowelAnchor (&anchors)[kNumVowelAnchors], uint16_t x_q12) {
  uint32_t scaled = uint32_t(x_q12) * uint32_t(kNumVowelAnchors - 1U);
  uint32_t index = scaled >> 12;
  uint16_t frac = uint16_t(scaled & 0x0FFFU);

  if (index >= uint32_t(kNumVowelAnchors - 1U)) {
    index = kNumVowelAnchors - 2U;
    frac = 4096U;
  }

  VowelAnchor out{};
  const VowelAnchor& a = anchors[index];
  const VowelAnchor& b = anchors[index + 1U];
  for (uint8_t i = 0; i < kNumFormants; ++i) {
    out.formant_hz[i] = uint16_t(uint32_t(a.formant_hz[i]) +
                                 ((int32_t(b.formant_hz[i]) - int32_t(a.formant_hz[i])) * int32_t(frac) >> 12));
    out.formant_gain_q12[i] =
        uint16_t(uint32_t(a.formant_gain_q12[i]) +
                 ((int32_t(b.formant_gain_q12[i]) - int32_t(a.formant_gain_q12[i])) * int32_t(frac) >> 12));
  }
  return out;
}
}  // namespace

// Initializes the engine and clears its phase state.
LosengeEngine::LosengeEngine(SineLUT* lut) : lut_(lut), phase_(0), formant_phase_{{0, 0, 0}, {0, 0, 0}} {
  Init();
}

// Resets the carrier and both output formant banks to the start of a cycle.
void LosengeEngine::Init() {
  phase_ = 0;
  for (uint8_t output = 0; output < kNumOutputs; ++output) {
    for (uint8_t formant = 0; formant < kNumFormants; ++formant) {
      formant_phase_[output][formant] = 0;
    }
  }
}

// Keeps the current oscillator state so slot changes crossfade smoothly.
void LosengeEngine::OnSelected() {
  // Keep oscillator continuity.
}

// Clamps the sample to the signed 12-bit ComputerCard output range.
int32_t __not_in_flash_func(LosengeEngine::Clamp12)(int32_t v) {
  if (v > 2047) return 2047;
  if (v < -2048) return -2048;
  return v;
}

// Converts Hz into a 0.32 phase increment for a 48kHz sample rate.
// Uses a constant reciprocal multiply instead of a 64-bit division by 48000.
// 2^32 / 48000 = 89478.485..., so hz * 89478 gives the phase increment with
// sub-Hz accuracy across the formant range (40-6000 Hz). This saves ~80 cycles
// per call vs the 64-bit division, and is called 6 times per control tick.
uint32_t LosengeEngine::HzToPhaseIncrement(uint32_t hz) {
  return uint32_t(uint64_t(hz) * 89478ULL);
}

// Applies a Q12 tract-size shift to a formant frequency in Hz.
// `shift_q12 = 4096` is neutral, values below it darken/lengthen the tract, and
// values above it brighten/shorten the tract. The endpoint range is 0.5x..1.5x.
uint32_t LosengeEngine::ApplyShiftQ12(uint16_t hz, uint16_t shift_q12) {
  uint32_t shifted_hz = (uint32_t(hz) * uint32_t(shift_q12) + 2048U) >> 12;
  if (shifted_hz < 40U) shifted_hz = 40U;
  if (shifted_hz > 6000U) shifted_hz = 6000U;
  return shifted_hz;
}

// Generates a bipolar square in the signed 12-bit board domain.
int32_t __not_in_flash_func(LosengeEngine::SquareQ12)(uint32_t phase) {
  return (phase < 0x80000000U) ? 2047 : -2048;
}

// Mixes the three formant oscillators, applies the glottal envelope, and scales
// the result by the output gain. The envelope and voice gain are both Q12.
int32_t __not_in_flash_func(LosengeEngine::MixFormantsQ12)(int32_t f1,
                                      int32_t f2,
                                      int32_t f3,
                                      const uint16_t (&amplitudes_q12)[3],
                                      uint16_t envelope_q12,
                                      uint16_t voice_gain_q12) {
  int64_t sum = int64_t(f1) * amplitudes_q12[0] + int64_t(f2) * amplitudes_q12[1] + int64_t(f3) * amplitudes_q12[2];
  int32_t weighted = int32_t((sum + 2048) >> 12);
  int32_t enveloped = int32_t((int64_t(weighted) * envelope_q12 + 2048) >> 12);
  return int32_t((int64_t(enveloped) * voice_gain_q12 + 2048) >> 12);
}

// Converts global controls into a Braids-style vocal-oscillator frame.
// Main sets pitch, X navigates named vowel anchors for Out1, Out2 uses the
// inverse path position so the channels move oppositely without wrapping, Y
// applies a shared formant shift, and alt switches from the standard F1/F2/F3
// formant set to the upper F2/F3/F4 set for a brighter, more metallic timbre.
void LosengeEngine::ControlTick(const GlobalControlFrame& global, EngineControlFrame& frame) {
  LosengeControlFrame& out = frame.losenge;
  out.phase_increment = global.pitch_inc;

  const uint16_t x_q12 = ToU12Q12(global.macro_x);
  const uint16_t out2_x_q12 = uint16_t(4096U - x_q12);
  const VowelAnchor out1_vowel = global.mode_alt ? InterpolateVowelPath(kUpperAnchors, x_q12)
                                                 : InterpolateVowelPath(kMaleAnchors, x_q12);
  const VowelAnchor out2_vowel = global.mode_alt ? InterpolateVowelPath(kUpperAnchors, out2_x_q12)
                                                 : InterpolateVowelPath(kMaleAnchors, out2_x_q12);

  // Y is centered at 1.0x shift so the middle position sounds neutral. Full CCW
  // is a larger/darker tract at 0.5x, and full CW is a smaller/brighter tract at
  // about 1.5x. The formula is linear so the endpoints are predictable.
  const int32_t shift_delta_q12 = ((int32_t(global.macro_y) - 2048) * 2048) >> 11;
  const uint16_t shift_q12 = uint16_t(4096 + shift_delta_q12);

  const VowelAnchor vowels[kNumOutputs] = {out1_vowel, out2_vowel};
  for (uint8_t output = 0; output < kNumOutputs; ++output) {
    for (uint8_t i = 0; i < kNumFormants; ++i) {
      const uint32_t shifted_hz = ApplyShiftQ12(vowels[output].formant_hz[i], shift_q12);
      out.formant_increment[output][i] = HzToPhaseIncrement(shifted_hz);
      out.formant_amplitude_q12[output][i] = vowels[output].formant_gain_q12[i];
    }
  }

  // A fixed gain keeps the formant sum strong without hard-clipping every vowel.
  out.voice_gain_q12 = 4608U;
}

// Renders one sample of the vocal oscillator with separate vowel positions per
// output. The carrier phase defines pitch and resets both formant banks at each
// glottal pulse, which is the main behavior borrowed from Braids/Twists VOWL.
void __not_in_flash_func(LosengeEngine::RenderSample)(const EngineControlFrame& frame, int32_t& out1, int32_t& out2) {
  const LosengeControlFrame& in = frame.losenge;
  const uint32_t previous_phase = phase_;
  phase_ += in.phase_increment;
  if (phase_ < previous_phase) {
    for (uint8_t output = 0; output < kNumOutputs; ++output) {
      for (uint8_t formant = 0; formant < kNumFormants; ++formant) {
        formant_phase_[output][formant] = 0;
      }
    }
  }

  const uint16_t envelope_q12 = uint16_t(4096U - ((phase_ >> 20) & 0x0FFFU));
  int32_t outputs[kNumOutputs] = {0, 0};
  for (uint8_t output = 0; output < kNumOutputs; ++output) {
    formant_phase_[output][0] += in.formant_increment[output][0];
    formant_phase_[output][1] += in.formant_increment[output][1];
    formant_phase_[output][2] += in.formant_increment[output][2];

    const int32_t formant1 = lut_->LookupLinear(formant_phase_[output][0]);
    const int32_t formant2 = lut_->LookupLinear(formant_phase_[output][1]);
    const int32_t formant3 = SquareQ12(formant_phase_[output][2]);
    outputs[output] = MixFormantsQ12(
        formant1, formant2, formant3, in.formant_amplitude_q12[output], envelope_q12, in.voice_gain_q12);
  }

  out1 = Clamp12(outputs[0]);
  out2 = Clamp12(outputs[1]);
}

}  // namespace mtws


// ──────────────────────────────────────────────────────────────────────────────
// Source: engines/sawsome_engine.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "knots/src/engines/sawsome_engine.h"
#include "pico.h"

namespace mtws {

namespace {
constexpr int32_t engines_sawsome_engine__kUnityQ12 = 4096;
constexpr int32_t kDetuneOffsetQ16[kNumSawsomeVoices] = {
    -3920, -2370, -910, 0, 1040, 2610, 3550,
};
constexpr int32_t kPanQ12[kNumSawsomeVoices] = {
    -3686, -2458, -1229, 0, 1229, 2458, 3686,
};
constexpr int32_t kGainQ12[kNumSawsomeVoices] = {
    2048, 2867, 3482, 4096, 3482, 2867, 2048,
};
constexpr uint8_t kCenterVoice = 3;
// Sum of squared full-spread voice gains for the 7-voice table above.
// This reference lets the Y-control makeup gain keep level movement moderate
// as side voices fade in from center-only to the full 7-voice spread.
constexpr uint32_t kFullSpreadPowerQ24 = 65853850U;
constexpr uint32_t kMaxMakeupQ12 = 8192U;

inline uint32_t engines_sawsome_engine__U12ToQ12(uint16_t v) {
  if (v >= 4095U) return 4096U;
  return uint32_t(v);
}

// Integer square root for 64-bit inputs. Used at control rate to derive a
// bounded makeup gain while keeping the engine path on integer math.
uint32_t IntegerSqrt64(uint64_t v) {
  uint64_t bit = 1ULL << 62;
  uint64_t result = 0;

  while (bit > v) {
    bit >>= 2;
  }

  while (bit != 0) {
    if (v >= result + bit) {
      v -= result + bit;
      result = (result >> 1) + bit;
    } else {
      result >>= 1;
    }
    bit >>= 2;
  }

  return uint32_t(result);
}
}  // namespace

SawsomeEngine::SawsomeEngine() {
  Init();
}

void SawsomeEngine::Init() {
  for (uint8_t i = 0; i < kNumSawsomeVoices; ++i) {
    phases_[i] = uint32_t(i) * 0x1f123bb5U;
    tri_state_[i] = 0;
  }
}

void SawsomeEngine::OnSelected() {
  // Keep phase continuity.
}

void SawsomeEngine::ControlTick(const GlobalControlFrame& global, EngineControlFrame& frame) {
  SawsomeControlFrame& out = frame.sawsome;

  const uint32_t width_q12 = engines_sawsome_engine__U12ToQ12(global.macro_x);
  const uint32_t detune_q12 = engines_sawsome_engine__U12ToQ12(global.macro_y);
  uint32_t active_gain_q12[kNumSawsomeVoices];
  out.alt = global.mode_alt;

  // Fade side voices in with detune so full CCW collapses toward the center
  // oscillator while full CW restores the full 7-voice spread.
  uint32_t active_power_q24 = 0;
  for (uint8_t i = 0; i < kNumSawsomeVoices; ++i) {
    uint32_t voice_gain_q12 = uint32_t(kGainQ12[i]);
    if (i != kCenterVoice) {
      voice_gain_q12 = uint32_t((uint64_t(voice_gain_q12) * detune_q12 + 2048U) >> 12);
    }
    active_gain_q12[i] = voice_gain_q12;
    active_power_q24 += voice_gain_q12 * voice_gain_q12;
  }

  // Approximate constant-energy compensation based on the active voice power.
  // This keeps Y movement from sounding like a large level jump while leaving
  // headroom protected by a fixed makeup ceiling.
  uint32_t makeup_q12 = 4096U;
  if (active_power_q24 > 0U) {
    uint64_t makeup_squared_q24 = (uint64_t(kFullSpreadPowerQ24) << 24) / active_power_q24;
    makeup_q12 = IntegerSqrt64(makeup_squared_q24);
    if (makeup_q12 > kMaxMakeupQ12) makeup_q12 = kMaxMakeupQ12;
  }

  for (uint8_t i = 0; i < kNumSawsomeVoices; ++i) {
    // Ratio = 1.0 + (voice detune offset * detune amount).
    int32_t ratio_q16 = 65536 + int32_t((int64_t(kDetuneOffsetQ16[i]) * int32_t(detune_q12)) >> 12);
    if (ratio_q16 < 32768) ratio_q16 = 32768;

    uint64_t inc = (uint64_t(global.pitch_inc) * uint32_t(ratio_q16)) >> 16;
    if (inc > 0x7FFFFFFFULL) inc = 0x7FFFFFFFULL;
    out.voice_phase_increment[i] = uint32_t(inc);
    out.voice_phase_inc_recip_q24[i] = (inc > 0) ? uint32_t((1ULL << 36) / inc) : 0U;

    // Width scales the shared 7-voice pan table before it is converted into
    // left/right gains, so the standalone and integrated engines keep the same
    // stereo image.
    int32_t pan_q12 = int32_t((int64_t(kPanQ12[i]) * int32_t(width_q12)) >> 12);
    int32_t voice_gain_q12 = int32_t((uint64_t(active_gain_q12[i]) * makeup_q12 + 2048U) >> 12);
    int32_t gain_l_q12 = int32_t((int64_t(voice_gain_q12) * (engines_sawsome_engine__kUnityQ12 - pan_q12)) >> 13);
    int32_t gain_r_q12 = int32_t((int64_t(voice_gain_q12) * (engines_sawsome_engine__kUnityQ12 + pan_q12)) >> 13);

    if (gain_l_q12 < 0) gain_l_q12 = 0;
    if (gain_r_q12 < 0) gain_r_q12 = 0;
    out.voice_gain_l_q12[i] = int16_t(gain_l_q12);
    out.voice_gain_r_q12[i] = int16_t(gain_r_q12);
  }
}

int32_t __not_in_flash_func(SawsomeEngine::Clamp12)(int32_t v) {
  if (v > 2047) return 2047;
  if (v < -2048) return -2048;
  return v;
}

// Uses the precomputed reciprocal (recip_q24 = (1<<36)/phase_inc) to replace
// audio-rate 64-bit divisions with 64-bit multiplies, saving ~60 cycles per
// BLEP correction on Cortex-M0+.
int32_t __not_in_flash_func(SawsomeEngine::PolyBlepSawQ12)(uint32_t phase, uint32_t phase_inc, uint32_t recip_q24) {
  int32_t saw = int32_t((phase >> 20) & 0x0FFFU) - 2048;
  if (phase_inc == 0) return saw;

  if (phase < phase_inc) {
    uint32_t t_q12 = uint32_t((uint64_t(phase) * recip_q24) >> 24);
    int32_t x = int32_t(t_q12);
    int32_t corr = x + x - int32_t((int64_t(x) * x) >> 12) - 4096;
    saw -= corr >> 1;
  }

  uint32_t tail = 0xFFFFFFFFU - phase;
  if (tail < phase_inc) {
    uint32_t t_q12 = uint32_t((uint64_t(tail) * recip_q24) >> 24);
    int32_t x = int32_t(t_q12);
    int32_t corr = int32_t((int64_t(x) * x) >> 12);
    saw += corr >> 1;
  }

  return Clamp12(saw);
}

int32_t __not_in_flash_func(SawsomeEngine::PolyBlepTriangleQ12)(int voice_index, uint32_t phase, uint32_t phase_inc, uint32_t recip_q24) {
  int32_t saw = PolyBlepSawQ12(phase, phase_inc, recip_q24);
  tri_state_[voice_index] += saw;
  tri_state_[voice_index] -= tri_state_[voice_index] >> 11;
  return Clamp12(tri_state_[voice_index] >> 5);
}

void __not_in_flash_func(SawsomeEngine::RenderSample)(const EngineControlFrame& frame, int32_t& out1, int32_t& out2) {
  const SawsomeControlFrame& in = frame.sawsome;

  int32_t sum_l = 0;
  int32_t sum_r = 0;

  for (uint8_t i = 0; i < kNumSawsomeVoices; ++i) {
    phases_[i] += in.voice_phase_increment[i];

    int32_t s = in.alt ? PolyBlepTriangleQ12(i, phases_[i], in.voice_phase_increment[i], in.voice_phase_inc_recip_q24[i])
                       : PolyBlepSawQ12(phases_[i], in.voice_phase_increment[i], in.voice_phase_inc_recip_q24[i]);

    sum_l += int32_t((int64_t(s) * in.voice_gain_l_q12[i]) >> 12);
    sum_r += int32_t((int64_t(s) * in.voice_gain_r_q12[i]) >> 12);
  }

  out1 = Clamp12(sum_l >> 1);
  out2 = Clamp12(sum_r >> 1);
}

}  // namespace mtws


} // namespace Card_Knots

extern "C" {
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_Knots::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
