// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include <array>
#include <cmath>
#include <complex>
#include <random>
#include <functional>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <initializer_list>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

#define _Static_assert static_assert
namespace std { using ::sinf; using ::cosf; using ::tanf; using ::asinf; using ::acosf; using ::atanf; using ::atan2f; using ::sqrtf; using ::expf; using ::logf; using ::log10f; using ::powf; }

// DSO-local thread-local variables definition




namespace Card_ChordBlimey {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: main.cpp
// ──────────────────────────────────────────────────────────────────────────────

/*
    Chord Blimey!
    A simple arpeggiator for Music Thing Workshop System Computer
    Tom Waters / Random Works Modular 2024
    Modified by Moses Hoyt 2025

    Send a trigger into Pulse In 1 and get an arpeggio from CV Out & Pulse Out 1

    Pulse Out 2 fires when the last note has finished
    It also fires at startup so you can patch it to Pulse In 1 for looping arpeggios

    CV Out 2 outputs the root note
    The big Knob controls the speed
    The X Knob controls the root note
    The Y Knob controls the chord
    The toggle switch controls the number of notes in the chord and the arpeggiator direction

    CV 1 In controls the root note (added to X Knob)
    CV 2 In controls the chord 0v - 1v (added to Y Knob)

    Audio Out 1 & 2 output a random voltage 0v - 1v for patching to CV Ins
    At the end of a chord a coin is tossed to decide if the output should change
    If starts off unlikely to change and gets more likely with each toss

    LEDs show the current note in the chord
*/

/* stripped system include */
/* stripped system include */
/* stripped pico include */
#include "computer.h"
#include "ui.h"
/* stripped pico include */

// --- Arp helpers ---
static inline int chord_size(const int *row)
{
    int n = 0;
    while (row[n] != -1)
        n++;
    return n;
}

#define TRIGGER_LENGTH 10

Computer computer;
UI ui;

int chords[12][7] = {
    {0, 4, 7, -1},             // M
    {0, 4, 7, 11, -1},         // M7
    {0, 4, 7, 11, 14, -1},     // M9
    {0, 4, 7, 11, 14, 17, -1}, // M11
    {0, 5, 7, -1},             // SUS4
    {0, 4, 8, -1},             // AUG
    {0, 3, 6, -1},             // DIM
    {0, 4, 7, 10, -1},         // DOM7
    {0, 3, 7, 10, 14, 17, -1}, // m11
    {0, 3, 7, 10, 14, -1},     // m9
    {0, 3, 7, 10, -1},         // m7
    {0, 3, 7, -1}              // m
};

bool pulse_in_got[2] = {false, false};
void pulsein_callback(uint gpio, uint32_t events)
{
    pulse_in_got[gpio - PIN_PULSE1_IN] = true;
}

// current play state
bool chord_play = false;
uint chord = 0;
uint chord_note = 0;
uint32_t last_note_time = 0;

int arp_count = 0;
int arp_length = -1;

// --- RANDOM mode state ---
static int rand_order[16]; // permutation buffer (max steps ≤ 16, actual use ≤ 6)
static int rand_size = 0;  // current permutation length (equals base_steps)
static int rand_prev_base_steps = -1;
static int rand_prev_root_semi = -100000;
static int rand_prev_chord = -1; // last observed chord selection for reseed detection
static bool rand_valid = false;  // true = rand_order currently valid

static inline int quantize_semitone_from_volts(float v)
{
    // Quantize to semitone number relative to 0V, matches VOLT_SEMITONE grid
    return (int)floorf(v / VOLT_SEMITONE + 1e-6f);
}

static void reseed_random_order(int size)
{
    if (size < 1)
        size = 1;
    if (size > (int)(sizeof(rand_order) / sizeof(rand_order[0])))
        size = (int)(sizeof(rand_order) / sizeof(rand_order[0]));
    rand_size = size;
    for (int i = 0; i < size; ++i)
        rand_order[i] = i;
    // Fisher–Yates shuffle using Pico RNG
    for (int i = size - 1; i > 0; --i)
    {
        uint32_t r = get_rand_32();
        int j = (int)(r % (uint32_t)(i + 1));
        int tmp = rand_order[i];
        rand_order[i] = rand_order[j];
        rand_order[j] = tmp;
    }
    rand_valid = true;
}

int main()
{
    stdio_init_all();
    computer.init();
    computer.calibrateIfSwitchDown();

    computer.setPulseCallback(1, pulsein_callback);
    ui.init(&computer);

    // output trigger on pulse 2 to start looping if patched
    computer.setTimedPulse(2, TRIGGER_LENGTH);

    #ifdef __EMSCRIPTEN__
    g_wasm_background_tick = []() {
        
        uint32_t now = to_ms_since_boot(get_absolute_time());
        computer.poll();
        ui.checkSwitch();
        arp_length = ui.getArpLength();

        // If mode changed, restart the cycle immediately in the new direction
        if (ui.consumeModeChanged())
        {
            if (chord_play)
            {
                arp_count = 0;      // restart from beginning of pattern
                last_note_time = 0; // play immediately on next tick
            }
            // If entering RANDOM, force a new permutation next note
            if (ui.getArpMode() == ARP_RANDOM)
            {
                rand_valid = false;
            }
        }

        // if we get a pulse start a new arp
        if (pulse_in_got[0])
        {
            pulse_in_got[0] = false;
            chord_note = 0;
            arp_count = 0;

            ui.spinRandomOuts();

            chord = ui.getChord();
            chord_play = true;
            last_note_time = 0; // reset so we play immediately
        }

        // if time for a new note
        uint note_length = ui.getNoteLengthMS();
        if (chord_play && (now - last_note_time >= note_length || last_note_time == 0))
        {
            // Determine chord size and the total length of this arpeggio cycle
            int csize = chord_size(chords[chord]);                   // notes in this chord
            int base_steps = (arp_length >= 0) ? arp_length : csize; // base notes to emit this cycle

            // For UPUP and DOWNDOWN modes, double the total steps (each note played twice)
            ArpMode mode = ui.getArpMode();
            int total_steps;
            if (mode == ARP_UPUP || mode == ARP_DOWNDOWN)
            {
                total_steps = base_steps * 2;
            }
            else if (mode == ARP_UPDOWN_INC)
            {
                total_steps = base_steps * 2;
            }
            else if (mode == ARP_UPDOWN_EXC)
            {
                total_steps = (base_steps <= 1) ? 1 : (base_steps * 2 - 2);
            }
            else
            {
                total_steps = base_steps; // UP or DOWN or RANDOM
            }

            // RANDOM mode: detect changes that require reseed & immediate restart
            if (mode == ARP_RANDOM)
            {
                // Quantize root to semitone for stable detection
                float rv = ui.getRootVolts();
                int root_semi = quantize_semitone_from_volts(rv);
                int observed_chord = ui.getChord(); // detect knob/CV change even mid-cycle

                bool need_reseed = false;
                if (!rand_valid)
                    need_reseed = true;
                if (rand_prev_base_steps != base_steps)
                    need_reseed = true;
                if (rand_prev_root_semi != root_semi)
                    need_reseed = true;
                if (rand_prev_chord != observed_chord)
                    need_reseed = true;

                if (need_reseed)
                {
                    reseed_random_order(base_steps);
                    rand_prev_base_steps = base_steps;
                    rand_prev_root_semi = root_semi;
                    rand_prev_chord = observed_chord;
                    // restart immediately to begin the new permutation cleanly
                    arp_count = 0;
                    last_note_time = 0;
                    // Recompute timing gate for this tick
                    return; // go to next loop; we'll emit the first step of the new order on next pass
                }
            }

            // End-of-arp condition
            if (csize <= 0 || arp_count >= total_steps)
            {
                computer.setTimedPulse(2, TRIGGER_LENGTH);
                chord_play = false;
                return;
            }

            // set next note time and update UI
            last_note_time = now;
            ui.update();

            // step number within the full cycle according to current mode
            int s;
            int t = arp_count; // 0..total_steps-1 within a single cycle

            switch (mode)
            {
            case ARP_UP:
                s = t;
                break;

            case ARP_DOWN:
                s = total_steps - 1 - t;
                break;

            case ARP_UPUP:
                // 0,0,1,1,2,2 (ascending)
                s = t / 2;
                break;

            case ARP_DOWNDOWN:
                // ...3,3,2,2,1,1,0,0 (descending)
                s = (base_steps - 1) - (t / 2);
                break;

            case ARP_UPDOWN_INC:
                // Up then down, inclusive (peak is played twice)
                // Sequence length = 2 * base_steps
                // t: 0..base_steps-1 (up), base_steps..2*base_steps-1 (down incl endpoints)
                if (t < base_steps)
                {
                    s = t;
                }
                else
                {
                    s = (2 * base_steps - 1) - t;
                }
                break;

            case ARP_UPDOWN_EXC:
                // Up then down, exclusive (no double-count of endpoints)
                // Sequence length = 2 * base_steps - 2  (unless base_steps <= 1 -> 1)
                if (total_steps <= 1)
                {
                    s = 0;
                }
                else if (t < base_steps)
                {
                    s = t; // up 0..base_steps-1
                }
                else
                {
                    s = total_steps - t; // down base_steps-2 .. 1
                }
                break;

            case ARP_RANDOM:
                // Random but repeating order over the expanded step space (0..base_steps-1)
                // Ensure rand_order is valid (it should be, due to the reseed logic above)
                if (!rand_valid || rand_size != base_steps)
                {
                    reseed_random_order(base_steps);
                }
                s = rand_order[t];
                break;

            default:
                s = t; // safe fallback
                break;
            }

            // derive pitch from step number: base degree and octave shift
            int base_idx = (csize > 0) ? (s % csize) : 0;
            int octave_shift = (csize > 0) ? (s / csize) : 0; // 0 for first pass, 1 for second, etc.
            chord_note = base_idx;                            // same degree mapping for all modes; direction is encoded in s

            float chord_root_volts = ui.getRootVolts();
            if (octave_shift > 0)
            {
                chord_root_volts += (float)octave_shift; // +1V per full pass
            }

            float chord_note_volts = chord_root_volts + ((float)chords[chord][chord_note] * VOLT_SEMITONE);
            computer.setCVOutVolts(1, chord_note_volts);
            computer.setCVOutVolts(2, chord_root_volts);

            computer.setTimedPulse(1, TRIGGER_LENGTH);

            // show step number (wrap across 6 LEDs) only if suppression time passed
            if ((now - ui.last_switch_change) >= UI::LED_SUPPRESS_MS)
            {
                int led_index = (total_steps > 0) ? (s % 6) : 0;
                computer.setLEDs(1 << led_index);
            }

            // advance to next step in this cycle
            arp_count++;
        }
    
    };
#else
    while (true) {
        
        uint32_t now = to_ms_since_boot(get_absolute_time());
        computer.poll();
        ui.checkSwitch();
        arp_length = ui.getArpLength();

        // If mode changed, restart the cycle immediately in the new direction
        if (ui.consumeModeChanged())
        {
            if (chord_play)
            {
                arp_count = 0;      // restart from beginning of pattern
                last_note_time = 0; // play immediately on next tick
            }
            // If entering RANDOM, force a new permutation next note
            if (ui.getArpMode() == ARP_RANDOM)
            {
                rand_valid = false;
            }
        }

        // if we get a pulse start a new arp
        if (pulse_in_got[0])
        {
            pulse_in_got[0] = false;
            chord_note = 0;
            arp_count = 0;

            ui.spinRandomOuts();

            chord = ui.getChord();
            chord_play = true;
            last_note_time = 0; // reset so we play immediately
        }

        // if time for a new note
        uint note_length = ui.getNoteLengthMS();
        if (chord_play && (now - last_note_time >= note_length || last_note_time == 0))
        {
            // Determine chord size and the total length of this arpeggio cycle
            int csize = chord_size(chords[chord]);                   // notes in this chord
            int base_steps = (arp_length >= 0) ? arp_length : csize; // base notes to emit this cycle

            // For UPUP and DOWNDOWN modes, double the total steps (each note played twice)
            ArpMode mode = ui.getArpMode();
            int total_steps;
            if (mode == ARP_UPUP || mode == ARP_DOWNDOWN)
            {
                total_steps = base_steps * 2;
            }
            else if (mode == ARP_UPDOWN_INC)
            {
                total_steps = base_steps * 2;
            }
            else if (mode == ARP_UPDOWN_EXC)
            {
                total_steps = (base_steps <= 1) ? 1 : (base_steps * 2 - 2);
            }
            else
            {
                total_steps = base_steps; // UP or DOWN or RANDOM
            }

            // RANDOM mode: detect changes that require reseed & immediate restart
            if (mode == ARP_RANDOM)
            {
                // Quantize root to semitone for stable detection
                float rv = ui.getRootVolts();
                int root_semi = quantize_semitone_from_volts(rv);
                int observed_chord = ui.getChord(); // detect knob/CV change even mid-cycle

                bool need_reseed = false;
                if (!rand_valid)
                    need_reseed = true;
                if (rand_prev_base_steps != base_steps)
                    need_reseed = true;
                if (rand_prev_root_semi != root_semi)
                    need_reseed = true;
                if (rand_prev_chord != observed_chord)
                    need_reseed = true;

                if (need_reseed)
                {
                    reseed_random_order(base_steps);
                    rand_prev_base_steps = base_steps;
                    rand_prev_root_semi = root_semi;
                    rand_prev_chord = observed_chord;
                    // restart immediately to begin the new permutation cleanly
                    arp_count = 0;
                    last_note_time = 0;
                    // Recompute timing gate for this tick
                    return; // go to next loop; we'll emit the first step of the new order on next pass
                }
            }

            // End-of-arp condition
            if (csize <= 0 || arp_count >= total_steps)
            {
                computer.setTimedPulse(2, TRIGGER_LENGTH);
                chord_play = false;
                return;
            }

            // set next note time and update UI
            last_note_time = now;
            ui.update();

            // step number within the full cycle according to current mode
            int s;
            int t = arp_count; // 0..total_steps-1 within a single cycle

            switch (mode)
            {
            case ARP_UP:
                s = t;
                break;

            case ARP_DOWN:
                s = total_steps - 1 - t;
                break;

            case ARP_UPUP:
                // 0,0,1,1,2,2 (ascending)
                s = t / 2;
                break;

            case ARP_DOWNDOWN:
                // ...3,3,2,2,1,1,0,0 (descending)
                s = (base_steps - 1) - (t / 2);
                break;

            case ARP_UPDOWN_INC:
                // Up then down, inclusive (peak is played twice)
                // Sequence length = 2 * base_steps
                // t: 0..base_steps-1 (up), base_steps..2*base_steps-1 (down incl endpoints)
                if (t < base_steps)
                {
                    s = t;
                }
                else
                {
                    s = (2 * base_steps - 1) - t;
                }
                break;

            case ARP_UPDOWN_EXC:
                // Up then down, exclusive (no double-count of endpoints)
                // Sequence length = 2 * base_steps - 2  (unless base_steps <= 1 -> 1)
                if (total_steps <= 1)
                {
                    s = 0;
                }
                else if (t < base_steps)
                {
                    s = t; // up 0..base_steps-1
                }
                else
                {
                    s = total_steps - t; // down base_steps-2 .. 1
                }
                break;

            case ARP_RANDOM:
                // Random but repeating order over the expanded step space (0..base_steps-1)
                // Ensure rand_order is valid (it should be, due to the reseed logic above)
                if (!rand_valid || rand_size != base_steps)
                {
                    reseed_random_order(base_steps);
                }
                s = rand_order[t];
                break;

            default:
                s = t; // safe fallback
                break;
            }

            // derive pitch from step number: base degree and octave shift
            int base_idx = (csize > 0) ? (s % csize) : 0;
            int octave_shift = (csize > 0) ? (s / csize) : 0; // 0 for first pass, 1 for second, etc.
            chord_note = base_idx;                            // same degree mapping for all modes; direction is encoded in s

            float chord_root_volts = ui.getRootVolts();
            if (octave_shift > 0)
            {
                chord_root_volts += (float)octave_shift; // +1V per full pass
            }

            float chord_note_volts = chord_root_volts + ((float)chords[chord][chord_note] * VOLT_SEMITONE);
            computer.setCVOutVolts(1, chord_note_volts);
            computer.setCVOutVolts(2, chord_root_volts);

            computer.setTimedPulse(1, TRIGGER_LENGTH);

            // show step number (wrap across 6 LEDs) only if suppression time passed
            if ((now - ui.last_switch_change) >= UI::LED_SUPPRESS_MS)
            {
                int led_index = (total_steps > 0) ? (s % 6) : 0;
                computer.setLEDs(1 << led_index);
            }

            // advance to next step in this cycle
            arp_count++;
        }
    
    }
#endif

    return 0;
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: computer.cpp
// ──────────────────────────────────────────────────────────────────────────────

/* stripped system include */
/* stripped system include */
/* stripped system include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */

#include "computer.h"

void Computer::init() {
    initLEDs();
    initPulse();
    initCVOut();
    initMux();
    initAudioIn();
    initAudioOut();
    calibration_data = readCalibration();
    cv_in1_calibrated_helper = (12.0f / 4096.0f) * (float)calibration_data.cv_in1;
    cv_in2_calibrated_helper = (12.0f / 4096.0f) * (float)calibration_data.cv_in2;
    cv_out1_calibrated_helper = (2048.0f - (float)calibration_data.cv_out1) / 6.16f;
    cv_out2_calibrated_helper = (2048.0f - (float)calibration_data.cv_out2) / 6.16f;

    initVersion();
    readVersion();
}

void Computer::poll() {
    uint32_t now = to_ms_since_boot(get_absolute_time());

    // check if we should end any timed pulses
    for(int i=0; i<2; i++) {
        if(timed_pulse_out[i].enabled && now - timed_pulse_out[i].start_time >= timed_pulse_out[i].length) {
            timed_pulse_out[i].enabled = false;
            gpio_put(PIN_PULSE1_OUT + i, true); // inverted
        }
    }
}

#pragma region HardwareVersion
void Computer::initVersion() {
    gpio_init(PIN_VER1);
    gpio_set_dir(PIN_VER1, GPIO_IN);
    gpio_init(PIN_VER2);
    gpio_set_dir(PIN_VER2, GPIO_IN);
    gpio_init(PIN_VER3);
    gpio_set_dir(PIN_VER3, GPIO_IN);
}

void Computer::readVersion() {
    board_version = (gpio_get(PIN_VER3) << 2) | (gpio_get(PIN_VER2) << 1) | gpio_get(PIN_VER1);
}
#pragma endregion HardwareVersion

#pragma region LEDs
void Computer::initLEDs() {
    for(int i=PIN_LED1_OUT; i<PIN_LED1_OUT+6; i++) {
        gpio_init(i);
        gpio_set_dir(i, GPIO_OUT);
    }
    setAllLEDs(false);
}

// Set all LEDs on or off
void Computer::setAllLEDs(bool value) {
    uint32_t set = value ? PIN_MASK_LEDS : 0;
    sleep_us(1);
    gpio_put_masked(PIN_MASK_LEDS, set);
    sleep_us(1);
}

// Set LED bits (e.g. LEDs 1 & 3 = 5)
void Computer::setLEDs(uint8_t values) {
    gpio_put_masked(PIN_MASK_LEDS, (values & 0x3F) << PIN_LED1_OUT);
}

// Set a single LED on or off (1 based)
void Computer::setLED(uint8_t led, bool value) {
    gpio_put(PIN_LED1_OUT + led - 1, value);
}
#pragma endregion

#pragma region Pulse
void Computer::initPulse() {
    // Pulse In pullup
    gpio_init(PIN_PULSE1_IN);
    gpio_set_dir(PIN_PULSE1_IN, GPIO_IN);
    gpio_pull_up(PIN_PULSE1_IN);

    gpio_init(PIN_PULSE2_IN);
    gpio_set_dir(PIN_PULSE2_IN, GPIO_IN);
    gpio_pull_up(PIN_PULSE2_IN);

    // Pulse Out
    gpio_init(PIN_PULSE1_OUT);
    gpio_set_dir(PIN_PULSE1_OUT, GPIO_OUT);
    gpio_put(PIN_PULSE1_OUT, true);

    gpio_init(PIN_PULSE2_OUT);
    gpio_set_dir(PIN_PULSE2_OUT, GPIO_OUT);
    gpio_put(PIN_PULSE2_OUT, true);

    for(int i=0; i<2; i++) {
        timed_pulse_out[i].enabled = false;
        timed_pulse_out[i].start_time = 0;
        timed_pulse_out[i].length = 0;
    }
}

// Get the value of Pulse In 1 or 2
bool Computer::getPulse(uint8_t output) {
    if(output < 1 || output > 2) { 
        return false;
    }
    return !gpio_get(PIN_PULSE1_IN + output - 1);
}

// Set the value of Pulse Out 1 or 2
void Computer::setPulse(uint8_t output, bool value) {
    if(output < 1 || output > 2) { 
        return;
    }

    // Pulse outputs are inverted
    gpio_put(PIN_PULSE1_OUT + output - 1, !value);
}

void Computer::setPulseCallback(uint8_t input, gpio_irq_callback_t callback) {
    uint gpio = input == 1 ? PIN_PULSE1_IN : PIN_PULSE2_IN;
    gpio_set_irq_enabled_with_callback(gpio, GPIO_IRQ_EDGE_FALL, true, callback);
}

// Output Pulse 1 or 2 for length_ms milliseconds
void Computer::setTimedPulse(uint8_t output, uint32_t length_ms) {
    uint8_t idx = output - 1;
    timed_pulse_out[idx].enabled = true;
    timed_pulse_out[idx].length = length_ms;
    timed_pulse_out[idx].start_time = to_ms_since_boot(get_absolute_time());
    gpio_put(PIN_PULSE1_OUT + idx, false); // inverted
}
#pragma endregion Pulse

#pragma region CVOut
void Computer::initCVOut() {
    gpio_set_function(PIN_CV1_OUT, GPIO_FUNC_PWM);
    gpio_set_function(PIN_CV2_OUT, GPIO_FUNC_PWM);

    cv_out1_slice = pwm_gpio_to_slice_num(PIN_CV1_OUT);
    cv_out1_channel = pwm_gpio_to_channel(PIN_CV1_OUT);
    cv_out2_slice = pwm_gpio_to_slice_num(PIN_CV2_OUT);
    cv_out2_channel = pwm_gpio_to_channel(PIN_CV2_OUT);

    pwm_set_wrap(cv_out1_slice, 2047); // 11 bit 60kHz
    pwm_set_wrap(cv_out2_slice, 2047);

    pwm_set_enabled(cv_out1_slice, true);
    pwm_set_enabled(cv_out2_slice, true);
}

void Computer::setCVOut(uint8_t output, uint16_t value) {
    if(board_version > 0) {
        value = 2047 - value;
    }

    if(output == 1) {
        pwm_set_chan_level(cv_out1_slice, cv_out1_channel, value);
    } else if(output == 2) {
        pwm_set_chan_level(cv_out2_slice, cv_out2_channel, value);
    }
}

void Computer::setCVOutVolts(uint8_t output, float volts) {
    if(output == 1) {
        setCVOut(output, calibration_data.cv_out1 + (volts * cv_out1_calibrated_helper));
    } else if(output == 2) {
        setCVOut(output, calibration_data.cv_out2 + (volts * cv_out2_calibrated_helper));
    }
}

#pragma endregion

#pragma region MUX
void Computer::initMux() {
    gpio_init(PIN_MUX_LOGIC_A);
    gpio_set_dir(PIN_MUX_LOGIC_A, GPIO_OUT);
    gpio_init(PIN_MUX_LOGIC_B);
    gpio_set_dir(PIN_MUX_LOGIC_B, GPIO_OUT);

    adc_init();
    adc_gpio_init(PIN_MUX_OUT_X);
    adc_gpio_init(PIN_MUX_OUT_Y);
}

/*
MUX Logic to Channel
b a
0 0 = x0 y0
0 1 = x1 y1
1 0 = x2 y2
1 1 = x3 y3
*/
// bank: x = 0, y = 1
// chan: 0 - 3
uint16_t Computer::getMuxValue(uint8_t bank, uint8_t chan) {
    bool logic_a = (chan & 1) ? true : false;
    bool logic_b = (chan >> 1) ? true : false;   
    gpio_put(PIN_MUX_LOGIC_A, logic_a);
    gpio_put(PIN_MUX_LOGIC_B, logic_b);
    
    sleep_us(10);
    adc_select_input(bank + 2);
    return adc_read();
}

// Get the current switch state
ComputerSwitchState Computer::getSwitchState() {
    // Switch = pin 11 x3
    uint16_t switch_value = getMuxValue(0, 3);

    if(switch_value > 3000) {
        return ComputerSwitchState::UP;
    } else if(switch_value < 1000) {
        return ComputerSwitchState::DOWN;
    } else {
        return ComputerSwitchState::MID;
    }
}

// ~ 0 to 4095
uint16_t Computer::getPotXValue() {
    // Pot x = pin 12 x0    
    return getMuxValue(0, 1);
}
uint16_t Computer::getPotYValue() {
    // Pot y = pin 14 x1
    return getMuxValue(0, 2);
}
uint16_t Computer::getPotZValue() {
    // Pot z = pin 15 x2
    return getMuxValue(0, 0);
}

uint16_t Computer::getCVIn1Value() {
    // CV 1 in = pin 1 & 2 y0, y2
    return getMuxValue(1, 0);
}
uint16_t Computer::getCVIn2Value() {
    // CV 2 in = pin 4 & 5 y3, y1
    return getMuxValue(1, 1);
}

float Computer::getCVInVolts(uint8_t input) {
    float n = -0.0029296875; //0 - (12/4096)
    float result = 0;
    if(input == 1) {
        result = (n * averageCVInput(input)) + cv_in1_calibrated_helper;
        return result;
    } else if(input == 2) {
        result = (n * averageCVInput(input)) + cv_in2_calibrated_helper;
    }
    return result;
}

#pragma endregion MUX

#pragma region AudioIn
void Computer::initAudioIn() {
    adc_init();
    adc_gpio_init(PIN_AUDIO_IN1);
    adc_gpio_init(PIN_AUDIO_IN2);
}

uint16_t Computer::getAudioIn(uint8_t input) {
    adc_select_input(input == 1 ? 1 : 0);
    return adc_read();
}
#pragma endregion

#pragma region AudioOut

void Computer::initAudioOut() {
    // Initialize SPI channel (channel, baud rate set to 20MHz)
    spi_init(DAC_SPI_PORT, 20000000);
    // Format (channel, data bits per transfer, polarity, phase, order)
    spi_set_format(DAC_SPI_PORT, 16, SPI_CPOL_0, SPI_CPHA_0, SPI_LSB_FIRST);

    // Map SPI signals to GPIO ports    
    gpio_set_function(PIN_SCK, GPIO_FUNC_SPI);
    gpio_set_function(PIN_MOSI, GPIO_FUNC_SPI);
    gpio_set_function(PIN_CS, GPIO_FUNC_SPI);

    // Init to 0v
    setAudioOut(1, 1024);
    setAudioOut(2, 1024);
}

void Computer::setAudioOut(uint8_t output, uint16_t value) {
    uint16_t DAC_data = (output == 1 ? DAC_config_chan_A_gain : DAC_config_chan_B_gain) | ((value + CALIBRATE_DAC_OUT) & 0xffff);
    spi_write16_blocking(DAC_SPI_PORT, &DAC_data, 1);
}
#pragma endregion

#pragma region Calibration
CalibrationData Computer::readCalibration() {
    CalibrationData result;

    uint8_t *p = (uint8_t *)(XIP_BASE + CALIBRATION_FLASH_START);
    uint8_t first_byte = *p;

    // if we don't have calibration saved, use defaults
    if(first_byte != CALIBRATION_FIRST_BYTE) {
        result.cv_in1 = CALIBRATION_DEFAULT_CV_IN;
        result.cv_in2 = CALIBRATION_DEFAULT_CV_IN;
        result.cv_out1 = CALIBRATION_DEFAULT_CV_OUT;
        result.cv_out2 = CALIBRATION_DEFAULT_CV_OUT;
    }
    else
    {
        p++;
        memcpy(&result.cv_in1, p, sizeof(result.cv_in1));
        p += sizeof(result.cv_in1);
        memcpy(&result.cv_in2, p, sizeof(result.cv_in2));
        p += sizeof(result.cv_in2);
        memcpy(&result.cv_out1, p, sizeof(result.cv_out1));
        p += sizeof(result.cv_out1);
        memcpy(&result.cv_out2, p, sizeof(result.cv_out2));
    }

    return result;
}

void Computer::writeCalibration() {
    // if the settings match whats in the flash, don't save
    CalibrationData stored_data = readCalibration();
    if(calibration_data.equals(stored_data)) {
        return;
    }
    
    uint8_t buffer[FLASH_SECTOR_SIZE];
    buffer[0] = CALIBRATION_FIRST_BYTE;
    uint8_t *p = buffer + 1;
    memcpy(p, &calibration_data.cv_in1, sizeof(calibration_data.cv_in1));
    p += sizeof(calibration_data.cv_in1);
    memcpy(p, &calibration_data.cv_in2, sizeof(calibration_data.cv_in2));
    p += sizeof(calibration_data.cv_in2);
    memcpy(p, &calibration_data.cv_out1, sizeof(calibration_data.cv_out1));
    p += sizeof(calibration_data.cv_out1);
    memcpy(p, &calibration_data.cv_out2, sizeof(calibration_data.cv_out2));

    uint32_t irqs = save_and_disable_interrupts();
    flash_range_erase(CALIBRATION_FLASH_START, FLASH_SECTOR_SIZE);
    flash_range_program(CALIBRATION_FLASH_START, buffer, FLASH_SECTOR_SIZE);
    restore_interrupts(irqs);
}

uint16_t Computer::averageCVInput(uint8_t output) {
    int16_t num_samples = 100;
    uint32_t total = 0;
    for(int i=0; i<num_samples; i++) {
        if(output == 1) {
            total += getCVIn1Value();
        } else if(output == 2) {
            total += getCVIn2Value();
        }
    }

    return total / num_samples;
}

void Computer::calibrateIfSwitchDown() {
    
    ComputerSwitchState switch_state = getSwitchState();
    if(switch_state == ComputerSwitchState::DOWN) {
        // get cv in averages with nothing connected
        uint16_t nc1 = averageCVInput(1);
        uint16_t nc2 = averageCVInput(2);

        // all leds on, wait for switch up and then down again
        setAllLEDs(true);
        while(getSwitchState() == ComputerSwitchState::DOWN);
        while(getSwitchState() != ComputerSwitchState::DOWN);

        // set ideal 0v out
        setCVOut(1, CALIBRATION_DEFAULT_CV_OUT);
        setCVOut(2, CALIBRATION_DEFAULT_CV_OUT);
        sleep_ms(1000);
        uint16_t ideal_out_zero1 = averageCVInput(1);
        uint16_t ideal_out_zero2 = averageCVInput(2);

        calibration_data.cv_in1 = nc1;
        calibration_data.cv_in2 = nc2;
        calibration_data.cv_out1 = CALIBRATION_DEFAULT_CV_OUT * ((float)ideal_out_zero1 / (float)nc1);
        calibration_data.cv_out2 = CALIBRATION_DEFAULT_CV_OUT * ((float)ideal_out_zero2 / (float)nc2);
        writeCalibration();

        setAllLEDs(false);
    }
}
#pragma endregion


// ──────────────────────────────────────────────────────────────────────────────
// Source: ui.cpp
// ──────────────────────────────────────────────────────────────────────────────

#include "ui.h"
/* stripped pico include */
/* stripped pico include */
/* stripped system include */

void UI::init(Computer *computer)
{
    _computer = computer;

    coin_weight[0] = UINT32_MAX;
    coin_weight[1] = UINT32_MAX;

    // Initialize prev state to current to avoid spurious edge handling on boot
    prev_switch_state = _computer->getSwitchState();
}

int UI::getArpLength()
{
    return fix_length_on ? fix_length : -1;
}

float UI::getRootVolts()
{
    return root_volts;
}

uint UI::getNoteLengthMS()
{
    // invert knob value and curve it so we have more control over the faster end
    return pow(2, (4095 - _computer->getPotZValue()) / 300) + 20;
}

uint UI::getChord()
{
    float knoby_volts = _computer->getPotYValue() * MUX_BY_VOLT;
    float cv2_volts = _computer->getCVInVolts(2);

    float total_volts = cv2_volts + knoby_volts;

    if (total_volts > 1.0f)
    {
        return 11;
    }
    else if (total_volts < 0.0f)
    {
        return 0;
    }
    else
    {
        return floor(total_volts / VOLT_SEMITONE);
    }
}

void UI::update()
{
    float knobx_volts = _computer->getPotXValue() * MUX_BY_VOLT;
    root_volts = _computer->getCVInVolts(1) + knobx_volts;
}

void UI::checkSwitch()
{
    uint32_t now = to_ms_since_boot(get_absolute_time());

    // Clear LED hold when the time has elapsed
    if (led_hold_active && (int32_t)(now - led_hold_until) >= 0)
    {
        led_hold_active = false;
    }

    // switch
    // up  = play full length of chord
    // mid = limit number of notes
    // down short press = toggle number of notes (existing)
    // down long  press = toggle arp direction mode (new)
    ComputerSwitchState switch_state = _computer->getSwitchState();

    if (switch_state != prev_switch_state)
    {
        // Leaving DOWN: resolve short vs long
        if (prev_switch_state == ComputerSwitchState::DOWN)
        {
            if (down_pending_short && !down_long_consumed)
            {
                // SHORT PRESS (existing behavior)
                fix_length++;
                if (fix_length > 6)
                {
                    fix_length = 1;
                }
                if (!led_hold_active)
                {
                    last_switch_change = now;
                    _computer->setLEDs(0x3f >> (6 - fix_length));
                }
            }
            // reset DOWN press state
            down_pending_short = false;
            down_long_consumed = false;
            down_press_start = 0;
        }

        // Entering new state
        if (switch_state == ComputerSwitchState::DOWN)
        {
            down_press_start = now;
            down_pending_short = true;
            down_long_consumed = false;
            // do not change LEDs yet; we decide after timing
        }
        else if (switch_state == ComputerSwitchState::MID)
        {
            // existing behavior: MID means fixed-length ON
            fix_length_on = true;
            if (!led_hold_active)
            {
                last_switch_change = now;
                _computer->setLEDs(0x3f >> (6 - fix_length));
            }
        }
        else
        { // UP
            // existing behavior: full-length mode (fixed-length OFF)
            fix_length_on = false;
            if (!led_hold_active)
            {
                last_switch_change = 0;
            }
        }

        prev_switch_state = switch_state;
    }

    // While holding in DOWN, detect long press
    if (switch_state == ComputerSwitchState::DOWN &&
        down_press_start != 0 && !down_long_consumed)
    {
        if ((now - down_press_start) >= LONGPRESS_MS)
        {
            // LONG PRESS: cycle through arp direction modes (7 modes)
            arp_mode = (ArpMode)((arp_mode + 1) % 7);
            mode_changed = true; // notify main to adopt new mode
            down_long_consumed = true;
            down_pending_short = false; // suppress short press action

            // Brief LED hint so user sees the change (no pulse here to avoid TRIGGER_LENGTH dep)
            // Different LED patterns for each mode
            uint8_t led_pattern;
            switch (arp_mode)
            {
            case ARP_UP:
                led_pattern = 0b000001;
                break; // top left
            case ARP_DOWN:
                led_pattern = 0b010000;
                break; // bottom left
            case ARP_UPUP:
                led_pattern = 0b000011;
                break; // two at the top
            case ARP_DOWNDOWN:
                led_pattern = 0b110000;
                break; // two at the bottom
            case ARP_UPDOWN_INC:
                led_pattern = 0b010010;
                break; // top right and bottom left
            case ARP_UPDOWN_EXC:
                led_pattern = 0b100001;
                break; // top left and bottom right
            case ARP_RANDOM:
                led_pattern = 0b011001;
                break; // top left, middle right, bottom left
            default:
                led_pattern = 0b000001;
                break;
            }
            _computer->setLEDs(led_pattern);
            // Start LED hold so this hint remains visible; also mark last_switch_change
            led_hold_active = true;
            led_hold_until = now + LED_SUPPRESS_MS;
            last_switch_change = now; // ensures main.cpp suppresses step LEDs during hold
        }
    }
}

void UI::spinRandomOuts()
{
    bool any_changed = false;
    for (int i = 0; i < 2; i++)
    {
        uint32_t change_value = get_rand_32();
        if (coin_weight[i] < change_value)
        {
            coin_weight[i] = UINT32_MAX;

            // output a random value from 0v to 1v
            uint r = get_rand_32() * 0.000000002561137081;
            uint output_val = 1024 - (r * 14.22222222) + 0.5;

            _computer->setAudioOut(i + 1, output_val);
            any_changed = true;
        }
        else
        {
            // increase probability of changing next time
            coin_weight[i] -= 0xfffffff;
        }
    }

    // add delay so outputs settle
    if (any_changed)
    {
        sleep_us(500);
    }
}


} // namespace Card_ChordBlimey

extern "C" {
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_ChordBlimey::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
